name: 'Update PR Workflow Status'
description: 'Update PR comment with workflow status'

inputs:
  workflow-status:
    description: 'Overall workflow status'
    required: true
  workflow-table:
    description: 'Workflow status table'
    required: true
  commit-sha:
    description: 'Commit SHA'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate status message
      id: message
      shell: bash
      run: ${{ github.action_path }}/scripts/generate-status-message.sh
      env:
        WORKFLOW_STATUS: ${{ inputs.workflow-status }}

    - name: Create or update PR comment
      uses: thollander/actions-comment-pull-request@v3
      with:
        message: |
          ## 🔄 Workflow Status Report

          **Commit:** `${{ inputs.commit-sha }}`

          ${{ steps.message.outputs.status-message }}

          ${{ inputs.workflow-table }}
        comment-tag: workflow-status
        mode: upsert
        pr-number: ${{ inputs.pr-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      continue-on-error: true
