# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: profile/v1/service.proto for package 'profile.v1'

require 'grpc'
require 'profile/v1/service_pb'

module Profile
  module V1
    module ProfileService
      # Unified profile service (replaces portfolio CastService + GuestService).
      # One Profile per account (1:1 with identity.Account). role-specific fields are
      # optional (cast extras). Escort commerce dimension (plans/schedules/genres) dropped.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'profile.v1.ProfileService'

        rpc :GetProfile, ::Profile::V1::GetProfileRequest, ::Profile::V1::GetProfileResponse
        rpc :GetProfileByUsername, ::Profile::V1::GetProfileByUsernameRequest, ::Profile::V1::GetProfileResponse
        rpc :SaveProfile, ::Profile::V1::SaveProfileRequest, ::Profile::V1::SaveProfileResponse
        rpc :CheckUsernameAvailability, ::Profile::V1::CheckUsernameAvailabilityRequest, ::Profile::V1::CheckUsernameAvailabilityResponse
        rpc :SaveProfileMedia, ::Profile::V1::SaveProfileMediaRequest, ::Profile::V1::SaveProfileMediaResponse
        rpc :ListAreas, ::Profile::V1::ListAreasRequest, ::Profile::V1::ListAreasResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
