apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - demo-app/deployment.yaml

patches:
  - target:
      kind: Ingress
      name: nginx-app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nginx.local
