# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: trust/v1/service.proto for package 'trust.v1'

require 'grpc'
require 'trust/v1/service_pb'

module Trust
  module V1
    module TrustService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'trust.v1.TrustService'

        # Tagging operations
        rpc :AddTagging, ::Trust::V1::AddTaggingRequest, ::Trust::V1::AddTaggingResponse
        rpc :RemoveTagging, ::Trust::V1::RemoveTaggingRequest, ::Trust::V1::RemoveTaggingResponse
        rpc :ListTargetTags, ::Trust::V1::ListTargetTagsRequest, ::Trust::V1::ListTargetTagsResponse
        # Suggestions
        rpc :ListMyTagNames, ::Trust::V1::ListMyTagNamesRequest, ::Trust::V1::ListMyTagNamesResponse
        # Review RPCs
        rpc :CreateReview, ::Trust::V1::CreateReviewRequest, ::Trust::V1::CreateReviewResponse
        rpc :UpdateReview, ::Trust::V1::UpdateReviewRequest, ::Trust::V1::UpdateReviewResponse
        rpc :DeleteReview, ::Trust::V1::DeleteReviewRequest, ::Trust::V1::DeleteReviewResponse
        rpc :ListReviews, ::Trust::V1::ListReviewsRequest, ::Trust::V1::ListReviewsResponse
        rpc :GetReviewStats, ::Trust::V1::GetReviewStatsRequest, ::Trust::V1::GetReviewStatsResponse
        rpc :ApproveReview, ::Trust::V1::ApproveReviewRequest, ::Trust::V1::ApproveReviewResponse
        rpc :RejectReview, ::Trust::V1::RejectReviewRequest, ::Trust::V1::RejectReviewResponse
        rpc :ListPendingReviews, ::Trust::V1::ListPendingReviewsRequest, ::Trust::V1::ListPendingReviewsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
