// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file footprints/v1/footprints_service.proto (package footprints.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Profile } from "../../profile/v1/service_pb";
import { file_profile_v1_service } from "../../profile/v1/service_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file footprints/v1/footprints_service.proto.
 */
export const file_footprints_v1_footprints_service: GenFile = /*@__PURE__*/
  fileDesc("CiZmb290cHJpbnRzL3YxL2Zvb3RwcmludHNfc2VydmljZS5wcm90bxINZm9vdHByaW50cy52MSIwChJSZWNvcmRWaXNpdFJlcXVlc3QSGgoSdmlzaXRlZF9hY2NvdW50X2lkGAEgASgJIhUKE1JlY29yZFZpc2l0UmVzcG9uc2UiNgoVTGlzdEZvb3RwcmludHNSZXF1ZXN0Eg0KBWxpbWl0GAEgASgFEg4KBmN1cnNvchgCIAEoCSJtChZMaXN0Rm9vdHByaW50c1Jlc3BvbnNlEiwKCmZvb3RwcmludHMYASADKAsyGC5mb290cHJpbnRzLnYxLkZvb3RwcmludBITCgtuZXh0X2N1cnNvchgCIAEoCRIQCghoYXNfbW9yZRgDIAEoCCJ5CglGb290cHJpbnQSJAoHdmlzaXRvchgBIAEoCzITLnByb2ZpbGUudjEuUHJvZmlsZRIzCg9sYXN0X3Zpc2l0ZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhEKCWlzX3VucmVhZBgDIAEoCCIXChVHZXRVbnJlYWRDb3VudFJlcXVlc3QiJwoWR2V0VW5yZWFkQ291bnRSZXNwb25zZRINCgVjb3VudBgBIAEoBSIRCg9NYXJrUmVhZFJlcXVlc3QiEgoQTWFya1JlYWRSZXNwb25zZTL0AgoRRm9vdHByaW50c1NlcnZpY2USVAoLUmVjb3JkVmlzaXQSIS5mb290cHJpbnRzLnYxLlJlY29yZFZpc2l0UmVxdWVzdBoiLmZvb3RwcmludHMudjEuUmVjb3JkVmlzaXRSZXNwb25zZRJdCg5MaXN0Rm9vdHByaW50cxIkLmZvb3RwcmludHMudjEuTGlzdEZvb3RwcmludHNSZXF1ZXN0GiUuZm9vdHByaW50cy52MS5MaXN0Rm9vdHByaW50c1Jlc3BvbnNlEl0KDkdldFVucmVhZENvdW50EiQuZm9vdHByaW50cy52MS5HZXRVbnJlYWRDb3VudFJlcXVlc3QaJS5mb290cHJpbnRzLnYxLkdldFVucmVhZENvdW50UmVzcG9uc2USSwoITWFya1JlYWQSHi5mb290cHJpbnRzLnYxLk1hcmtSZWFkUmVxdWVzdBofLmZvb3RwcmludHMudjEuTWFya1JlYWRSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_timestamp, file_profile_v1_service]);

/**
 * @generated from message footprints.v1.RecordVisitRequest
 */
export type RecordVisitRequest = Message<"footprints.v1.RecordVisitRequest"> & {
  /**
   * visitor derived from gRPC metadata sub claim
   *
   * @generated from field: string visited_account_id = 1;
   */
  visitedAccountId: string;
};

/**
 * Describes the message footprints.v1.RecordVisitRequest.
 * Use `create(RecordVisitRequestSchema)` to create a new message.
 */
export const RecordVisitRequestSchema: GenMessage<RecordVisitRequest> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 0);

/**
 * @generated from message footprints.v1.RecordVisitResponse
 */
export type RecordVisitResponse = Message<"footprints.v1.RecordVisitResponse"> & {
};

/**
 * Describes the message footprints.v1.RecordVisitResponse.
 * Use `create(RecordVisitResponseSchema)` to create a new message.
 */
export const RecordVisitResponseSchema: GenMessage<RecordVisitResponse> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 1);

/**
 * @generated from message footprints.v1.ListFootprintsRequest
 */
export type ListFootprintsRequest = Message<"footprints.v1.ListFootprintsRequest"> & {
  /**
   * default 20, max 50
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * base64(last_visited_at, id)
   *
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message footprints.v1.ListFootprintsRequest.
 * Use `create(ListFootprintsRequestSchema)` to create a new message.
 */
export const ListFootprintsRequestSchema: GenMessage<ListFootprintsRequest> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 2);

/**
 * @generated from message footprints.v1.ListFootprintsResponse
 */
export type ListFootprintsResponse = Message<"footprints.v1.ListFootprintsResponse"> & {
  /**
   * @generated from field: repeated footprints.v1.Footprint footprints = 1;
   */
  footprints: Footprint[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message footprints.v1.ListFootprintsResponse.
 * Use `create(ListFootprintsResponseSchema)` to create a new message.
 */
export const ListFootprintsResponseSchema: GenMessage<ListFootprintsResponse> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 3);

/**
 * is_unread = last_visited_at > viewer.last_read_visit_at
 *
 * @generated from message footprints.v1.Footprint
 */
export type Footprint = Message<"footprints.v1.Footprint"> & {
  /**
   * @generated from field: profile.v1.Profile visitor = 1;
   */
  visitor?: Profile | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp last_visited_at = 2;
   */
  lastVisitedAt?: Timestamp | undefined;

  /**
   * @generated from field: bool is_unread = 3;
   */
  isUnread: boolean;
};

/**
 * Describes the message footprints.v1.Footprint.
 * Use `create(FootprintSchema)` to create a new message.
 */
export const FootprintSchema: GenMessage<Footprint> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 4);

/**
 * @generated from message footprints.v1.GetUnreadCountRequest
 */
export type GetUnreadCountRequest = Message<"footprints.v1.GetUnreadCountRequest"> & {
};

/**
 * Describes the message footprints.v1.GetUnreadCountRequest.
 * Use `create(GetUnreadCountRequestSchema)` to create a new message.
 */
export const GetUnreadCountRequestSchema: GenMessage<GetUnreadCountRequest> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 5);

/**
 * @generated from message footprints.v1.GetUnreadCountResponse
 */
export type GetUnreadCountResponse = Message<"footprints.v1.GetUnreadCountResponse"> & {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;
};

/**
 * Describes the message footprints.v1.GetUnreadCountResponse.
 * Use `create(GetUnreadCountResponseSchema)` to create a new message.
 */
export const GetUnreadCountResponseSchema: GenMessage<GetUnreadCountResponse> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 6);

/**
 * @generated from message footprints.v1.MarkReadRequest
 */
export type MarkReadRequest = Message<"footprints.v1.MarkReadRequest"> & {
};

/**
 * Describes the message footprints.v1.MarkReadRequest.
 * Use `create(MarkReadRequestSchema)` to create a new message.
 */
export const MarkReadRequestSchema: GenMessage<MarkReadRequest> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 7);

/**
 * @generated from message footprints.v1.MarkReadResponse
 */
export type MarkReadResponse = Message<"footprints.v1.MarkReadResponse"> & {
};

/**
 * Describes the message footprints.v1.MarkReadResponse.
 * Use `create(MarkReadResponseSchema)` to create a new message.
 */
export const MarkReadResponseSchema: GenMessage<MarkReadResponse> = /*@__PURE__*/
  messageDesc(file_footprints_v1_footprints_service, 8);

/**
 * @generated from service footprints.v1.FootprintsService
 */
export const FootprintsService: GenService<{
  /**
   * Record that the authenticated viewer visited `visited_account_id`'s profile.
   * No-op (returns OK) when visitor == visited or either side blocks the other.
   *
   * @generated from rpc footprints.v1.FootprintsService.RecordVisit
   */
  recordVisit: {
    methodKind: "unary";
    input: typeof RecordVisitRequestSchema;
    output: typeof RecordVisitResponseSchema;
  },
  /**
   * Cursor-paginated list of accounts who have visited the authenticated viewer.
   * Excludes visitors who are mutually blocked with the viewer.
   *
   * @generated from rpc footprints.v1.FootprintsService.ListFootprints
   */
  listFootprints: {
    methodKind: "unary";
    input: typeof ListFootprintsRequestSchema;
    output: typeof ListFootprintsResponseSchema;
  },
  /**
   * Number of visits whose last_visited_at > viewer.last_read_visit_at.
   *
   * @generated from rpc footprints.v1.FootprintsService.GetUnreadCount
   */
  getUnreadCount: {
    methodKind: "unary";
    input: typeof GetUnreadCountRequestSchema;
    output: typeof GetUnreadCountResponseSchema;
  },
  /**
   * Set viewer.last_read_visit_at = now(). Used when /footprints page is opened.
   *
   * @generated from rpc footprints.v1.FootprintsService.MarkRead
   */
  markRead: {
    methodKind: "unary";
    input: typeof MarkReadRequestSchema;
    output: typeof MarkReadResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_footprints_v1_footprints_service, 0);

