name: 'Notify Kubernetes Results'
description: 'Update source PR with Kubernetes generation results'

inputs:
  build-status:
    description: 'Build status from manifest generation'
    required: true
  build-failed:
    description: 'Whether build failed'
    required: true
  pr-number:
    description: 'GitOps PR number (if created)'
    required: false
  has-changes:
    description: 'Whether changes were detected'
    required: false
  service-name:
    description: 'Service name'
    required: true
  environment:
    description: 'Environment name'
    required: true
  target-repository:
    description: 'Target GitOps repository'
    required: true
  target-branch:
    description: 'Target branch'
    required: true
  source-path:
    description: 'Source path used for generation'
    required: true
  source-pr-number:
    description: 'Source PR number to comment on'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate comment message
      id: message
      shell: bash
      run: ${{ github.action_path }}/scripts/generate-comment.sh
      env:
        ACTION_PATH: ${{ github.action_path }}
        BUILD_FAILED: ${{ inputs.build-failed }}
        SERVICE_NAME: ${{ inputs.service-name }}
        ENVIRONMENT: ${{ inputs.environment }}
        BUILD_STATUS: ${{ inputs.build-status }}
        TARGET_REPOSITORY: ${{ inputs.target-repository }}
        TARGET_BRANCH: ${{ inputs.target-branch }}
        SOURCE_PATH: ${{ inputs.source-path }}
        HAS_CHANGES: ${{ inputs.has-changes }}
        PR_NUMBER: ${{ inputs.pr-number }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}

    - name: Update source PR comment
      uses: thollander/actions-comment-pull-request@v3
      with:
        message: ${{ steps.message.outputs.comment-body }}
        comment-tag: 'kubernetes-manifest-${{ inputs.environment }}-${{ inputs.service-name }}'
        mode: upsert
        pr-number: ${{ inputs.source-pr-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      continue-on-error: true
