// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file post/v1/post_service.proto (package post.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file post/v1/post_service.proto.
 */
export const file_post_v1_post_service: GenFile = /*@__PURE__*/
  fileDesc("Chpwb3N0L3YxL3Bvc3Rfc2VydmljZS5wcm90bxIHcG9zdC52MSJcCgpQb3N0QXV0aG9yEhIKCnByb2ZpbGVfaWQYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJEhIKCmF2YXRhcl91cmwYBCABKAkiVQoLUG9zdE1lbnRpb24SEgoKcHJvZmlsZV9pZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIQCghwb3NpdGlvbhgDIAEoBRIOCgZsZW5ndGgYBCABKAUiYQoJUG9zdE1lZGlhEgoKAmlkGAEgASgJEhIKCm1lZGlhX3R5cGUYAiABKAkSCwoDdXJsGAMgASgJEhUKDXRodW1ibmFpbF91cmwYBCABKAkSEAoIbWVkaWFfaWQYBSABKAkipAIKBFBvc3QSCgoCaWQYASABKAkSGQoRYXV0aG9yX3Byb2ZpbGVfaWQYAiABKAkSDwoHY29udGVudBgDIAEoCRIhCgVtZWRpYRgEIAMoCzISLnBvc3QudjEuUG9zdE1lZGlhEhIKCmNyZWF0ZWRfYXQYBSABKAkSIwoGYXV0aG9yGAYgASgLMhMucG9zdC52MS5Qb3N0QXV0aG9yEhMKC2xpa2VzX2NvdW50GAcgASgFEhYKDmNvbW1lbnRzX2NvdW50GAggASgFEhIKCnZpc2liaWxpdHkYCSABKAkSEAoIaGFzaHRhZ3MYCiADKAkSDQoFbGlrZWQYCyABKAgSJgoIbWVudGlvbnMYDCADKAsyFC5wb3N0LnYxLlBvc3RNZW50aW9uInAKEExpc3RQb3N0c1JlcXVlc3QSDQoFbGltaXQYASABKAUSDgoGY3Vyc29yGAIgASgJEhkKEWF1dGhvcl9wcm9maWxlX2lkGAMgASgJEg4KBmZpbHRlchgEIAEoCRISCgptZWRpYV9vbmx5GAUgASgIIlgKEUxpc3RQb3N0c1Jlc3BvbnNlEhwKBXBvc3RzGAEgAygLMg0ucG9zdC52MS5Qb3N0EhMKC25leHRfY3Vyc29yGAIgASgJEhAKCGhhc19tb3JlGAMgASgIIncKD1NhdmVQb3N0UmVxdWVzdBIKCgJpZBgBIAEoCRIPCgdjb250ZW50GAIgASgJEiEKBW1lZGlhGAMgAygLMhIucG9zdC52MS5Qb3N0TWVkaWESEgoKdmlzaWJpbGl0eRgEIAEoCRIQCghoYXNodGFncxgFIAMoCSIvChBTYXZlUG9zdFJlc3BvbnNlEhsKBHBvc3QYASABKAsyDS5wb3N0LnYxLlBvc3QiHAoOR2V0UG9zdFJlcXVlc3QSCgoCaWQYASABKAkiLgoPR2V0UG9zdFJlc3BvbnNlEhsKBHBvc3QYASABKAsyDS5wb3N0LnYxLlBvc3QiHwoRRGVsZXRlUG9zdFJlcXVlc3QSCgoCaWQYASABKAkiFAoSRGVsZXRlUG9zdFJlc3BvbnNlMpcCCgtQb3N0U2VydmljZRJCCglMaXN0UG9zdHMSGS5wb3N0LnYxLkxpc3RQb3N0c1JlcXVlc3QaGi5wb3N0LnYxLkxpc3RQb3N0c1Jlc3BvbnNlEjwKB0dldFBvc3QSFy5wb3N0LnYxLkdldFBvc3RSZXF1ZXN0GhgucG9zdC52MS5HZXRQb3N0UmVzcG9uc2USPwoIU2F2ZVBvc3QSGC5wb3N0LnYxLlNhdmVQb3N0UmVxdWVzdBoZLnBvc3QudjEuU2F2ZVBvc3RSZXNwb25zZRJFCgpEZWxldGVQb3N0EhoucG9zdC52MS5EZWxldGVQb3N0UmVxdWVzdBobLnBvc3QudjEuRGVsZXRlUG9zdFJlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message post.v1.PostAuthor
 */
export type PostAuthor = Message<"post.v1.PostAuthor"> & {
  /**
   * @generated from field: string profile_id = 1;
   */
  profileId: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;
};

/**
 * Describes the message post.v1.PostAuthor.
 * Use `create(PostAuthorSchema)` to create a new message.
 */
export const PostAuthorSchema: GenMessage<PostAuthor> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 0);

/**
 * @generated from message post.v1.PostMention
 */
export type PostMention = Message<"post.v1.PostMention"> & {
  /**
   * @generated from field: string profile_id = 1;
   */
  profileId: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: int32 position = 3;
   */
  position: number;

  /**
   * @generated from field: int32 length = 4;
   */
  length: number;
};

/**
 * Describes the message post.v1.PostMention.
 * Use `create(PostMentionSchema)` to create a new message.
 */
export const PostMentionSchema: GenMessage<PostMention> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 1);

/**
 * @generated from message post.v1.PostMedia
 */
export type PostMedia = Message<"post.v1.PostMedia"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string media_type = 2;
   */
  mediaType: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: string thumbnail_url = 4;
   */
  thumbnailUrl: string;

  /**
   * @generated from field: string media_id = 5;
   */
  mediaId: string;
};

/**
 * Describes the message post.v1.PostMedia.
 * Use `create(PostMediaSchema)` to create a new message.
 */
export const PostMediaSchema: GenMessage<PostMedia> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 2);

/**
 * @generated from message post.v1.Post
 */
export type Post = Message<"post.v1.Post"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string author_profile_id = 2;
   */
  authorProfileId: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: repeated post.v1.PostMedia media = 4;
   */
  media: PostMedia[];

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * @generated from field: post.v1.PostAuthor author = 6;
   */
  author?: PostAuthor | undefined;

  /**
   * @generated from field: int32 likes_count = 7;
   */
  likesCount: number;

  /**
   * @generated from field: int32 comments_count = 8;
   */
  commentsCount: number;

  /**
   * @generated from field: string visibility = 9;
   */
  visibility: string;

  /**
   * @generated from field: repeated string hashtags = 10;
   */
  hashtags: string[];

  /**
   * @generated from field: bool liked = 11;
   */
  liked: boolean;

  /**
   * @generated from field: repeated post.v1.PostMention mentions = 12;
   */
  mentions: PostMention[];
};

/**
 * Describes the message post.v1.Post.
 * Use `create(PostSchema)` to create a new message.
 */
export const PostSchema: GenMessage<Post> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 3);

/**
 * @generated from message post.v1.ListPostsRequest
 */
export type ListPostsRequest = Message<"post.v1.ListPostsRequest"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * @generated from field: string author_profile_id = 3;
   */
  authorProfileId: string;

  /**
   * @generated from field: string filter = 4;
   */
  filter: string;

  /**
   * @generated from field: bool media_only = 5;
   */
  mediaOnly: boolean;
};

/**
 * Describes the message post.v1.ListPostsRequest.
 * Use `create(ListPostsRequestSchema)` to create a new message.
 */
export const ListPostsRequestSchema: GenMessage<ListPostsRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 4);

/**
 * @generated from message post.v1.ListPostsResponse
 */
export type ListPostsResponse = Message<"post.v1.ListPostsResponse"> & {
  /**
   * @generated from field: repeated post.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message post.v1.ListPostsResponse.
 * Use `create(ListPostsResponseSchema)` to create a new message.
 */
export const ListPostsResponseSchema: GenMessage<ListPostsResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 5);

/**
 * @generated from message post.v1.SavePostRequest
 */
export type SavePostRequest = Message<"post.v1.SavePostRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * @generated from field: repeated post.v1.PostMedia media = 3;
   */
  media: PostMedia[];

  /**
   * @generated from field: string visibility = 4;
   */
  visibility: string;

  /**
   * @generated from field: repeated string hashtags = 5;
   */
  hashtags: string[];
};

/**
 * Describes the message post.v1.SavePostRequest.
 * Use `create(SavePostRequestSchema)` to create a new message.
 */
export const SavePostRequestSchema: GenMessage<SavePostRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 6);

/**
 * @generated from message post.v1.SavePostResponse
 */
export type SavePostResponse = Message<"post.v1.SavePostResponse"> & {
  /**
   * @generated from field: post.v1.Post post = 1;
   */
  post?: Post | undefined;
};

/**
 * Describes the message post.v1.SavePostResponse.
 * Use `create(SavePostResponseSchema)` to create a new message.
 */
export const SavePostResponseSchema: GenMessage<SavePostResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 7);

/**
 * @generated from message post.v1.GetPostRequest
 */
export type GetPostRequest = Message<"post.v1.GetPostRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message post.v1.GetPostRequest.
 * Use `create(GetPostRequestSchema)` to create a new message.
 */
export const GetPostRequestSchema: GenMessage<GetPostRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 8);

/**
 * @generated from message post.v1.GetPostResponse
 */
export type GetPostResponse = Message<"post.v1.GetPostResponse"> & {
  /**
   * @generated from field: post.v1.Post post = 1;
   */
  post?: Post | undefined;
};

/**
 * Describes the message post.v1.GetPostResponse.
 * Use `create(GetPostResponseSchema)` to create a new message.
 */
export const GetPostResponseSchema: GenMessage<GetPostResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 9);

/**
 * @generated from message post.v1.DeletePostRequest
 */
export type DeletePostRequest = Message<"post.v1.DeletePostRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message post.v1.DeletePostRequest.
 * Use `create(DeletePostRequestSchema)` to create a new message.
 */
export const DeletePostRequestSchema: GenMessage<DeletePostRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 10);

/**
 * @generated from message post.v1.DeletePostResponse
 */
export type DeletePostResponse = Message<"post.v1.DeletePostResponse"> & {
};

/**
 * Describes the message post.v1.DeletePostResponse.
 * Use `create(DeletePostResponseSchema)` to create a new message.
 */
export const DeletePostResponseSchema: GenMessage<DeletePostResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 11);

/**
 * @generated from service post.v1.PostService
 */
export const PostService: GenService<{
  /**
   * @generated from rpc post.v1.PostService.ListPosts
   */
  listPosts: {
    methodKind: "unary";
    input: typeof ListPostsRequestSchema;
    output: typeof ListPostsResponseSchema;
  },
  /**
   * @generated from rpc post.v1.PostService.GetPost
   */
  getPost: {
    methodKind: "unary";
    input: typeof GetPostRequestSchema;
    output: typeof GetPostResponseSchema;
  },
  /**
   * @generated from rpc post.v1.PostService.SavePost
   */
  savePost: {
    methodKind: "unary";
    input: typeof SavePostRequestSchema;
    output: typeof SavePostResponseSchema;
  },
  /**
   * @generated from rpc post.v1.PostService.DeletePost
   */
  deletePost: {
    methodKind: "unary";
    input: typeof DeletePostRequestSchema;
    output: typeof DeletePostResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_post_v1_post_service, 0);

