default:
  iam_role_plan: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
  iam_role_apply: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
  aws_region: ap-northeast-1

develop:
  iam_role_plan: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
  iam_role_apply: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
  aws_region: ap-northeast-1
  working_directory: "**/terragrunt/envs/develop"

staging:
  iam_role_plan: arn:aws:iam::123456789012:role/terragrunt-plan-staging-role
  iam_role_apply: arn:aws:iam::123456789012:role/terragrunt-apply-staging-role
  aws_region: ap-northeast-1
  working_directory: "**/terragrunt/envs/staging"

production:
  iam_role_plan: arn:aws:iam::123456789012:role/terragrunt-plan-production-role
  iam_role_apply: arn:aws:iam::123456789012:role/terragrunt-apply-production-role
  aws_region: ap-northeast-1
  working_directory: "**/terragrunt/envs/production"

claude-code-action:
  iam_role_plan: arn:aws:iam::123456789012:role/GitHubActions-TerragruntCustom-Role
  iam_role_apply: arn:aws:iam::123456789012:role/GitHubActions-TerragruntCustom-Role
  aws_region: ap-northeast-1
