environments:
  develop:
    aws_region: ap-northeast-1
    plan:
      aws_assume_role_arn: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
    apply:
      aws_assume_role_arn: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
  staging:
    aws_region: ap-northeast-1
    plan:
      aws_assume_role_arn: arn:aws:iam::123456789012:role/terragrunt-plan-develop-role
    apply:
      aws_assume_role_arn: arn:aws:iam::123456789012:role/terragrunt-apply-develop-role
  production:
    aws_region: ap-northeast-1
    plan:
      aws_assume_role_arn: arn:aws:iam::123456789012:role/terragrunt-plan-develop-role
    apply:
      aws_assume_role_arn: arn:aws:iam::123456789012:role/terragrunt-apply-develop-role

projects:
  claude-code-action:
    path: "github-actions/claude-code-action/terragrunt"
