syntax = "proto3";

package schedule.v1;

service ScheduleService {
  rpc ListSchedules(ListSchedulesRequest) returns (ListSchedulesResponse);

  rpc SaveSchedule(SaveScheduleRequest) returns (SaveScheduleResponse);

  rpc DeleteSchedule(DeleteScheduleRequest) returns (DeleteScheduleResponse);
}

message Schedule {
  string account_id = 1;
  string work_date = 2;
  string start_time = 3;
  string end_time = 4;
}

message ListSchedulesRequest {
  string account_id = 1;
  string from_date = 2;
  string to_date = 3;
}

message ListSchedulesResponse {
  repeated Schedule schedules = 1;
}

message SaveScheduleRequest {
  string work_date = 1;
  string start_time = 2;
  string end_time = 3;
}

message SaveScheduleResponse {
  Schedule schedule = 1;
}

message DeleteScheduleRequest {
  string work_date = 1;
}

message DeleteScheduleResponse {}
