name: 'Claude Code Action - CI/CD'

on:
  pull_request:
    branches:
      - staging/claude-code-action
      - production/claude-code-action
    paths:
      - 'github-actions/claude-code-action/**'
      - '.github/workflows/claude-code-action-*.yaml'
      - '.github/workflows/reusable-*.yaml'
      - '.github/scripts/load-terragrunt-config.js'
      - 'terragrunt-action-root.yaml'
  push:
    branches:
      - staging/claude-code-action
      - production/claude-code-action
    paths:
      - 'github-actions/claude-code-action/**'
      - '.github/workflows/claude-code-action-*.yaml'
      - '.github/workflows/reusable-*.yaml'
      - '.github/scripts/load-terragrunt-config.js'
      - 'terragrunt-action-root.yaml'

env:
  SERVICE_NAME: claude-code-action
  SERVICE_PATH: claude-code-action

jobs:
  terragrunt-plan:
    name: 'Terragrunt Plan'
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reusable-terragrunt-plan.yaml
    with:
      project_name: claude-code-action
    permissions:
      contents: read
      pull-requests: write
      id-token: write

  terragrunt-apply:
    name: 'Terragrunt Apply'
    if: github.event_name == 'push'
    uses: ./.github/workflows/reusable-terragrunt-apply.yaml
    with:
      project_name: claude-code-action
      auto_approve: true
    permissions:
      contents: read
      id-token: write

  deployment-summary:
    name: 'Deployment Summary'
    runs-on: ubuntu-latest
    needs: [terragrunt-apply]
    if: always() && github.event_name == 'push'
    steps:
    - name: Create deployment summary
      run: |
        echo "## 🚀 GitHub OIDC Auth Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Service**: claude-code-action" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Status**: ${{ needs.test-and-build.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Build**: ${{ needs.docker-build.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Infrastructure**: ${{ needs.terragrunt-apply.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Deployment Time**: $(date)" >> $GITHUB_STEP_SUMMARY
