// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=none"
// @generated from file identity/v1/service.proto (package identity.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file identity/v1/service.proto.
 */
export const file_identity_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChlpZGVudGl0eS92MS9zZXJ2aWNlLnByb3RvEgtpZGVudGl0eS52MSIUChJIZWFsdGhDaGVja1JlcXVlc3QiJQoTSGVhbHRoQ2hlY2tSZXNwb25zZRIOCgZzdGF0dXMYASABKAkiJgoOU2VuZFNtc1JlcXVlc3QSFAoMcGhvbmVfbnVtYmVyGAEgASgJIiIKD1NlbmRTbXNSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIjYKEFZlcmlmeVNtc1JlcXVlc3QSFAoMcGhvbmVfbnVtYmVyGAEgASgJEgwKBGNvZGUYAiABKAkiLwoRVmVyaWZ5U21zUmVzcG9uc2USGgoSdmVyaWZpY2F0aW9uX3Rva2VuGAEgASgJIlUKD1JlZ2lzdGVyUmVxdWVzdBIUCgxwaG9uZV9udW1iZXIYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSGgoSdmVyaWZpY2F0aW9uX3Rva2VuGAMgASgJIlgKEFJlZ2lzdGVyUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEi4KDHVzZXJfcHJvZmlsZRgCIAEoCzIYLmlkZW50aXR5LnYxLlVzZXJQcm9maWxlIjYKDExvZ2luUmVxdWVzdBIUCgxwaG9uZV9udW1iZXIYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiVQoNTG9naW5SZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSLgoMdXNlcl9wcm9maWxlGAIgASgLMhguaWRlbnRpdHkudjEuVXNlclByb2ZpbGUiUAoLVXNlclByb2ZpbGUSCgoCaWQYASABKAkSFAoMcGhvbmVfbnVtYmVyGAIgASgJEh8KBHJvbGUYAyABKA4yES5pZGVudGl0eS52MS5Sb2xlKjsKBFJvbGUSFAoQUk9MRV9VTlNQRUNJRklFRBAAEg4KClJPTEVfR1VFU1QQARINCglST0xFX0NBU1QQAjLCAwoPSWRlbnRpdHlTZXJ2aWNlElAKC0hlYWx0aENoZWNrEh8uaWRlbnRpdHkudjEuSGVhbHRoQ2hlY2tSZXF1ZXN0GiAuaWRlbnRpdHkudjEuSGVhbHRoQ2hlY2tSZXNwb25zZRJECgdTZW5kU21zEhsuaWRlbnRpdHkudjEuU2VuZFNtc1JlcXVlc3QaHC5pZGVudGl0eS52MS5TZW5kU21zUmVzcG9uc2USSgoJVmVyaWZ5U21zEh0uaWRlbnRpdHkudjEuVmVyaWZ5U21zUmVxdWVzdBoeLmlkZW50aXR5LnYxLlZlcmlmeVNtc1Jlc3BvbnNlEkcKCFJlZ2lzdGVyEhwuaWRlbnRpdHkudjEuUmVnaXN0ZXJSZXF1ZXN0Gh0uaWRlbnRpdHkudjEuUmVnaXN0ZXJSZXNwb25zZRI+CgVMb2dpbhIZLmlkZW50aXR5LnYxLkxvZ2luUmVxdWVzdBoaLmlkZW50aXR5LnYxLkxvZ2luUmVzcG9uc2USQgoOR2V0Q3VycmVudFVzZXISFi5nb29nbGUucHJvdG9idWYuRW1wdHkaGC5pZGVudGl0eS52MS5Vc2VyUHJvZmlsZWIGcHJvdG8z", [file_google_protobuf_empty]);

/**
 * @generated from message identity.v1.HealthCheckRequest
 */
export type HealthCheckRequest = Message<"identity.v1.HealthCheckRequest"> & {
};

/**
 * Describes the message identity.v1.HealthCheckRequest.
 * Use `create(HealthCheckRequestSchema)` to create a new message.
 */
export const HealthCheckRequestSchema: GenMessage<HealthCheckRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 0);

/**
 * @generated from message identity.v1.HealthCheckResponse
 */
export type HealthCheckResponse = Message<"identity.v1.HealthCheckResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;
};

/**
 * Describes the message identity.v1.HealthCheckResponse.
 * Use `create(HealthCheckResponseSchema)` to create a new message.
 */
export const HealthCheckResponseSchema: GenMessage<HealthCheckResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 1);

/**
 * @generated from message identity.v1.SendSmsRequest
 */
export type SendSmsRequest = Message<"identity.v1.SendSmsRequest"> & {
  /**
   * @generated from field: string phone_number = 1;
   */
  phoneNumber: string;
};

/**
 * Describes the message identity.v1.SendSmsRequest.
 * Use `create(SendSmsRequestSchema)` to create a new message.
 */
export const SendSmsRequestSchema: GenMessage<SendSmsRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 2);

/**
 * @generated from message identity.v1.SendSmsResponse
 */
export type SendSmsResponse = Message<"identity.v1.SendSmsResponse"> & {
  /**
   * In dev/test, we might return the code here for convenience, but skipping for now.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message identity.v1.SendSmsResponse.
 * Use `create(SendSmsResponseSchema)` to create a new message.
 */
export const SendSmsResponseSchema: GenMessage<SendSmsResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 3);

/**
 * @generated from message identity.v1.VerifySmsRequest
 */
export type VerifySmsRequest = Message<"identity.v1.VerifySmsRequest"> & {
  /**
   * @generated from field: string phone_number = 1;
   */
  phoneNumber: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message identity.v1.VerifySmsRequest.
 * Use `create(VerifySmsRequestSchema)` to create a new message.
 */
export const VerifySmsRequestSchema: GenMessage<VerifySmsRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 4);

/**
 * @generated from message identity.v1.VerifySmsResponse
 */
export type VerifySmsResponse = Message<"identity.v1.VerifySmsResponse"> & {
  /**
   * Token proving phone ownership
   *
   * @generated from field: string verification_token = 1;
   */
  verificationToken: string;
};

/**
 * Describes the message identity.v1.VerifySmsResponse.
 * Use `create(VerifySmsResponseSchema)` to create a new message.
 */
export const VerifySmsResponseSchema: GenMessage<VerifySmsResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 5);

/**
 * @generated from message identity.v1.RegisterRequest
 */
export type RegisterRequest = Message<"identity.v1.RegisterRequest"> & {
  /**
   * @generated from field: string phone_number = 1;
   */
  phoneNumber: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * Must match the one from VerifySms
   *
   * @generated from field: string verification_token = 3;
   */
  verificationToken: string;
};

/**
 * Describes the message identity.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 6);

/**
 * @generated from message identity.v1.RegisterResponse
 */
export type RegisterResponse = Message<"identity.v1.RegisterResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: identity.v1.UserProfile user_profile = 2;
   */
  userProfile?: UserProfile;
};

/**
 * Describes the message identity.v1.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 7);

/**
 * @generated from message identity.v1.LoginRequest
 */
export type LoginRequest = Message<"identity.v1.LoginRequest"> & {
  /**
   * @generated from field: string phone_number = 1;
   */
  phoneNumber: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message identity.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 8);

/**
 * @generated from message identity.v1.LoginResponse
 */
export type LoginResponse = Message<"identity.v1.LoginResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: identity.v1.UserProfile user_profile = 2;
   */
  userProfile?: UserProfile;
};

/**
 * Describes the message identity.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 9);

/**
 * @generated from message identity.v1.UserProfile
 */
export type UserProfile = Message<"identity.v1.UserProfile"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string phone_number = 2;
   */
  phoneNumber: string;

  /**
   * @generated from field: identity.v1.Role role = 3;
   */
  role: Role;
};

/**
 * Describes the message identity.v1.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export const UserProfileSchema: GenMessage<UserProfile> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 10);

/**
 * @generated from enum identity.v1.Role
 */
export enum Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_GUEST = 1;
   */
  GUEST = 1,

  /**
   * @generated from enum value: ROLE_CAST = 2;
   */
  CAST = 2,
}

/**
 * Describes the enum identity.v1.Role.
 */
export const RoleSchema: GenEnum<Role> = /*@__PURE__*/
  enumDesc(file_identity_v1_service, 0);

/**
 * @generated from service identity.v1.IdentityService
 */
export const IdentityService: GenService<{
  /**
   * @generated from rpc identity.v1.IdentityService.HealthCheck
   */
  healthCheck: {
    methodKind: "unary";
    input: typeof HealthCheckRequestSchema;
    output: typeof HealthCheckResponseSchema;
  },
  /**
   * Use Phone Number to send SMS verification code
   *
   * @generated from rpc identity.v1.IdentityService.SendSms
   */
  sendSms: {
    methodKind: "unary";
    input: typeof SendSmsRequestSchema;
    output: typeof SendSmsResponseSchema;
  },
  /**
   * Verify SMS code to get a verification token
   *
   * @generated from rpc identity.v1.IdentityService.VerifySms
   */
  verifySms: {
    methodKind: "unary";
    input: typeof VerifySmsRequestSchema;
    output: typeof VerifySmsResponseSchema;
  },
  /**
   * Register with Phone (verified) and Password
   *
   * @generated from rpc identity.v1.IdentityService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * Login with Phone and Password
   *
   * @generated from rpc identity.v1.IdentityService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Get current user session
   *
   * @generated from rpc identity.v1.IdentityService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof UserProfileSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_identity_v1_service, 0);

