---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monorepo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  # url: http://gitea-gitea-http.gitea.svc.cluster.local:3000/giteaadmin/monorepo.git
  url: https://github.com/panicboat/monorepo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monorepo
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./clusters/local"
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
