name: 'Notify Terragrunt Results'
description: 'Update PR comment with Terragrunt execution results'

inputs:
  action-type:
    description: 'Action type (plan/apply)'
    required: true
  project-name:
    description: 'Project name'
    required: true
  environment:
    description: 'Environment name'
    required: true
  working-directory:
    description: 'Working directory'
    required: true
  status:
    description: 'Execution status'
    required: true
  output:
    description: 'Execution output'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create or update PR comment
      uses: thollander/actions-comment-pull-request@v3
      with:
        message: |
          ## ${{ inputs.action-type == 'plan' && '📋 Terragrunt Plan Results' || '🚀 Terragrunt Apply Completed' }}

          **Project**: ${{ inputs.project-name }}
          **Environment**: `${{ inputs.environment }}`
          **Directory**: `${{ inputs.working-directory }}`
          **Status**: ${{ inputs.status }}
          **Action**: ${{ inputs.action-type }}

          <details>
          <summary>📝 ${{ inputs.action-type == 'plan' && 'Plan' || 'Apply' }} Output</summary>

          ```hcl
          ${{ inputs.output }}
          ```
          </details>

          [View full workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          ---
          *Triggered by workflow automation system*
        comment-tag: 'terragrunt-${{ inputs.action-type }}-${{ inputs.environment }}-${{ inputs.project-name }}'
        mode: upsert
        pr-number: ${{ inputs.pr-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      continue-on-error: true
