// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file offer/v1/service.proto (package offer.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file offer/v1/service.proto.
 */
export const file_offer_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChZvZmZlci92MS9zZXJ2aWNlLnByb3RvEghvZmZlci52MSJhCgRQbGFuEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSDQoFcHJpY2UYAyABKAUSGAoQZHVyYXRpb25fbWludXRlcxgEIAEoBRIWCg5pc19yZWNvbW1lbmRlZBgFIAEoCCIiCg9HZXRQbGFuc1JlcXVlc3QSDwoHY2FzdF9pZBgBIAEoCSIxChBHZXRQbGFuc1Jlc3BvbnNlEh0KBXBsYW5zGAEgAygLMg4ub2ZmZXIudjEuUGxhbiIxChBTYXZlUGxhbnNSZXF1ZXN0Eh0KBXBsYW5zGAEgAygLMg4ub2ZmZXIudjEuUGxhbiIyChFTYXZlUGxhbnNSZXNwb25zZRIdCgVwbGFucxgBIAMoCzIOLm9mZmVyLnYxLlBsYW4iPgoIU2NoZWR1bGUSDAoEZGF0ZRgBIAEoCRISCgpzdGFydF90aW1lGAIgASgJEhAKCGVuZF90aW1lGAMgASgJIkwKE0dldFNjaGVkdWxlc1JlcXVlc3QSDwoHY2FzdF9pZBgBIAEoCRISCgpzdGFydF9kYXRlGAIgASgJEhAKCGVuZF9kYXRlGAMgASgJIj0KFEdldFNjaGVkdWxlc1Jlc3BvbnNlEiUKCXNjaGVkdWxlcxgBIAMoCzISLm9mZmVyLnYxLlNjaGVkdWxlIj0KFFNhdmVTY2hlZHVsZXNSZXF1ZXN0EiUKCXNjaGVkdWxlcxgBIAMoCzISLm9mZmVyLnYxLlNjaGVkdWxlIj4KFVNhdmVTY2hlZHVsZXNSZXNwb25zZRIlCglzY2hlZHVsZXMYASADKAsyEi5vZmZlci52MS5TY2hlZHVsZTK4AgoMT2ZmZXJTZXJ2aWNlEkEKCEdldFBsYW5zEhkub2ZmZXIudjEuR2V0UGxhbnNSZXF1ZXN0Ghoub2ZmZXIudjEuR2V0UGxhbnNSZXNwb25zZRJECglTYXZlUGxhbnMSGi5vZmZlci52MS5TYXZlUGxhbnNSZXF1ZXN0Ghsub2ZmZXIudjEuU2F2ZVBsYW5zUmVzcG9uc2USTQoMR2V0U2NoZWR1bGVzEh0ub2ZmZXIudjEuR2V0U2NoZWR1bGVzUmVxdWVzdBoeLm9mZmVyLnYxLkdldFNjaGVkdWxlc1Jlc3BvbnNlElAKDVNhdmVTY2hlZHVsZXMSHi5vZmZlci52MS5TYXZlU2NoZWR1bGVzUmVxdWVzdBofLm9mZmVyLnYxLlNhdmVTY2hlZHVsZXNSZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message offer.v1.Plan
 */
export type Plan = Message<"offer.v1.Plan"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * JPY (0 = Ask)
   *
   * @generated from field: int32 price = 3;
   */
  price: number;

  /**
   * @generated from field: int32 duration_minutes = 4;
   */
  durationMinutes: number;

  /**
   * @generated from field: bool is_recommended = 5;
   */
  isRecommended: boolean;
};

/**
 * Describes the message offer.v1.Plan.
 * Use `create(PlanSchema)` to create a new message.
 */
export const PlanSchema: GenMessage<Plan> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 0);

/**
 * @generated from message offer.v1.GetPlansRequest
 */
export type GetPlansRequest = Message<"offer.v1.GetPlansRequest"> & {
  /**
   * Optional: if empty, use current user's cast
   *
   * @generated from field: string cast_id = 1;
   */
  castId: string;
};

/**
 * Describes the message offer.v1.GetPlansRequest.
 * Use `create(GetPlansRequestSchema)` to create a new message.
 */
export const GetPlansRequestSchema: GenMessage<GetPlansRequest> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 1);

/**
 * @generated from message offer.v1.GetPlansResponse
 */
export type GetPlansResponse = Message<"offer.v1.GetPlansResponse"> & {
  /**
   * @generated from field: repeated offer.v1.Plan plans = 1;
   */
  plans: Plan[];
};

/**
 * Describes the message offer.v1.GetPlansResponse.
 * Use `create(GetPlansResponseSchema)` to create a new message.
 */
export const GetPlansResponseSchema: GenMessage<GetPlansResponse> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 2);

/**
 * @generated from message offer.v1.SavePlansRequest
 */
export type SavePlansRequest = Message<"offer.v1.SavePlansRequest"> & {
  /**
   * @generated from field: repeated offer.v1.Plan plans = 1;
   */
  plans: Plan[];
};

/**
 * Describes the message offer.v1.SavePlansRequest.
 * Use `create(SavePlansRequestSchema)` to create a new message.
 */
export const SavePlansRequestSchema: GenMessage<SavePlansRequest> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 3);

/**
 * @generated from message offer.v1.SavePlansResponse
 */
export type SavePlansResponse = Message<"offer.v1.SavePlansResponse"> & {
  /**
   * @generated from field: repeated offer.v1.Plan plans = 1;
   */
  plans: Plan[];
};

/**
 * Describes the message offer.v1.SavePlansResponse.
 * Use `create(SavePlansResponseSchema)` to create a new message.
 */
export const SavePlansResponseSchema: GenMessage<SavePlansResponse> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 4);

/**
 * @generated from message offer.v1.Schedule
 */
export type Schedule = Message<"offer.v1.Schedule"> & {
  /**
   * YYYY-MM-DD
   *
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * HH:mm
   *
   * @generated from field: string start_time = 2;
   */
  startTime: string;

  /**
   * HH:mm
   *
   * @generated from field: string end_time = 3;
   */
  endTime: string;
};

/**
 * Describes the message offer.v1.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export const ScheduleSchema: GenMessage<Schedule> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 5);

/**
 * @generated from message offer.v1.GetSchedulesRequest
 */
export type GetSchedulesRequest = Message<"offer.v1.GetSchedulesRequest"> & {
  /**
   * Optional: if empty, use current user's cast
   *
   * @generated from field: string cast_id = 1;
   */
  castId: string;

  /**
   * Optional: YYYY-MM-DD
   *
   * @generated from field: string start_date = 2;
   */
  startDate: string;

  /**
   * Optional: YYYY-MM-DD
   *
   * @generated from field: string end_date = 3;
   */
  endDate: string;
};

/**
 * Describes the message offer.v1.GetSchedulesRequest.
 * Use `create(GetSchedulesRequestSchema)` to create a new message.
 */
export const GetSchedulesRequestSchema: GenMessage<GetSchedulesRequest> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 6);

/**
 * @generated from message offer.v1.GetSchedulesResponse
 */
export type GetSchedulesResponse = Message<"offer.v1.GetSchedulesResponse"> & {
  /**
   * @generated from field: repeated offer.v1.Schedule schedules = 1;
   */
  schedules: Schedule[];
};

/**
 * Describes the message offer.v1.GetSchedulesResponse.
 * Use `create(GetSchedulesResponseSchema)` to create a new message.
 */
export const GetSchedulesResponseSchema: GenMessage<GetSchedulesResponse> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 7);

/**
 * @generated from message offer.v1.SaveSchedulesRequest
 */
export type SaveSchedulesRequest = Message<"offer.v1.SaveSchedulesRequest"> & {
  /**
   * @generated from field: repeated offer.v1.Schedule schedules = 1;
   */
  schedules: Schedule[];
};

/**
 * Describes the message offer.v1.SaveSchedulesRequest.
 * Use `create(SaveSchedulesRequestSchema)` to create a new message.
 */
export const SaveSchedulesRequestSchema: GenMessage<SaveSchedulesRequest> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 8);

/**
 * @generated from message offer.v1.SaveSchedulesResponse
 */
export type SaveSchedulesResponse = Message<"offer.v1.SaveSchedulesResponse"> & {
  /**
   * @generated from field: repeated offer.v1.Schedule schedules = 1;
   */
  schedules: Schedule[];
};

/**
 * Describes the message offer.v1.SaveSchedulesResponse.
 * Use `create(SaveSchedulesResponseSchema)` to create a new message.
 */
export const SaveSchedulesResponseSchema: GenMessage<SaveSchedulesResponse> = /*@__PURE__*/
  messageDesc(file_offer_v1_service, 9);

/**
 * @generated from service offer.v1.OfferService
 */
export const OfferService: GenService<{
  /**
   * Plan APIs
   *
   * @generated from rpc offer.v1.OfferService.GetPlans
   */
  getPlans: {
    methodKind: "unary";
    input: typeof GetPlansRequestSchema;
    output: typeof GetPlansResponseSchema;
  },
  /**
   * @generated from rpc offer.v1.OfferService.SavePlans
   */
  savePlans: {
    methodKind: "unary";
    input: typeof SavePlansRequestSchema;
    output: typeof SavePlansResponseSchema;
  },
  /**
   * Schedule APIs
   *
   * @generated from rpc offer.v1.OfferService.GetSchedules
   */
  getSchedules: {
    methodKind: "unary";
    input: typeof GetSchedulesRequestSchema;
    output: typeof GetSchedulesResponseSchema;
  },
  /**
   * @generated from rpc offer.v1.OfferService.SaveSchedules
   */
  saveSchedules: {
    methodKind: "unary";
    input: typeof SaveSchedulesRequestSchema;
    output: typeof SaveSchedulesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_offer_v1_service, 0);

