---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "${NAMESPACE}-workflow"
resources:
- "../../../base/workflow"
patches:
- path: configmap/scaffold-cron-workflow.yaml
- path: cronworkflow/scaffold-cron-workflow.yaml
