# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: post/v1/comment_service.proto for package 'post.v1'

require 'grpc'
require 'post/v1/comment_service_pb'

module Post
  module V1
    module CommentService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'post.v1.CommentService'

        rpc :AddComment, ::Post::V1::AddCommentRequest, ::Post::V1::AddCommentResponse
        rpc :DeleteComment, ::Post::V1::DeleteCommentRequest, ::Post::V1::DeleteCommentResponse
        rpc :ListComments, ::Post::V1::ListCommentsRequest, ::Post::V1::ListCommentsResponse
        rpc :ListReplies, ::Post::V1::ListRepliesRequest, ::Post::V1::ListRepliesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
