# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: post/v1/post_service.proto for package 'post.v1'

require 'grpc'
require 'post/v1/post_service_pb'

module Post
  module V1
    module PostService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'post.v1.PostService'

        rpc :ListCastPosts, ::Post::V1::ListCastPostsRequest, ::Post::V1::ListCastPostsResponse
        rpc :GetCastPost, ::Post::V1::GetCastPostRequest, ::Post::V1::GetCastPostResponse
        rpc :SaveCastPost, ::Post::V1::SaveCastPostRequest, ::Post::V1::SaveCastPostResponse
        rpc :DeleteCastPost, ::Post::V1::DeleteCastPostRequest, ::Post::V1::DeleteCastPostResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
