# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portfolio/v1/guest.proto

require 'google/protobuf'

require 'portfolio/v1/service_pb'


descriptor_data = "\n\x18portfolio/v1/guest.proto\x12\x0cportfolio.v1\x1a\x1aportfolio/v1/service.proto\"{\n\x0cGuestProfile\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n\x0b\x61vatar_path\x18\x03 \x01(\tR\navatarPath\x12\x1d\n\navatar_url\x18\x04 \x01(\tR\tavatarUrl\"\x18\n\x16GetGuestProfileRequest\"O\n\x17GetGuestProfileResponse\x12\x34\n\x07profile\x18\x01 \x01(\x0b\x32\x1a.portfolio.v1.GuestProfileR\x07profile\"N\n\x17SaveGuestProfileRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n\x0b\x61vatar_path\x18\x02 \x01(\tR\navatarPath\"P\n\x18SaveGuestProfileResponse\x12\x34\n\x07profile\x18\x01 \x01(\x0b\x32\x1a.portfolio.v1.GuestProfileR\x07profile2\xa8\x02\n\x0cGuestService\x12^\n\x0fGetGuestProfile\x12$.portfolio.v1.GetGuestProfileRequest\x1a%.portfolio.v1.GetGuestProfileResponse\x12\x61\n\x10SaveGuestProfile\x12%.portfolio.v1.SaveGuestProfileRequest\x1a&.portfolio.v1.SaveGuestProfileResponse\x12U\n\x0cGetUploadUrl\x12!.portfolio.v1.GetUploadUrlRequest\x1a\".portfolio.v1.GetUploadUrlResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Portfolio
  module V1
    GuestProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("portfolio.v1.GuestProfile").msgclass
    GetGuestProfileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("portfolio.v1.GetGuestProfileRequest").msgclass
    GetGuestProfileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("portfolio.v1.GetGuestProfileResponse").msgclass
    SaveGuestProfileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("portfolio.v1.SaveGuestProfileRequest").msgclass
    SaveGuestProfileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("portfolio.v1.SaveGuestProfileResponse").msgclass
  end
end
