# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: portfolio/v1/service.proto for package 'portfolio.v1'

require 'grpc'
require 'portfolio/v1/service_pb'

module Portfolio
  module V1
    module CastService
      # import "buf/validate/validate.proto";
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'portfolio.v1.CastService'

        rpc :GetCastProfile, ::Portfolio::V1::GetCastProfileRequest, ::Portfolio::V1::GetCastProfileResponse
        rpc :CreateCastProfile, ::Portfolio::V1::CreateCastProfileRequest, ::Portfolio::V1::CreateCastProfileResponse
        rpc :UpdateCastProfile, ::Portfolio::V1::UpdateCastProfileRequest, ::Portfolio::V1::UpdateCastProfileResponse
        rpc :UpdateCastImages, ::Portfolio::V1::UpdateCastImagesRequest, ::Portfolio::V1::UpdateCastImagesResponse
        rpc :UpdateCastPlans, ::Portfolio::V1::UpdateCastPlansRequest, ::Portfolio::V1::UpdateCastPlansResponse
        rpc :UpdateCastSchedules, ::Portfolio::V1::UpdateCastSchedulesRequest, ::Portfolio::V1::UpdateCastSchedulesResponse
        rpc :ListCasts, ::Portfolio::V1::ListCastsRequest, ::Portfolio::V1::ListCastsResponse
        rpc :GetUploadUrl, ::Portfolio::V1::GetUploadUrlRequest, ::Portfolio::V1::GetUploadUrlResponse
        rpc :UpdateCastStatus, ::Portfolio::V1::UpdateCastStatusRequest, ::Portfolio::V1::UpdateCastStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
