# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: feed/v1/feed_service.proto for package 'feed.v1'

require 'grpc'
require 'feed/v1/feed_service_pb'

module Feed
  module V1
    module FeedService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'feed.v1.FeedService'

        rpc :ListFeed, ::Feed::V1::ListFeedRequest, ::Feed::V1::ListFeedResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
