// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file social/v1/block_service.proto (package social.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Profile } from "../../profile/v1/service_pb";
import { file_profile_v1_service } from "../../profile/v1/service_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file social/v1/block_service.proto.
 */
export const file_social_v1_block_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1zb2NpYWwvdjEvYmxvY2tfc2VydmljZS5wcm90bxIJc29jaWFsLnYxIikKDEJsb2NrUmVxdWVzdBIZChF0YXJnZXRfYWNjb3VudF9pZBgBIAEoCSIPCg1CbG9ja1Jlc3BvbnNlIisKDlVuYmxvY2tSZXF1ZXN0EhkKEXRhcmdldF9hY2NvdW50X2lkGAEgASgJIhEKD1VuYmxvY2tSZXNwb25zZSIzChJMaXN0QmxvY2tlZFJlcXVlc3QSDQoFbGltaXQYASABKAUSDgoGY3Vyc29yGAIgASgJImMKE0xpc3RCbG9ja2VkUmVzcG9uc2USJQoIcHJvZmlsZXMYASADKAsyEy5wcm9maWxlLnYxLlByb2ZpbGUSEwoLbmV4dF9jdXJzb3IYAiABKAkSEAoIaGFzX21vcmUYAyABKAgiMwoVR2V0QmxvY2tTdGF0dXNSZXF1ZXN0EhoKEnRhcmdldF9hY2NvdW50X2lkcxgBIAMoCSKJAQoWR2V0QmxvY2tTdGF0dXNSZXNwb25zZRI/CgdibG9ja2VkGAEgAygLMi4uc29jaWFsLnYxLkdldEJsb2NrU3RhdHVzUmVzcG9uc2UuQmxvY2tlZEVudHJ5Gi4KDEJsb2NrZWRFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAg6AjgBMrECCgxCbG9ja1NlcnZpY2USOgoFQmxvY2sSFy5zb2NpYWwudjEuQmxvY2tSZXF1ZXN0Ghguc29jaWFsLnYxLkJsb2NrUmVzcG9uc2USQAoHVW5ibG9jaxIZLnNvY2lhbC52MS5VbmJsb2NrUmVxdWVzdBoaLnNvY2lhbC52MS5VbmJsb2NrUmVzcG9uc2USTAoLTGlzdEJsb2NrZWQSHS5zb2NpYWwudjEuTGlzdEJsb2NrZWRSZXF1ZXN0Gh4uc29jaWFsLnYxLkxpc3RCbG9ja2VkUmVzcG9uc2USVQoOR2V0QmxvY2tTdGF0dXMSIC5zb2NpYWwudjEuR2V0QmxvY2tTdGF0dXNSZXF1ZXN0GiEuc29jaWFsLnYxLkdldEJsb2NrU3RhdHVzUmVzcG9uc2ViBnByb3RvMw", [file_profile_v1_service]);

/**
 * @generated from message social.v1.BlockRequest
 */
export type BlockRequest = Message<"social.v1.BlockRequest"> & {
  /**
   * @generated from field: string target_account_id = 1;
   */
  targetAccountId: string;
};

/**
 * Describes the message social.v1.BlockRequest.
 * Use `create(BlockRequestSchema)` to create a new message.
 */
export const BlockRequestSchema: GenMessage<BlockRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 0);

/**
 * @generated from message social.v1.BlockResponse
 */
export type BlockResponse = Message<"social.v1.BlockResponse"> & {
};

/**
 * Describes the message social.v1.BlockResponse.
 * Use `create(BlockResponseSchema)` to create a new message.
 */
export const BlockResponseSchema: GenMessage<BlockResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 1);

/**
 * @generated from message social.v1.UnblockRequest
 */
export type UnblockRequest = Message<"social.v1.UnblockRequest"> & {
  /**
   * @generated from field: string target_account_id = 1;
   */
  targetAccountId: string;
};

/**
 * Describes the message social.v1.UnblockRequest.
 * Use `create(UnblockRequestSchema)` to create a new message.
 */
export const UnblockRequestSchema: GenMessage<UnblockRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 2);

/**
 * @generated from message social.v1.UnblockResponse
 */
export type UnblockResponse = Message<"social.v1.UnblockResponse"> & {
};

/**
 * Describes the message social.v1.UnblockResponse.
 * Use `create(UnblockResponseSchema)` to create a new message.
 */
export const UnblockResponseSchema: GenMessage<UnblockResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 3);

/**
 * @generated from message social.v1.ListBlockedRequest
 */
export type ListBlockedRequest = Message<"social.v1.ListBlockedRequest"> & {
  /**
   * default 20, max 50
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message social.v1.ListBlockedRequest.
 * Use `create(ListBlockedRequestSchema)` to create a new message.
 */
export const ListBlockedRequestSchema: GenMessage<ListBlockedRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 4);

/**
 * @generated from message social.v1.ListBlockedResponse
 */
export type ListBlockedResponse = Message<"social.v1.ListBlockedResponse"> & {
  /**
   * @generated from field: repeated profile.v1.Profile profiles = 1;
   */
  profiles: Profile[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message social.v1.ListBlockedResponse.
 * Use `create(ListBlockedResponseSchema)` to create a new message.
 */
export const ListBlockedResponseSchema: GenMessage<ListBlockedResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 5);

/**
 * @generated from message social.v1.GetBlockStatusRequest
 */
export type GetBlockStatusRequest = Message<"social.v1.GetBlockStatusRequest"> & {
  /**
   * @generated from field: repeated string target_account_ids = 1;
   */
  targetAccountIds: string[];
};

/**
 * Describes the message social.v1.GetBlockStatusRequest.
 * Use `create(GetBlockStatusRequestSchema)` to create a new message.
 */
export const GetBlockStatusRequestSchema: GenMessage<GetBlockStatusRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 6);

/**
 * @generated from message social.v1.GetBlockStatusResponse
 */
export type GetBlockStatusResponse = Message<"social.v1.GetBlockStatusResponse"> & {
  /**
   * target_account_id -> bool (viewer blocked them?)
   *
   * @generated from field: map<string, bool> blocked = 1;
   */
  blocked: { [key: string]: boolean };
};

/**
 * Describes the message social.v1.GetBlockStatusResponse.
 * Use `create(GetBlockStatusResponseSchema)` to create a new message.
 */
export const GetBlockStatusResponseSchema: GenMessage<GetBlockStatusResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 7);

/**
 * @generated from service social.v1.BlockService
 */
export const BlockService: GenService<{
  /**
   * @generated from rpc social.v1.BlockService.Block
   */
  block: {
    methodKind: "unary";
    input: typeof BlockRequestSchema;
    output: typeof BlockResponseSchema;
  },
  /**
   * @generated from rpc social.v1.BlockService.Unblock
   */
  unblock: {
    methodKind: "unary";
    input: typeof UnblockRequestSchema;
    output: typeof UnblockResponseSchema;
  },
  /**
   * @generated from rpc social.v1.BlockService.ListBlocked
   */
  listBlocked: {
    methodKind: "unary";
    input: typeof ListBlockedRequestSchema;
    output: typeof ListBlockedResponseSchema;
  },
  /**
   * @generated from rpc social.v1.BlockService.GetBlockStatus
   */
  getBlockStatus: {
    methodKind: "unary";
    input: typeof GetBlockStatusRequestSchema;
    output: typeof GetBlockStatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_social_v1_block_service, 0);

