# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: relationship/v1/favorite_service.proto for package 'relationship.v1'

require 'grpc'
require 'relationship/v1/favorite_service_pb'

module Relationship
  module V1
    module FavoriteService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'relationship.v1.FavoriteService'

        rpc :AddFavorite, ::Relationship::V1::AddFavoriteRequest, ::Relationship::V1::AddFavoriteResponse
        rpc :RemoveFavorite, ::Relationship::V1::RemoveFavoriteRequest, ::Relationship::V1::RemoveFavoriteResponse
        rpc :ListFavorites, ::Relationship::V1::ListFavoritesRequest, ::Relationship::V1::ListFavoritesResponse
        rpc :GetFavoriteStatus, ::Relationship::V1::GetFavoriteStatusRequest, ::Relationship::V1::GetFavoriteStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
