# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cast/v1/service.proto for package 'cast.v1'

require 'grpc'
require 'cast/v1/service_pb'

module Cast
  module V1
    module CastService
      # import "buf/validate/validate.proto";
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'cast.v1.CastService'

        rpc :CreateProfile, ::Cast::V1::CreateProfileRequest, ::Cast::V1::CastProfile
        rpc :GetProfile, ::Cast::V1::GetProfileRequest, ::Cast::V1::GetProfileResponse
        rpc :UpdateProfile, ::Cast::V1::UpdateProfileRequest, ::Cast::V1::UpdateProfileResponse
        rpc :ListCasts, ::Cast::V1::ListCastsRequest, ::Cast::V1::ListCastsResponse
        rpc :UpdateStatus, ::Cast::V1::UpdateStatusRequest, ::Cast::V1::UpdateStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
