name: 'Notify Slack Workflow Status'
description: 'Send workflow status notification to Slack'

inputs:
  workflow-status:
    description: 'Overall workflow status'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  pr-author:
    description: 'Pull request author'
    required: true
  pr-url:
    description: 'Pull request URL'
    required: true
  slack-token:
    description: 'Slack bot token'
    required: true
  slack-channel:
    description: 'Slack channel ID'
    required: false
    default: 'C0907M25935'

runs:
  using: 'composite'
  steps:
    - name: Prepare Slack message
      id: message
      shell: bash
      run: ${{ github.action_path }}/scripts/prepare-slack-message.sh
      env:
        ACTION_PATH: ${{ github.action_path }}
        WORKFLOW_STATUS: ${{ inputs.workflow-status }}
        PR_NUMBER: ${{ inputs.pr-number }}
        PR_AUTHOR: ${{ inputs.pr-author }}
        PR_URL: ${{ inputs.pr-url }}
        SLACK_CHANNEL: ${{ inputs.slack-channel }}

    - name: Send Slack notification
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ inputs.slack-token }}
        payload: ${{ steps.message.outputs.payload }}
      continue-on-error: true
