apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monolith-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: monolith-database
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: panicboat/monolith/database
        property: url
