syntax = "proto3";

package feed.v1;

import "post/v1/post_service.proto";

service FeedService {
  rpc ListFeed(ListFeedRequest) returns (ListFeedResponse);
}

enum FeedFilter {
  FEED_FILTER_UNSPECIFIED = 0;
  FEED_FILTER_ALL = 1;
  FEED_FILTER_FOLLOWING = 2;
  FEED_FILTER_AREA = 3;
}

message ListFeedRequest {
  FeedFilter filter = 1;
  int32 limit = 2;
  string cursor = 3;
  string prefecture = 4;
}

message ListFeedResponse {
  repeated post.v1.Post posts = 1;
  string next_cursor = 2;
  bool has_more = 3;
}
