---
apiVersion: v1
kind: Namespace
metadata:
  name: dystopia
  labels:
    app.kubernetes.io/part-of: dystopia
---
apiVersion: v1
kind: Namespace
metadata:
  name: system-components
  labels:
    app.kubernetes.io/part-of: system-components
---
apiVersion: v1
kind: Namespace
metadata:
  name: tools
  labels:
    app.kubernetes.io/part-of: tools
