// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file trust/v1/service.proto (package trust.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file trust/v1/service.proto.
 */
export const file_trust_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChZ0cnVzdC92MS9zZXJ2aWNlLnByb3RvEgh0cnVzdC52MSJSCgtUYWdnaW5nSXRlbRIKCgJpZBgBIAEoCRIQCgh0YWdfbmFtZRgCIAEoCRIRCgl0YWdnZXJfaWQYAyABKAkSEgoKY3JlYXRlZF9hdBgEIAEoCSI4ChFBZGRUYWdnaW5nUmVxdWVzdBIQCgh0YWdfbmFtZRgBIAEoCRIRCgl0YXJnZXRfaWQYAiABKAkiJQoSQWRkVGFnZ2luZ1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiIgoUUmVtb3ZlVGFnZ2luZ1JlcXVlc3QSCgoCaWQYASABKAkiKAoVUmVtb3ZlVGFnZ2luZ1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiKgoVTGlzdFRhcmdldFRhZ3NSZXF1ZXN0EhEKCXRhcmdldF9pZBgBIAEoCSJBChZMaXN0VGFyZ2V0VGFnc1Jlc3BvbnNlEicKCHRhZ2dpbmdzGAEgAygLMhUudHJ1c3QudjEuVGFnZ2luZ0l0ZW0iFwoVTGlzdE15VGFnTmFtZXNSZXF1ZXN0IisKFkxpc3RNeVRhZ05hbWVzUmVzcG9uc2USEQoJdGFnX25hbWVzGAEgAygJMtMCCgxUcnVzdFNlcnZpY2USRwoKQWRkVGFnZ2luZxIbLnRydXN0LnYxLkFkZFRhZ2dpbmdSZXF1ZXN0GhwudHJ1c3QudjEuQWRkVGFnZ2luZ1Jlc3BvbnNlElAKDVJlbW92ZVRhZ2dpbmcSHi50cnVzdC52MS5SZW1vdmVUYWdnaW5nUmVxdWVzdBofLnRydXN0LnYxLlJlbW92ZVRhZ2dpbmdSZXNwb25zZRJTCg5MaXN0VGFyZ2V0VGFncxIfLnRydXN0LnYxLkxpc3RUYXJnZXRUYWdzUmVxdWVzdBogLnRydXN0LnYxLkxpc3RUYXJnZXRUYWdzUmVzcG9uc2USUwoOTGlzdE15VGFnTmFtZXMSHy50cnVzdC52MS5MaXN0TXlUYWdOYW1lc1JlcXVlc3QaIC50cnVzdC52MS5MaXN0TXlUYWdOYW1lc1Jlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message trust.v1.TaggingItem
 */
export type TaggingItem = Message<"trust.v1.TaggingItem"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tag_name = 2;
   */
  tagName: string;

  /**
   * @generated from field: string tagger_id = 3;
   */
  taggerId: string;

  /**
   * @generated from field: string created_at = 4;
   */
  createdAt: string;
};

/**
 * Describes the message trust.v1.TaggingItem.
 * Use `create(TaggingItemSchema)` to create a new message.
 */
export const TaggingItemSchema: GenMessage<TaggingItem> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 0);

/**
 * @generated from message trust.v1.AddTaggingRequest
 */
export type AddTaggingRequest = Message<"trust.v1.AddTaggingRequest"> & {
  /**
   * @generated from field: string tag_name = 1;
   */
  tagName: string;

  /**
   * @generated from field: string target_id = 2;
   */
  targetId: string;
};

/**
 * Describes the message trust.v1.AddTaggingRequest.
 * Use `create(AddTaggingRequestSchema)` to create a new message.
 */
export const AddTaggingRequestSchema: GenMessage<AddTaggingRequest> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 1);

/**
 * @generated from message trust.v1.AddTaggingResponse
 */
export type AddTaggingResponse = Message<"trust.v1.AddTaggingResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message trust.v1.AddTaggingResponse.
 * Use `create(AddTaggingResponseSchema)` to create a new message.
 */
export const AddTaggingResponseSchema: GenMessage<AddTaggingResponse> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 2);

/**
 * @generated from message trust.v1.RemoveTaggingRequest
 */
export type RemoveTaggingRequest = Message<"trust.v1.RemoveTaggingRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message trust.v1.RemoveTaggingRequest.
 * Use `create(RemoveTaggingRequestSchema)` to create a new message.
 */
export const RemoveTaggingRequestSchema: GenMessage<RemoveTaggingRequest> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 3);

/**
 * @generated from message trust.v1.RemoveTaggingResponse
 */
export type RemoveTaggingResponse = Message<"trust.v1.RemoveTaggingResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message trust.v1.RemoveTaggingResponse.
 * Use `create(RemoveTaggingResponseSchema)` to create a new message.
 */
export const RemoveTaggingResponseSchema: GenMessage<RemoveTaggingResponse> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 4);

/**
 * @generated from message trust.v1.ListTargetTagsRequest
 */
export type ListTargetTagsRequest = Message<"trust.v1.ListTargetTagsRequest"> & {
  /**
   * @generated from field: string target_id = 1;
   */
  targetId: string;
};

/**
 * Describes the message trust.v1.ListTargetTagsRequest.
 * Use `create(ListTargetTagsRequestSchema)` to create a new message.
 */
export const ListTargetTagsRequestSchema: GenMessage<ListTargetTagsRequest> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 5);

/**
 * @generated from message trust.v1.ListTargetTagsResponse
 */
export type ListTargetTagsResponse = Message<"trust.v1.ListTargetTagsResponse"> & {
  /**
   * @generated from field: repeated trust.v1.TaggingItem taggings = 1;
   */
  taggings: TaggingItem[];
};

/**
 * Describes the message trust.v1.ListTargetTagsResponse.
 * Use `create(ListTargetTagsResponseSchema)` to create a new message.
 */
export const ListTargetTagsResponseSchema: GenMessage<ListTargetTagsResponse> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 6);

/**
 * @generated from message trust.v1.ListMyTagNamesRequest
 */
export type ListMyTagNamesRequest = Message<"trust.v1.ListMyTagNamesRequest"> & {
};

/**
 * Describes the message trust.v1.ListMyTagNamesRequest.
 * Use `create(ListMyTagNamesRequestSchema)` to create a new message.
 */
export const ListMyTagNamesRequestSchema: GenMessage<ListMyTagNamesRequest> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 7);

/**
 * @generated from message trust.v1.ListMyTagNamesResponse
 */
export type ListMyTagNamesResponse = Message<"trust.v1.ListMyTagNamesResponse"> & {
  /**
   * @generated from field: repeated string tag_names = 1;
   */
  tagNames: string[];
};

/**
 * Describes the message trust.v1.ListMyTagNamesResponse.
 * Use `create(ListMyTagNamesResponseSchema)` to create a new message.
 */
export const ListMyTagNamesResponseSchema: GenMessage<ListMyTagNamesResponse> = /*@__PURE__*/
  messageDesc(file_trust_v1_service, 8);

/**
 * @generated from service trust.v1.TrustService
 */
export const TrustService: GenService<{
  /**
   * Tagging operations
   *
   * @generated from rpc trust.v1.TrustService.AddTagging
   */
  addTagging: {
    methodKind: "unary";
    input: typeof AddTaggingRequestSchema;
    output: typeof AddTaggingResponseSchema;
  },
  /**
   * @generated from rpc trust.v1.TrustService.RemoveTagging
   */
  removeTagging: {
    methodKind: "unary";
    input: typeof RemoveTaggingRequestSchema;
    output: typeof RemoveTaggingResponseSchema;
  },
  /**
   * @generated from rpc trust.v1.TrustService.ListTargetTags
   */
  listTargetTags: {
    methodKind: "unary";
    input: typeof ListTargetTagsRequestSchema;
    output: typeof ListTargetTagsResponseSchema;
  },
  /**
   * Suggestions
   *
   * @generated from rpc trust.v1.TrustService.ListMyTagNames
   */
  listMyTagNames: {
    methodKind: "unary";
    input: typeof ListMyTagNamesRequestSchema;
    output: typeof ListMyTagNamesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_trust_v1_service, 0);

