// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file portfolio/v1/guest.proto (package portfolio.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { GetUploadUrlRequestSchema, GetUploadUrlResponseSchema } from "./service_pb";
import { file_portfolio_v1_service } from "./service_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file portfolio/v1/guest.proto.
 */
export const file_portfolio_v1_guest: GenFile = /*@__PURE__*/
  fileDesc("Chhwb3J0Zm9saW8vdjEvZ3Vlc3QucHJvdG8SDHBvcnRmb2xpby52MSJ0CgxHdWVzdFByb2ZpbGUSDwoHdXNlcl9pZBgBIAEoCRIMCgRuYW1lGAIgASgJEhMKC2F2YXRhcl9wYXRoGAMgASgJEhIKCmF2YXRhcl91cmwYBCABKAkSDwoHdGFnbGluZRgFIAEoCRILCgNiaW8YBiABKAkiGAoWR2V0R3Vlc3RQcm9maWxlUmVxdWVzdCJGChdHZXRHdWVzdFByb2ZpbGVSZXNwb25zZRIrCgdwcm9maWxlGAEgASgLMhoucG9ydGZvbGlvLnYxLkd1ZXN0UHJvZmlsZSJaChdTYXZlR3Vlc3RQcm9maWxlUmVxdWVzdBIMCgRuYW1lGAEgASgJEhMKC2F2YXRhcl9wYXRoGAIgASgJEg8KB3RhZ2xpbmUYAyABKAkSCwoDYmlvGAQgASgJIkcKGFNhdmVHdWVzdFByb2ZpbGVSZXNwb25zZRIrCgdwcm9maWxlGAEgASgLMhoucG9ydGZvbGlvLnYxLkd1ZXN0UHJvZmlsZSIqChVHZXRHdWVzdHNCeUlkc1JlcXVlc3QSEQoJZ3Vlc3RfaWRzGAEgAygJIqUBChZHZXRHdWVzdHNCeUlkc1Jlc3BvbnNlEkAKBmd1ZXN0cxgBIAMoCzIwLnBvcnRmb2xpby52MS5HZXRHdWVzdHNCeUlkc1Jlc3BvbnNlLkd1ZXN0c0VudHJ5GkkKC0d1ZXN0c0VudHJ5EgsKA2tleRgBIAEoCRIpCgV2YWx1ZRgCIAEoCzIaLnBvcnRmb2xpby52MS5HdWVzdFByb2ZpbGU6AjgBIi0KGUdldEd1ZXN0c0J5VXNlcklkc1JlcXVlc3QSEAoIdXNlcl9pZHMYASADKAkirQEKGkdldEd1ZXN0c0J5VXNlcklkc1Jlc3BvbnNlEkQKBmd1ZXN0cxgBIAMoCzI0LnBvcnRmb2xpby52MS5HZXRHdWVzdHNCeVVzZXJJZHNSZXNwb25zZS5HdWVzdHNFbnRyeRpJCgtHdWVzdHNFbnRyeRILCgNrZXkYASABKAkSKQoFdmFsdWUYAiABKAsyGi5wb3J0Zm9saW8udjEuR3Vlc3RQcm9maWxlOgI4ATLuAwoMR3Vlc3RTZXJ2aWNlEl4KD0dldEd1ZXN0UHJvZmlsZRIkLnBvcnRmb2xpby52MS5HZXRHdWVzdFByb2ZpbGVSZXF1ZXN0GiUucG9ydGZvbGlvLnYxLkdldEd1ZXN0UHJvZmlsZVJlc3BvbnNlEmEKEFNhdmVHdWVzdFByb2ZpbGUSJS5wb3J0Zm9saW8udjEuU2F2ZUd1ZXN0UHJvZmlsZVJlcXVlc3QaJi5wb3J0Zm9saW8udjEuU2F2ZUd1ZXN0UHJvZmlsZVJlc3BvbnNlElUKDEdldFVwbG9hZFVybBIhLnBvcnRmb2xpby52MS5HZXRVcGxvYWRVcmxSZXF1ZXN0GiIucG9ydGZvbGlvLnYxLkdldFVwbG9hZFVybFJlc3BvbnNlElsKDkdldEd1ZXN0c0J5SWRzEiMucG9ydGZvbGlvLnYxLkdldEd1ZXN0c0J5SWRzUmVxdWVzdBokLnBvcnRmb2xpby52MS5HZXRHdWVzdHNCeUlkc1Jlc3BvbnNlEmcKEkdldEd1ZXN0c0J5VXNlcklkcxInLnBvcnRmb2xpby52MS5HZXRHdWVzdHNCeVVzZXJJZHNSZXF1ZXN0GigucG9ydGZvbGlvLnYxLkdldEd1ZXN0c0J5VXNlcklkc1Jlc3BvbnNlYgZwcm90bzM", [file_portfolio_v1_service]);

/**
 * @generated from message portfolio.v1.GuestProfile
 */
export type GuestProfile = Message<"portfolio.v1.GuestProfile"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string avatar_path = 3;
   */
  avatarPath: string;

  /**
   * Read-only, download URL
   *
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;

  /**
   * Short introduction (max 100 chars)
   *
   * @generated from field: string tagline = 5;
   */
  tagline: string;

  /**
   * Self introduction (max 1000 chars)
   *
   * @generated from field: string bio = 6;
   */
  bio: string;
};

/**
 * Describes the message portfolio.v1.GuestProfile.
 * Use `create(GuestProfileSchema)` to create a new message.
 */
export const GuestProfileSchema: GenMessage<GuestProfile> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 0);

/**
 * @generated from message portfolio.v1.GetGuestProfileRequest
 */
export type GetGuestProfileRequest = Message<"portfolio.v1.GetGuestProfileRequest"> & {
};

/**
 * Describes the message portfolio.v1.GetGuestProfileRequest.
 * Use `create(GetGuestProfileRequestSchema)` to create a new message.
 */
export const GetGuestProfileRequestSchema: GenMessage<GetGuestProfileRequest> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 1);

/**
 * @generated from message portfolio.v1.GetGuestProfileResponse
 */
export type GetGuestProfileResponse = Message<"portfolio.v1.GetGuestProfileResponse"> & {
  /**
   * @generated from field: portfolio.v1.GuestProfile profile = 1;
   */
  profile?: GuestProfile;
};

/**
 * Describes the message portfolio.v1.GetGuestProfileResponse.
 * Use `create(GetGuestProfileResponseSchema)` to create a new message.
 */
export const GetGuestProfileResponseSchema: GenMessage<GetGuestProfileResponse> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 2);

/**
 * @generated from message portfolio.v1.SaveGuestProfileRequest
 */
export type SaveGuestProfileRequest = Message<"portfolio.v1.SaveGuestProfileRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string avatar_path = 2;
   */
  avatarPath: string;

  /**
   * Short introduction (max 100 chars)
   *
   * @generated from field: string tagline = 3;
   */
  tagline: string;

  /**
   * Self introduction (max 1000 chars)
   *
   * @generated from field: string bio = 4;
   */
  bio: string;
};

/**
 * Describes the message portfolio.v1.SaveGuestProfileRequest.
 * Use `create(SaveGuestProfileRequestSchema)` to create a new message.
 */
export const SaveGuestProfileRequestSchema: GenMessage<SaveGuestProfileRequest> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 3);

/**
 * @generated from message portfolio.v1.SaveGuestProfileResponse
 */
export type SaveGuestProfileResponse = Message<"portfolio.v1.SaveGuestProfileResponse"> & {
  /**
   * @generated from field: portfolio.v1.GuestProfile profile = 1;
   */
  profile?: GuestProfile;
};

/**
 * Describes the message portfolio.v1.SaveGuestProfileResponse.
 * Use `create(SaveGuestProfileResponseSchema)` to create a new message.
 */
export const SaveGuestProfileResponseSchema: GenMessage<SaveGuestProfileResponse> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 4);

/**
 * @generated from message portfolio.v1.GetGuestsByIdsRequest
 */
export type GetGuestsByIdsRequest = Message<"portfolio.v1.GetGuestsByIdsRequest"> & {
  /**
   * @generated from field: repeated string guest_ids = 1;
   */
  guestIds: string[];
};

/**
 * Describes the message portfolio.v1.GetGuestsByIdsRequest.
 * Use `create(GetGuestsByIdsRequestSchema)` to create a new message.
 */
export const GetGuestsByIdsRequestSchema: GenMessage<GetGuestsByIdsRequest> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 5);

/**
 * @generated from message portfolio.v1.GetGuestsByIdsResponse
 */
export type GetGuestsByIdsResponse = Message<"portfolio.v1.GetGuestsByIdsResponse"> & {
  /**
   * Map of guest_id to GuestProfile
   *
   * @generated from field: map<string, portfolio.v1.GuestProfile> guests = 1;
   */
  guests: { [key: string]: GuestProfile };
};

/**
 * Describes the message portfolio.v1.GetGuestsByIdsResponse.
 * Use `create(GetGuestsByIdsResponseSchema)` to create a new message.
 */
export const GetGuestsByIdsResponseSchema: GenMessage<GetGuestsByIdsResponse> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 6);

/**
 * @generated from message portfolio.v1.GetGuestsByUserIdsRequest
 */
export type GetGuestsByUserIdsRequest = Message<"portfolio.v1.GetGuestsByUserIdsRequest"> & {
  /**
   * @generated from field: repeated string user_ids = 1;
   */
  userIds: string[];
};

/**
 * Describes the message portfolio.v1.GetGuestsByUserIdsRequest.
 * Use `create(GetGuestsByUserIdsRequestSchema)` to create a new message.
 */
export const GetGuestsByUserIdsRequestSchema: GenMessage<GetGuestsByUserIdsRequest> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 7);

/**
 * @generated from message portfolio.v1.GetGuestsByUserIdsResponse
 */
export type GetGuestsByUserIdsResponse = Message<"portfolio.v1.GetGuestsByUserIdsResponse"> & {
  /**
   * Map of user_id to GuestProfile
   *
   * @generated from field: map<string, portfolio.v1.GuestProfile> guests = 1;
   */
  guests: { [key: string]: GuestProfile };
};

/**
 * Describes the message portfolio.v1.GetGuestsByUserIdsResponse.
 * Use `create(GetGuestsByUserIdsResponseSchema)` to create a new message.
 */
export const GetGuestsByUserIdsResponseSchema: GenMessage<GetGuestsByUserIdsResponse> = /*@__PURE__*/
  messageDesc(file_portfolio_v1_guest, 8);

/**
 * @generated from service portfolio.v1.GuestService
 */
export const GuestService: GenService<{
  /**
   * @generated from rpc portfolio.v1.GuestService.GetGuestProfile
   */
  getGuestProfile: {
    methodKind: "unary";
    input: typeof GetGuestProfileRequestSchema;
    output: typeof GetGuestProfileResponseSchema;
  },
  /**
   * @generated from rpc portfolio.v1.GuestService.SaveGuestProfile
   */
  saveGuestProfile: {
    methodKind: "unary";
    input: typeof SaveGuestProfileRequestSchema;
    output: typeof SaveGuestProfileResponseSchema;
  },
  /**
   * @generated from rpc portfolio.v1.GuestService.GetUploadUrl
   */
  getUploadUrl: {
    methodKind: "unary";
    input: typeof GetUploadUrlRequestSchema;
    output: typeof GetUploadUrlResponseSchema;
  },
  /**
   * @generated from rpc portfolio.v1.GuestService.GetGuestsByIds
   */
  getGuestsByIds: {
    methodKind: "unary";
    input: typeof GetGuestsByIdsRequestSchema;
    output: typeof GetGuestsByIdsResponseSchema;
  },
  /**
   * @generated from rpc portfolio.v1.GuestService.GetGuestsByUserIds
   */
  getGuestsByUserIds: {
    methodKind: "unary";
    input: typeof GetGuestsByUserIdsRequestSchema;
    output: typeof GetGuestsByUserIdsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_portfolio_v1_guest, 0);

