# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: identity/v1/service.proto for package 'identity.v1'

require 'grpc'
require 'identity/v1/service_pb'

module Identity
  module V1
    module IdentityService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'identity.v1.IdentityService'

        rpc :HealthCheck, ::Identity::V1::HealthCheckRequest, ::Identity::V1::HealthCheckResponse
        rpc :Register, ::Identity::V1::RegisterRequest, ::Identity::V1::RegisterResponse
        rpc :Login, ::Identity::V1::LoginRequest, ::Identity::V1::LoginResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
