# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: review/v1/service.proto for package 'review.v1'

require 'grpc'
require 'review/v1/service_pb'

module Review
  module V1
    module ReviewService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'review.v1.ReviewService'

        rpc :CreateEntry, ::Review::V1::CreateEntryRequest, ::Review::V1::CreateEntryResponse
        rpc :UpdateEntry, ::Review::V1::UpdateEntryRequest, ::Review::V1::UpdateEntryResponse
        rpc :DeleteEntry, ::Review::V1::DeleteEntryRequest, ::Review::V1::DeleteEntryResponse
        rpc :HideEntry, ::Review::V1::HideEntryRequest, ::Review::V1::HideEntryResponse
        rpc :UnhideEntry, ::Review::V1::UnhideEntryRequest, ::Review::V1::UnhideEntryResponse
        rpc :ListEntriesByTarget, ::Review::V1::ListEntriesByTargetRequest, ::Review::V1::ListEntriesByTargetResponse
        rpc :ListEntriesByAuthor, ::Review::V1::ListEntriesByAuthorRequest, ::Review::V1::ListEntriesByAuthorResponse
        rpc :GetMySettings, ::Review::V1::GetMySettingsRequest, ::Review::V1::GetMySettingsResponse
        rpc :UpdateMySettings, ::Review::V1::UpdateMySettingsRequest, ::Review::V1::UpdateMySettingsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
