apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
spec:
  template:
    spec:
      containers:
        - name: monolith
          image: ghcr.io/panicboat/monorepo/monolith:v0.7.1 # {"$imagepolicy": "flux-system:monolith"}
