# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feed/v1/feed_service.proto

require 'google/protobuf'


descriptor_data = "\n\x1a\x66\x65\x65\x64/v1/feed_service.proto\x12\x07\x66\x65\x65\x64.v1\"9\n\nFeedAuthor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\"O\n\tFeedMedia\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nmedia_type\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x15\n\rthumbnail_url\x18\x04 \x01(\t\"\xf6\x01\n\x08\x46\x65\x65\x64Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61st_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12!\n\x05media\x18\x04 \x03(\x0b\x32\x12.feed.v1.FeedMedia\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12#\n\x06\x61uthor\x18\x06 \x01(\x0b\x32\x13.feed.v1.FeedAuthor\x12\x13\n\x0blikes_count\x18\x07 \x01(\x05\x12\x16\n\x0e\x63omments_count\x18\x08 \x01(\x05\x12\x12\n\nvisibility\x18\t \x01(\t\x12\x10\n\x08hashtags\x18\n \x03(\t\x12\r\n\x05liked\x18\x0b \x01(\x08\"Z\n\x14ListGuestFeedRequest\x12#\n\x06\x66ilter\x18\x01 \x01(\x0e\x32\x13.feed.v1.FeedFilter\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06\x63ursor\x18\x03 \x01(\t\"`\n\x15ListGuestFeedResponse\x12 \n\x05posts\x18\x01 \x03(\x0b\x32\x11.feed.v1.FeedPost\x12\x13\n\x0bnext_cursor\x18\x02 \x01(\t\x12\x10\n\x08has_more\x18\x03 \x01(\x08\"4\n\x13ListCastFeedRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\"_\n\x14ListCastFeedResponse\x12 \n\x05posts\x18\x01 \x03(\x0b\x32\x11.feed.v1.FeedPost\x12\x13\n\x0bnext_cursor\x18\x02 \x01(\t\x12\x10\n\x08has_more\x18\x03 \x01(\x08*t\n\nFeedFilter\x12\x1b\n\x17\x46\x45\x45\x44_FILTER_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x46\x45\x45\x44_FILTER_ALL\x10\x01\x12\x19\n\x15\x46\x45\x45\x44_FILTER_FOLLOWING\x10\x02\x12\x19\n\x15\x46\x45\x45\x44_FILTER_FAVORITES\x10\x03\x32\xaa\x01\n\x0b\x46\x65\x65\x64Service\x12N\n\rListGuestFeed\x12\x1d.feed.v1.ListGuestFeedRequest\x1a\x1e.feed.v1.ListGuestFeedResponse\x12K\n\x0cListCastFeed\x12\x1c.feed.v1.ListCastFeedRequest\x1a\x1d.feed.v1.ListCastFeedResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Feed
  module V1
    FeedAuthor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.FeedAuthor").msgclass
    FeedMedia = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.FeedMedia").msgclass
    FeedPost = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.FeedPost").msgclass
    ListGuestFeedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.ListGuestFeedRequest").msgclass
    ListGuestFeedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.ListGuestFeedResponse").msgclass
    ListCastFeedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.ListCastFeedRequest").msgclass
    ListCastFeedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.ListCastFeedResponse").msgclass
    FeedFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("feed.v1.FeedFilter").enummodule
  end
end
