// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file social/v1/block_service.proto (package social.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file social/v1/block_service.proto.
 */
export const file_social_v1_block_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1zb2NpYWwvdjEvYmxvY2tfc2VydmljZS5wcm90bxIJc29jaWFsLnYxImEKC0Jsb2NrZWRVc2VyEgoKAmlkGAEgASgJEhEKCXVzZXJfdHlwZRgCIAEoCRIMCgRuYW1lGAMgASgJEhEKCWltYWdlX3VybBgEIAEoCRISCgpibG9ja2VkX2F0GAUgASgJIjwKEEJsb2NrVXNlclJlcXVlc3QSEgoKYmxvY2tlZF9pZBgBIAEoCRIUCgxibG9ja2VkX3R5cGUYAiABKAkiJAoRQmxvY2tVc2VyUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCCIoChJVbmJsb2NrVXNlclJlcXVlc3QSEgoKYmxvY2tlZF9pZBgBIAEoCSImChNVbmJsb2NrVXNlclJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiMwoSTGlzdEJsb2NrZWRSZXF1ZXN0Eg0KBWxpbWl0GAEgASgFEg4KBmN1cnNvchgCIAEoCSJjChNMaXN0QmxvY2tlZFJlc3BvbnNlEiUKBXVzZXJzGAEgAygLMhYuc29jaWFsLnYxLkJsb2NrZWRVc2VyEhMKC25leHRfY3Vyc29yGAIgASgJEhAKCGhhc19tb3JlGAMgASgIIikKFUdldEJsb2NrU3RhdHVzUmVxdWVzdBIQCgh1c2VyX2lkcxgBIAMoCSKJAQoWR2V0QmxvY2tTdGF0dXNSZXNwb25zZRI/CgdibG9ja2VkGAEgAygLMi4uc29jaWFsLnYxLkdldEJsb2NrU3RhdHVzUmVzcG9uc2UuQmxvY2tlZEVudHJ5Gi4KDEJsb2NrZWRFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAg6AjgBMskCCgxCbG9ja1NlcnZpY2USRgoJQmxvY2tVc2VyEhsuc29jaWFsLnYxLkJsb2NrVXNlclJlcXVlc3QaHC5zb2NpYWwudjEuQmxvY2tVc2VyUmVzcG9uc2USTAoLVW5ibG9ja1VzZXISHS5zb2NpYWwudjEuVW5ibG9ja1VzZXJSZXF1ZXN0Gh4uc29jaWFsLnYxLlVuYmxvY2tVc2VyUmVzcG9uc2USTAoLTGlzdEJsb2NrZWQSHS5zb2NpYWwudjEuTGlzdEJsb2NrZWRSZXF1ZXN0Gh4uc29jaWFsLnYxLkxpc3RCbG9ja2VkUmVzcG9uc2USVQoOR2V0QmxvY2tTdGF0dXMSIC5zb2NpYWwudjEuR2V0QmxvY2tTdGF0dXNSZXF1ZXN0GiEuc29jaWFsLnYxLkdldEJsb2NrU3RhdHVzUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message social.v1.BlockedUser
 */
export type BlockedUser = Message<"social.v1.BlockedUser"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "guest" or "cast"
   *
   * @generated from field: string user_type = 2;
   */
  userType: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string image_url = 4;
   */
  imageUrl: string;

  /**
   * ISO8601
   *
   * @generated from field: string blocked_at = 5;
   */
  blockedAt: string;
};

/**
 * Describes the message social.v1.BlockedUser.
 * Use `create(BlockedUserSchema)` to create a new message.
 */
export const BlockedUserSchema: GenMessage<BlockedUser> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 0);

/**
 * @generated from message social.v1.BlockUserRequest
 */
export type BlockUserRequest = Message<"social.v1.BlockUserRequest"> & {
  /**
   * @generated from field: string blocked_id = 1;
   */
  blockedId: string;

  /**
   * "guest" or "cast"
   *
   * @generated from field: string blocked_type = 2;
   */
  blockedType: string;
};

/**
 * Describes the message social.v1.BlockUserRequest.
 * Use `create(BlockUserRequestSchema)` to create a new message.
 */
export const BlockUserRequestSchema: GenMessage<BlockUserRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 1);

/**
 * @generated from message social.v1.BlockUserResponse
 */
export type BlockUserResponse = Message<"social.v1.BlockUserResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message social.v1.BlockUserResponse.
 * Use `create(BlockUserResponseSchema)` to create a new message.
 */
export const BlockUserResponseSchema: GenMessage<BlockUserResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 2);

/**
 * @generated from message social.v1.UnblockUserRequest
 */
export type UnblockUserRequest = Message<"social.v1.UnblockUserRequest"> & {
  /**
   * @generated from field: string blocked_id = 1;
   */
  blockedId: string;
};

/**
 * Describes the message social.v1.UnblockUserRequest.
 * Use `create(UnblockUserRequestSchema)` to create a new message.
 */
export const UnblockUserRequestSchema: GenMessage<UnblockUserRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 3);

/**
 * @generated from message social.v1.UnblockUserResponse
 */
export type UnblockUserResponse = Message<"social.v1.UnblockUserResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message social.v1.UnblockUserResponse.
 * Use `create(UnblockUserResponseSchema)` to create a new message.
 */
export const UnblockUserResponseSchema: GenMessage<UnblockUserResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 4);

/**
 * @generated from message social.v1.ListBlockedRequest
 */
export type ListBlockedRequest = Message<"social.v1.ListBlockedRequest"> & {
  /**
   * default: 50, max: 100
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * optional, for pagination
   *
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message social.v1.ListBlockedRequest.
 * Use `create(ListBlockedRequestSchema)` to create a new message.
 */
export const ListBlockedRequestSchema: GenMessage<ListBlockedRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 5);

/**
 * @generated from message social.v1.ListBlockedResponse
 */
export type ListBlockedResponse = Message<"social.v1.ListBlockedResponse"> & {
  /**
   * @generated from field: repeated social.v1.BlockedUser users = 1;
   */
  users: BlockedUser[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message social.v1.ListBlockedResponse.
 * Use `create(ListBlockedResponseSchema)` to create a new message.
 */
export const ListBlockedResponseSchema: GenMessage<ListBlockedResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 6);

/**
 * @generated from message social.v1.GetBlockStatusRequest
 */
export type GetBlockStatusRequest = Message<"social.v1.GetBlockStatusRequest"> & {
  /**
   * @generated from field: repeated string user_ids = 1;
   */
  userIds: string[];
};

/**
 * Describes the message social.v1.GetBlockStatusRequest.
 * Use `create(GetBlockStatusRequestSchema)` to create a new message.
 */
export const GetBlockStatusRequestSchema: GenMessage<GetBlockStatusRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 7);

/**
 * @generated from message social.v1.GetBlockStatusResponse
 */
export type GetBlockStatusResponse = Message<"social.v1.GetBlockStatusResponse"> & {
  /**
   * user_id -> is_blocked
   *
   * @generated from field: map<string, bool> blocked = 1;
   */
  blocked: { [key: string]: boolean };
};

/**
 * Describes the message social.v1.GetBlockStatusResponse.
 * Use `create(GetBlockStatusResponseSchema)` to create a new message.
 */
export const GetBlockStatusResponseSchema: GenMessage<GetBlockStatusResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_block_service, 8);

/**
 * @generated from service social.v1.BlockService
 */
export const BlockService: GenService<{
  /**
   * @generated from rpc social.v1.BlockService.BlockUser
   */
  blockUser: {
    methodKind: "unary";
    input: typeof BlockUserRequestSchema;
    output: typeof BlockUserResponseSchema;
  },
  /**
   * @generated from rpc social.v1.BlockService.UnblockUser
   */
  unblockUser: {
    methodKind: "unary";
    input: typeof UnblockUserRequestSchema;
    output: typeof UnblockUserResponseSchema;
  },
  /**
   * @generated from rpc social.v1.BlockService.ListBlocked
   */
  listBlocked: {
    methodKind: "unary";
    input: typeof ListBlockedRequestSchema;
    output: typeof ListBlockedResponseSchema;
  },
  /**
   * @generated from rpc social.v1.BlockService.GetBlockStatus
   */
  getBlockStatus: {
    methodKind: "unary";
    input: typeof GetBlockStatusRequestSchema;
    output: typeof GetBlockStatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_social_v1_block_service, 0);

