// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file social/v1/favorite_service.proto (package social.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file social/v1/favorite_service.proto.
 */
export const file_social_v1_favorite_service: GenFile = /*@__PURE__*/
  fileDesc("CiBzb2NpYWwvdjEvZmF2b3JpdGVfc2VydmljZS5wcm90bxIJc29jaWFsLnYxIiUKEkFkZEZhdm9yaXRlUmVxdWVzdBIPCgdjYXN0X2lkGAEgASgJIiYKE0FkZEZhdm9yaXRlUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCCIoChVSZW1vdmVGYXZvcml0ZVJlcXVlc3QSDwoHY2FzdF9pZBgBIAEoCSIpChZSZW1vdmVGYXZvcml0ZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiNQoUTGlzdEZhdm9yaXRlc1JlcXVlc3QSDQoFbGltaXQYASABKAUSDgoGY3Vyc29yGAIgASgJIlAKFUxpc3RGYXZvcml0ZXNSZXNwb25zZRIQCghjYXN0X2lkcxgBIAMoCRITCgtuZXh0X2N1cnNvchgCIAEoCRIQCghoYXNfbW9yZRgDIAEoCCIsChhHZXRGYXZvcml0ZVN0YXR1c1JlcXVlc3QSEAoIY2FzdF9pZHMYASADKAkilQEKGUdldEZhdm9yaXRlU3RhdHVzUmVzcG9uc2USRgoJZmF2b3JpdGVkGAEgAygLMjMuc29jaWFsLnYxLkdldEZhdm9yaXRlU3RhdHVzUmVzcG9uc2UuRmF2b3JpdGVkRW50cnkaMAoORmF2b3JpdGVkRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgIOgI4ATLqAgoPRmF2b3JpdGVTZXJ2aWNlEkwKC0FkZEZhdm9yaXRlEh0uc29jaWFsLnYxLkFkZEZhdm9yaXRlUmVxdWVzdBoeLnNvY2lhbC52MS5BZGRGYXZvcml0ZVJlc3BvbnNlElUKDlJlbW92ZUZhdm9yaXRlEiAuc29jaWFsLnYxLlJlbW92ZUZhdm9yaXRlUmVxdWVzdBohLnNvY2lhbC52MS5SZW1vdmVGYXZvcml0ZVJlc3BvbnNlElIKDUxpc3RGYXZvcml0ZXMSHy5zb2NpYWwudjEuTGlzdEZhdm9yaXRlc1JlcXVlc3QaIC5zb2NpYWwudjEuTGlzdEZhdm9yaXRlc1Jlc3BvbnNlEl4KEUdldEZhdm9yaXRlU3RhdHVzEiMuc29jaWFsLnYxLkdldEZhdm9yaXRlU3RhdHVzUmVxdWVzdBokLnNvY2lhbC52MS5HZXRGYXZvcml0ZVN0YXR1c1Jlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message social.v1.AddFavoriteRequest
 */
export type AddFavoriteRequest = Message<"social.v1.AddFavoriteRequest"> & {
  /**
   * @generated from field: string cast_id = 1;
   */
  castId: string;
};

/**
 * Describes the message social.v1.AddFavoriteRequest.
 * Use `create(AddFavoriteRequestSchema)` to create a new message.
 */
export const AddFavoriteRequestSchema: GenMessage<AddFavoriteRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 0);

/**
 * @generated from message social.v1.AddFavoriteResponse
 */
export type AddFavoriteResponse = Message<"social.v1.AddFavoriteResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message social.v1.AddFavoriteResponse.
 * Use `create(AddFavoriteResponseSchema)` to create a new message.
 */
export const AddFavoriteResponseSchema: GenMessage<AddFavoriteResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 1);

/**
 * @generated from message social.v1.RemoveFavoriteRequest
 */
export type RemoveFavoriteRequest = Message<"social.v1.RemoveFavoriteRequest"> & {
  /**
   * @generated from field: string cast_id = 1;
   */
  castId: string;
};

/**
 * Describes the message social.v1.RemoveFavoriteRequest.
 * Use `create(RemoveFavoriteRequestSchema)` to create a new message.
 */
export const RemoveFavoriteRequestSchema: GenMessage<RemoveFavoriteRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 2);

/**
 * @generated from message social.v1.RemoveFavoriteResponse
 */
export type RemoveFavoriteResponse = Message<"social.v1.RemoveFavoriteResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message social.v1.RemoveFavoriteResponse.
 * Use `create(RemoveFavoriteResponseSchema)` to create a new message.
 */
export const RemoveFavoriteResponseSchema: GenMessage<RemoveFavoriteResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 3);

/**
 * @generated from message social.v1.ListFavoritesRequest
 */
export type ListFavoritesRequest = Message<"social.v1.ListFavoritesRequest"> & {
  /**
   * default: 100, max: 200
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * optional, for pagination
   *
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message social.v1.ListFavoritesRequest.
 * Use `create(ListFavoritesRequestSchema)` to create a new message.
 */
export const ListFavoritesRequestSchema: GenMessage<ListFavoritesRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 4);

/**
 * @generated from message social.v1.ListFavoritesResponse
 */
export type ListFavoritesResponse = Message<"social.v1.ListFavoritesResponse"> & {
  /**
   * @generated from field: repeated string cast_ids = 1;
   */
  castIds: string[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message social.v1.ListFavoritesResponse.
 * Use `create(ListFavoritesResponseSchema)` to create a new message.
 */
export const ListFavoritesResponseSchema: GenMessage<ListFavoritesResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 5);

/**
 * @generated from message social.v1.GetFavoriteStatusRequest
 */
export type GetFavoriteStatusRequest = Message<"social.v1.GetFavoriteStatusRequest"> & {
  /**
   * @generated from field: repeated string cast_ids = 1;
   */
  castIds: string[];
};

/**
 * Describes the message social.v1.GetFavoriteStatusRequest.
 * Use `create(GetFavoriteStatusRequestSchema)` to create a new message.
 */
export const GetFavoriteStatusRequestSchema: GenMessage<GetFavoriteStatusRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 6);

/**
 * @generated from message social.v1.GetFavoriteStatusResponse
 */
export type GetFavoriteStatusResponse = Message<"social.v1.GetFavoriteStatusResponse"> & {
  /**
   * cast_id -> is_favorited
   *
   * @generated from field: map<string, bool> favorited = 1;
   */
  favorited: { [key: string]: boolean };
};

/**
 * Describes the message social.v1.GetFavoriteStatusResponse.
 * Use `create(GetFavoriteStatusResponseSchema)` to create a new message.
 */
export const GetFavoriteStatusResponseSchema: GenMessage<GetFavoriteStatusResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_favorite_service, 7);

/**
 * @generated from service social.v1.FavoriteService
 */
export const FavoriteService: GenService<{
  /**
   * @generated from rpc social.v1.FavoriteService.AddFavorite
   */
  addFavorite: {
    methodKind: "unary";
    input: typeof AddFavoriteRequestSchema;
    output: typeof AddFavoriteResponseSchema;
  },
  /**
   * @generated from rpc social.v1.FavoriteService.RemoveFavorite
   */
  removeFavorite: {
    methodKind: "unary";
    input: typeof RemoveFavoriteRequestSchema;
    output: typeof RemoveFavoriteResponseSchema;
  },
  /**
   * @generated from rpc social.v1.FavoriteService.ListFavorites
   */
  listFavorites: {
    methodKind: "unary";
    input: typeof ListFavoritesRequestSchema;
    output: typeof ListFavoritesResponseSchema;
  },
  /**
   * @generated from rpc social.v1.FavoriteService.GetFavoriteStatus
   */
  getFavoriteStatus: {
    methodKind: "unary";
    input: typeof GetFavoriteStatusRequestSchema;
    output: typeof GetFavoriteStatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_social_v1_favorite_service, 0);

