// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file social/v1/service.proto (package social.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file social/v1/service.proto.
 */
export const file_social_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Chdzb2NpYWwvdjEvc2VydmljZS5wcm90bxIJc29jaWFsLnYxIj0KDkNhc3RQb3N0QXV0aG9yEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEQoJaW1hZ2VfdXJsGAMgASgJIlMKDUNhc3RQb3N0TWVkaWESCgoCaWQYASABKAkSEgoKbWVkaWFfdHlwZRgCIAEoCRILCgN1cmwYAyABKAkSFQoNdGh1bWJuYWlsX3VybBgEIAEoCSLwAQoIQ2FzdFBvc3QSCgoCaWQYASABKAkSDwoHY2FzdF9pZBgCIAEoCRIPCgdjb250ZW50GAMgASgJEicKBW1lZGlhGAQgAygLMhguc29jaWFsLnYxLkNhc3RQb3N0TWVkaWESEgoKY3JlYXRlZF9hdBgFIAEoCRIpCgZhdXRob3IYBiABKAsyGS5zb2NpYWwudjEuQ2FzdFBvc3RBdXRob3ISEwoLbGlrZXNfY291bnQYByABKAUSFgoOY29tbWVudHNfY291bnQYCCABKAUSDwoHdmlzaWJsZRgJIAEoCBIQCghoYXNodGFncxgKIAMoCSJGChRMaXN0Q2FzdFBvc3RzUmVxdWVzdBINCgVsaW1pdBgBIAEoBRIOCgZjdXJzb3IYAiABKAkSDwoHY2FzdF9pZBgDIAEoCSJiChVMaXN0Q2FzdFBvc3RzUmVzcG9uc2USIgoFcG9zdHMYASADKAsyEy5zb2NpYWwudjEuQ2FzdFBvc3QSEwoLbmV4dF9jdXJzb3IYAiABKAkSEAoIaGFzX21vcmUYAyABKAgifgoTU2F2ZUNhc3RQb3N0UmVxdWVzdBIKCgJpZBgBIAEoCRIPCgdjb250ZW50GAIgASgJEicKBW1lZGlhGAMgAygLMhguc29jaWFsLnYxLkNhc3RQb3N0TWVkaWESDwoHdmlzaWJsZRgEIAEoCBIQCghoYXNodGFncxgFIAMoCSI5ChRTYXZlQ2FzdFBvc3RSZXNwb25zZRIhCgRwb3N0GAEgASgLMhMuc29jaWFsLnYxLkNhc3RQb3N0IiMKFURlbGV0ZUNhc3RQb3N0UmVxdWVzdBIKCgJpZBgBIAEoCSIYChZEZWxldGVDYXN0UG9zdFJlc3BvbnNlMo0CCg9UaW1lbGluZVNlcnZpY2USUgoNTGlzdENhc3RQb3N0cxIfLnNvY2lhbC52MS5MaXN0Q2FzdFBvc3RzUmVxdWVzdBogLnNvY2lhbC52MS5MaXN0Q2FzdFBvc3RzUmVzcG9uc2USTwoMU2F2ZUNhc3RQb3N0Eh4uc29jaWFsLnYxLlNhdmVDYXN0UG9zdFJlcXVlc3QaHy5zb2NpYWwudjEuU2F2ZUNhc3RQb3N0UmVzcG9uc2USVQoORGVsZXRlQ2FzdFBvc3QSIC5zb2NpYWwudjEuRGVsZXRlQ2FzdFBvc3RSZXF1ZXN0GiEuc29jaWFsLnYxLkRlbGV0ZUNhc3RQb3N0UmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message social.v1.CastPostAuthor
 */
export type CastPostAuthor = Message<"social.v1.CastPostAuthor"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string image_url = 3;
   */
  imageUrl: string;
};

/**
 * Describes the message social.v1.CastPostAuthor.
 * Use `create(CastPostAuthorSchema)` to create a new message.
 */
export const CastPostAuthorSchema: GenMessage<CastPostAuthor> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 0);

/**
 * @generated from message social.v1.CastPostMedia
 */
export type CastPostMedia = Message<"social.v1.CastPostMedia"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "image" or "video"
   *
   * @generated from field: string media_type = 2;
   */
  mediaType: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: string thumbnail_url = 4;
   */
  thumbnailUrl: string;
};

/**
 * Describes the message social.v1.CastPostMedia.
 * Use `create(CastPostMediaSchema)` to create a new message.
 */
export const CastPostMediaSchema: GenMessage<CastPostMedia> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 1);

/**
 * @generated from message social.v1.CastPost
 */
export type CastPost = Message<"social.v1.CastPost"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string cast_id = 2;
   */
  castId: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: repeated social.v1.CastPostMedia media = 4;
   */
  media: CastPostMedia[];

  /**
   * ISO8601
   *
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * @generated from field: social.v1.CastPostAuthor author = 6;
   */
  author?: CastPostAuthor;

  /**
   * @generated from field: int32 likes_count = 7;
   */
  likesCount: number;

  /**
   * @generated from field: int32 comments_count = 8;
   */
  commentsCount: number;

  /**
   * @generated from field: bool visible = 9;
   */
  visible: boolean;

  /**
   * @generated from field: repeated string hashtags = 10;
   */
  hashtags: string[];
};

/**
 * Describes the message social.v1.CastPost.
 * Use `create(CastPostSchema)` to create a new message.
 */
export const CastPostSchema: GenMessage<CastPost> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 2);

/**
 * @generated from message social.v1.ListCastPostsRequest
 */
export type ListCastPostsRequest = Message<"social.v1.ListCastPostsRequest"> & {
  /**
   * default: 20, max: 50
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * optional, base64 encoded
   *
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * optional, filter by cast
   *
   * @generated from field: string cast_id = 3;
   */
  castId: string;
};

/**
 * Describes the message social.v1.ListCastPostsRequest.
 * Use `create(ListCastPostsRequestSchema)` to create a new message.
 */
export const ListCastPostsRequestSchema: GenMessage<ListCastPostsRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 3);

/**
 * @generated from message social.v1.ListCastPostsResponse
 */
export type ListCastPostsResponse = Message<"social.v1.ListCastPostsResponse"> & {
  /**
   * @generated from field: repeated social.v1.CastPost posts = 1;
   */
  posts: CastPost[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message social.v1.ListCastPostsResponse.
 * Use `create(ListCastPostsResponseSchema)` to create a new message.
 */
export const ListCastPostsResponseSchema: GenMessage<ListCastPostsResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 4);

/**
 * @generated from message social.v1.SaveCastPostRequest
 */
export type SaveCastPostRequest = Message<"social.v1.SaveCastPostRequest"> & {
  /**
   * empty for create, set for update
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * @generated from field: repeated social.v1.CastPostMedia media = 3;
   */
  media: CastPostMedia[];

  /**
   * @generated from field: bool visible = 4;
   */
  visible: boolean;

  /**
   * @generated from field: repeated string hashtags = 5;
   */
  hashtags: string[];
};

/**
 * Describes the message social.v1.SaveCastPostRequest.
 * Use `create(SaveCastPostRequestSchema)` to create a new message.
 */
export const SaveCastPostRequestSchema: GenMessage<SaveCastPostRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 5);

/**
 * @generated from message social.v1.SaveCastPostResponse
 */
export type SaveCastPostResponse = Message<"social.v1.SaveCastPostResponse"> & {
  /**
   * @generated from field: social.v1.CastPost post = 1;
   */
  post?: CastPost;
};

/**
 * Describes the message social.v1.SaveCastPostResponse.
 * Use `create(SaveCastPostResponseSchema)` to create a new message.
 */
export const SaveCastPostResponseSchema: GenMessage<SaveCastPostResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 6);

/**
 * @generated from message social.v1.DeleteCastPostRequest
 */
export type DeleteCastPostRequest = Message<"social.v1.DeleteCastPostRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message social.v1.DeleteCastPostRequest.
 * Use `create(DeleteCastPostRequestSchema)` to create a new message.
 */
export const DeleteCastPostRequestSchema: GenMessage<DeleteCastPostRequest> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 7);

/**
 * @generated from message social.v1.DeleteCastPostResponse
 */
export type DeleteCastPostResponse = Message<"social.v1.DeleteCastPostResponse"> & {
};

/**
 * Describes the message social.v1.DeleteCastPostResponse.
 * Use `create(DeleteCastPostResponseSchema)` to create a new message.
 */
export const DeleteCastPostResponseSchema: GenMessage<DeleteCastPostResponse> = /*@__PURE__*/
  messageDesc(file_social_v1_service, 8);

/**
 * @generated from service social.v1.TimelineService
 */
export const TimelineService: GenService<{
  /**
   * @generated from rpc social.v1.TimelineService.ListCastPosts
   */
  listCastPosts: {
    methodKind: "unary";
    input: typeof ListCastPostsRequestSchema;
    output: typeof ListCastPostsResponseSchema;
  },
  /**
   * @generated from rpc social.v1.TimelineService.SaveCastPost
   */
  saveCastPost: {
    methodKind: "unary";
    input: typeof SaveCastPostRequestSchema;
    output: typeof SaveCastPostResponseSchema;
  },
  /**
   * @generated from rpc social.v1.TimelineService.DeleteCastPost
   */
  deleteCastPost: {
    methodKind: "unary";
    input: typeof DeleteCastPostRequestSchema;
    output: typeof DeleteCastPostResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_social_v1_service, 0);

