# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: schedule/v1/schedule_service.proto for package 'schedule.v1'

require 'grpc'
require 'schedule/v1/schedule_service_pb'

module Schedule
  module V1
    module ScheduleService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'schedule.v1.ScheduleService'

        rpc :ListSchedules, ::Schedule::V1::ListSchedulesRequest, ::Schedule::V1::ListSchedulesResponse
        rpc :SaveSchedule, ::Schedule::V1::SaveScheduleRequest, ::Schedule::V1::SaveScheduleResponse
        rpc :DeleteSchedule, ::Schedule::V1::DeleteScheduleRequest, ::Schedule::V1::DeleteScheduleResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
