apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-app/deployment.yaml
  - nginx-app/ingress.yaml
  - nginx-app/service.yaml
configMapGenerator:
  - name: nginx-app-config
    files:
      - nginx-app/index.html
    options:
      labels:
        app: nginx-app
labels:
  - pairs:
      app: nginx-app
images:
  - name: nginx
    newTag: 1.29.0-alpine
