// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file post/v1/post_service.proto (package post.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file post/v1/post_service.proto.
 */
export const file_post_v1_post_service: GenFile = /*@__PURE__*/
  fileDesc("Chpwb3N0L3YxL3Bvc3Rfc2VydmljZS5wcm90bxIHcG9zdC52MSI9Cg5DYXN0UG9zdEF1dGhvchIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhEKCWltYWdlX3VybBgDIAEoCSJlCg1DYXN0UG9zdE1lZGlhEgoKAmlkGAEgASgJEhIKCm1lZGlhX3R5cGUYAiABKAkSCwoDdXJsGAMgASgJEhUKDXRodW1ibmFpbF91cmwYBCABKAkSEAoIbWVkaWFfaWQYBSABKAki/gEKCENhc3RQb3N0EgoKAmlkGAEgASgJEg8KB2Nhc3RfaWQYAiABKAkSDwoHY29udGVudBgDIAEoCRIlCgVtZWRpYRgEIAMoCzIWLnBvc3QudjEuQ2FzdFBvc3RNZWRpYRISCgpjcmVhdGVkX2F0GAUgASgJEicKBmF1dGhvchgGIAEoCzIXLnBvc3QudjEuQ2FzdFBvc3RBdXRob3ISEwoLbGlrZXNfY291bnQYByABKAUSFgoOY29tbWVudHNfY291bnQYCCABKAUSEgoKdmlzaWJpbGl0eRgJIAEoCRIQCghoYXNodGFncxgKIAMoCRINCgVsaWtlZBgLIAEoCCJwChRMaXN0Q2FzdFBvc3RzUmVxdWVzdBINCgVsaW1pdBgBIAEoBRIOCgZjdXJzb3IYAiABKAkSDwoHY2FzdF9pZBgDIAEoCRIOCgZmaWx0ZXIYBCABKAkSGAoQZXhjbHVkZV9jYXN0X2lkcxgFIAMoCSJgChVMaXN0Q2FzdFBvc3RzUmVzcG9uc2USIAoFcG9zdHMYASADKAsyES5wb3N0LnYxLkNhc3RQb3N0EhMKC25leHRfY3Vyc29yGAIgASgJEhAKCGhhc19tb3JlGAMgASgIIn8KE1NhdmVDYXN0UG9zdFJlcXVlc3QSCgoCaWQYASABKAkSDwoHY29udGVudBgCIAEoCRIlCgVtZWRpYRgDIAMoCzIWLnBvc3QudjEuQ2FzdFBvc3RNZWRpYRISCgp2aXNpYmlsaXR5GAQgASgJEhAKCGhhc2h0YWdzGAUgAygJIjcKFFNhdmVDYXN0UG9zdFJlc3BvbnNlEh8KBHBvc3QYASABKAsyES5wb3N0LnYxLkNhc3RQb3N0IiAKEkdldENhc3RQb3N0UmVxdWVzdBIKCgJpZBgBIAEoCSI2ChNHZXRDYXN0UG9zdFJlc3BvbnNlEh8KBHBvc3QYASABKAsyES5wb3N0LnYxLkNhc3RQb3N0IiMKFURlbGV0ZUNhc3RQb3N0UmVxdWVzdBIKCgJpZBgBIAEoCSIYChZEZWxldGVDYXN0UG9zdFJlc3BvbnNlMscCCgtQb3N0U2VydmljZRJOCg1MaXN0Q2FzdFBvc3RzEh0ucG9zdC52MS5MaXN0Q2FzdFBvc3RzUmVxdWVzdBoeLnBvc3QudjEuTGlzdENhc3RQb3N0c1Jlc3BvbnNlEkgKC0dldENhc3RQb3N0EhsucG9zdC52MS5HZXRDYXN0UG9zdFJlcXVlc3QaHC5wb3N0LnYxLkdldENhc3RQb3N0UmVzcG9uc2USSwoMU2F2ZUNhc3RQb3N0EhwucG9zdC52MS5TYXZlQ2FzdFBvc3RSZXF1ZXN0Gh0ucG9zdC52MS5TYXZlQ2FzdFBvc3RSZXNwb25zZRJRCg5EZWxldGVDYXN0UG9zdBIeLnBvc3QudjEuRGVsZXRlQ2FzdFBvc3RSZXF1ZXN0Gh8ucG9zdC52MS5EZWxldGVDYXN0UG9zdFJlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message post.v1.CastPostAuthor
 */
export type CastPostAuthor = Message<"post.v1.CastPostAuthor"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string image_url = 3;
   */
  imageUrl: string;
};

/**
 * Describes the message post.v1.CastPostAuthor.
 * Use `create(CastPostAuthorSchema)` to create a new message.
 */
export const CastPostAuthorSchema: GenMessage<CastPostAuthor> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 0);

/**
 * @generated from message post.v1.CastPostMedia
 */
export type CastPostMedia = Message<"post.v1.CastPostMedia"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "image" or "video"
   *
   * @generated from field: string media_type = 2;
   */
  mediaType: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: string thumbnail_url = 4;
   */
  thumbnailUrl: string;

  /**
   * Reference to media__files.id (required for input)
   *
   * @generated from field: string media_id = 5;
   */
  mediaId: string;
};

/**
 * Describes the message post.v1.CastPostMedia.
 * Use `create(CastPostMediaSchema)` to create a new message.
 */
export const CastPostMediaSchema: GenMessage<CastPostMedia> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 1);

/**
 * @generated from message post.v1.CastPost
 */
export type CastPost = Message<"post.v1.CastPost"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string cast_id = 2;
   */
  castId: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: repeated post.v1.CastPostMedia media = 4;
   */
  media: CastPostMedia[];

  /**
   * ISO8601
   *
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * @generated from field: post.v1.CastPostAuthor author = 6;
   */
  author?: CastPostAuthor;

  /**
   * @generated from field: int32 likes_count = 7;
   */
  likesCount: number;

  /**
   * @generated from field: int32 comments_count = 8;
   */
  commentsCount: number;

  /**
   * "public" or "private"
   *
   * @generated from field: string visibility = 9;
   */
  visibility: string;

  /**
   * @generated from field: repeated string hashtags = 10;
   */
  hashtags: string[];

  /**
   * whether current user liked this post
   *
   * @generated from field: bool liked = 11;
   */
  liked: boolean;
};

/**
 * Describes the message post.v1.CastPost.
 * Use `create(CastPostSchema)` to create a new message.
 */
export const CastPostSchema: GenMessage<CastPost> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 2);

/**
 * @generated from message post.v1.ListCastPostsRequest
 */
export type ListCastPostsRequest = Message<"post.v1.ListCastPostsRequest"> & {
  /**
   * default: 20, max: 50
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * optional, base64 encoded
   *
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * optional, filter by cast
   *
   * @generated from field: string cast_id = 3;
   */
  castId: string;

  /**
   * optional, "following" or "favorites" to filter posts
   *
   * @generated from field: string filter = 4;
   */
  filter: string;

  /**
   * optional, exclude posts from these casts
   *
   * @generated from field: repeated string exclude_cast_ids = 5;
   */
  excludeCastIds: string[];
};

/**
 * Describes the message post.v1.ListCastPostsRequest.
 * Use `create(ListCastPostsRequestSchema)` to create a new message.
 */
export const ListCastPostsRequestSchema: GenMessage<ListCastPostsRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 3);

/**
 * @generated from message post.v1.ListCastPostsResponse
 */
export type ListCastPostsResponse = Message<"post.v1.ListCastPostsResponse"> & {
  /**
   * @generated from field: repeated post.v1.CastPost posts = 1;
   */
  posts: CastPost[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message post.v1.ListCastPostsResponse.
 * Use `create(ListCastPostsResponseSchema)` to create a new message.
 */
export const ListCastPostsResponseSchema: GenMessage<ListCastPostsResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 4);

/**
 * @generated from message post.v1.SaveCastPostRequest
 */
export type SaveCastPostRequest = Message<"post.v1.SaveCastPostRequest"> & {
  /**
   * empty for create, set for update
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * @generated from field: repeated post.v1.CastPostMedia media = 3;
   */
  media: CastPostMedia[];

  /**
   * "public" or "private", defaults to "public"
   *
   * @generated from field: string visibility = 4;
   */
  visibility: string;

  /**
   * @generated from field: repeated string hashtags = 5;
   */
  hashtags: string[];
};

/**
 * Describes the message post.v1.SaveCastPostRequest.
 * Use `create(SaveCastPostRequestSchema)` to create a new message.
 */
export const SaveCastPostRequestSchema: GenMessage<SaveCastPostRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 5);

/**
 * @generated from message post.v1.SaveCastPostResponse
 */
export type SaveCastPostResponse = Message<"post.v1.SaveCastPostResponse"> & {
  /**
   * @generated from field: post.v1.CastPost post = 1;
   */
  post?: CastPost;
};

/**
 * Describes the message post.v1.SaveCastPostResponse.
 * Use `create(SaveCastPostResponseSchema)` to create a new message.
 */
export const SaveCastPostResponseSchema: GenMessage<SaveCastPostResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 6);

/**
 * @generated from message post.v1.GetCastPostRequest
 */
export type GetCastPostRequest = Message<"post.v1.GetCastPostRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message post.v1.GetCastPostRequest.
 * Use `create(GetCastPostRequestSchema)` to create a new message.
 */
export const GetCastPostRequestSchema: GenMessage<GetCastPostRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 7);

/**
 * @generated from message post.v1.GetCastPostResponse
 */
export type GetCastPostResponse = Message<"post.v1.GetCastPostResponse"> & {
  /**
   * @generated from field: post.v1.CastPost post = 1;
   */
  post?: CastPost;
};

/**
 * Describes the message post.v1.GetCastPostResponse.
 * Use `create(GetCastPostResponseSchema)` to create a new message.
 */
export const GetCastPostResponseSchema: GenMessage<GetCastPostResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 8);

/**
 * @generated from message post.v1.DeleteCastPostRequest
 */
export type DeleteCastPostRequest = Message<"post.v1.DeleteCastPostRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message post.v1.DeleteCastPostRequest.
 * Use `create(DeleteCastPostRequestSchema)` to create a new message.
 */
export const DeleteCastPostRequestSchema: GenMessage<DeleteCastPostRequest> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 9);

/**
 * @generated from message post.v1.DeleteCastPostResponse
 */
export type DeleteCastPostResponse = Message<"post.v1.DeleteCastPostResponse"> & {
};

/**
 * Describes the message post.v1.DeleteCastPostResponse.
 * Use `create(DeleteCastPostResponseSchema)` to create a new message.
 */
export const DeleteCastPostResponseSchema: GenMessage<DeleteCastPostResponse> = /*@__PURE__*/
  messageDesc(file_post_v1_post_service, 10);

/**
 * @generated from service post.v1.PostService
 */
export const PostService: GenService<{
  /**
   * @generated from rpc post.v1.PostService.ListCastPosts
   */
  listCastPosts: {
    methodKind: "unary";
    input: typeof ListCastPostsRequestSchema;
    output: typeof ListCastPostsResponseSchema;
  },
  /**
   * @generated from rpc post.v1.PostService.GetCastPost
   */
  getCastPost: {
    methodKind: "unary";
    input: typeof GetCastPostRequestSchema;
    output: typeof GetCastPostResponseSchema;
  },
  /**
   * @generated from rpc post.v1.PostService.SaveCastPost
   */
  saveCastPost: {
    methodKind: "unary";
    input: typeof SaveCastPostRequestSchema;
    output: typeof SaveCastPostResponseSchema;
  },
  /**
   * @generated from rpc post.v1.PostService.DeleteCastPost
   */
  deleteCastPost: {
    methodKind: "unary";
    input: typeof DeleteCastPostRequestSchema;
    output: typeof DeleteCastPostResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_post_v1_post_service, 0);

