// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file media/v1/media_service.proto (package media.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file media/v1/media_service.proto.
 */
export const file_media_v1_media_service: GenFile = /*@__PURE__*/
  fileDesc("ChxtZWRpYS92MS9tZWRpYV9zZXJ2aWNlLnByb3RvEghtZWRpYS52MSKwAQoFTWVkaWESCgoCaWQYASABKAkSJwoKbWVkaWFfdHlwZRgCIAEoDjITLm1lZGlhLnYxLk1lZGlhVHlwZRILCgN1cmwYAyABKAkSFQoNdGh1bWJuYWlsX3VybBgEIAEoCRIQCghmaWxlbmFtZRgFIAEoCRIUCgxjb250ZW50X3R5cGUYBiABKAkSEgoKc2l6ZV9ieXRlcxgHIAEoAxISCgpjcmVhdGVkX2F0GAggASgJImYKE0dldFVwbG9hZFVybFJlcXVlc3QSEAoIZmlsZW5hbWUYASABKAkSFAoMY29udGVudF90eXBlGAIgASgJEicKCm1lZGlhX3R5cGUYAyABKA4yEy5tZWRpYS52MS5NZWRpYVR5cGUiTwoUR2V0VXBsb2FkVXJsUmVzcG9uc2USEgoKdXBsb2FkX3VybBgBIAEoCRIRCgltZWRpYV9rZXkYAiABKAkSEAoIbWVkaWFfaWQYAyABKAkitwEKFFJlZ2lzdGVyTWVkaWFSZXF1ZXN0EhAKCG1lZGlhX2lkGAEgASgJEhEKCW1lZGlhX2tleRgCIAEoCRInCgptZWRpYV90eXBlGAMgASgOMhMubWVkaWEudjEuTWVkaWFUeXBlEhAKCGZpbGVuYW1lGAQgASgJEhQKDGNvbnRlbnRfdHlwZRgFIAEoCRISCgpzaXplX2J5dGVzGAYgASgDEhUKDXRodW1ibmFpbF9rZXkYByABKAkiNwoVUmVnaXN0ZXJNZWRpYVJlc3BvbnNlEh4KBW1lZGlhGAEgASgLMg8ubWVkaWEudjEuTWVkaWEiHQoPR2V0TWVkaWFSZXF1ZXN0EgoKAmlkGAEgASgJIjIKEEdldE1lZGlhUmVzcG9uc2USHgoFbWVkaWEYASABKAsyDy5tZWRpYS52MS5NZWRpYSIjChRHZXRNZWRpYUJhdGNoUmVxdWVzdBILCgNpZHMYASADKAkiNwoVR2V0TWVkaWFCYXRjaFJlc3BvbnNlEh4KBW1lZGlhGAEgAygLMg8ubWVkaWEudjEuTWVkaWEiIAoSRGVsZXRlTWVkaWFSZXF1ZXN0EgoKAmlkGAEgASgJIiYKE0RlbGV0ZU1lZGlhUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCCpTCglNZWRpYVR5cGUSGgoWTUVESUFfVFlQRV9VTlNQRUNJRklFRBAAEhQKEE1FRElBX1RZUEVfSU1BR0UQARIUChBNRURJQV9UWVBFX1ZJREVPEAIykAMKDE1lZGlhU2VydmljZRJNCgxHZXRVcGxvYWRVcmwSHS5tZWRpYS52MS5HZXRVcGxvYWRVcmxSZXF1ZXN0Gh4ubWVkaWEudjEuR2V0VXBsb2FkVXJsUmVzcG9uc2USUAoNUmVnaXN0ZXJNZWRpYRIeLm1lZGlhLnYxLlJlZ2lzdGVyTWVkaWFSZXF1ZXN0Gh8ubWVkaWEudjEuUmVnaXN0ZXJNZWRpYVJlc3BvbnNlEkEKCEdldE1lZGlhEhkubWVkaWEudjEuR2V0TWVkaWFSZXF1ZXN0GhoubWVkaWEudjEuR2V0TWVkaWFSZXNwb25zZRJQCg1HZXRNZWRpYUJhdGNoEh4ubWVkaWEudjEuR2V0TWVkaWFCYXRjaFJlcXVlc3QaHy5tZWRpYS52MS5HZXRNZWRpYUJhdGNoUmVzcG9uc2USSgoLRGVsZXRlTWVkaWESHC5tZWRpYS52MS5EZWxldGVNZWRpYVJlcXVlc3QaHS5tZWRpYS52MS5EZWxldGVNZWRpYVJlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message media.v1.Media
 */
export type Media = Message<"media.v1.Media"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: media.v1.MediaType media_type = 2;
   */
  mediaType: MediaType;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: string thumbnail_url = 4;
   */
  thumbnailUrl: string;

  /**
   * @generated from field: string filename = 5;
   */
  filename: string;

  /**
   * @generated from field: string content_type = 6;
   */
  contentType: string;

  /**
   * @generated from field: int64 size_bytes = 7;
   */
  sizeBytes: bigint;

  /**
   * ISO8601
   *
   * @generated from field: string created_at = 8;
   */
  createdAt: string;
};

/**
 * Describes the message media.v1.Media.
 * Use `create(MediaSchema)` to create a new message.
 */
export const MediaSchema: GenMessage<Media> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 0);

/**
 * @generated from message media.v1.GetUploadUrlRequest
 */
export type GetUploadUrlRequest = Message<"media.v1.GetUploadUrlRequest"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: string content_type = 2;
   */
  contentType: string;

  /**
   * @generated from field: media.v1.MediaType media_type = 3;
   */
  mediaType: MediaType;
};

/**
 * Describes the message media.v1.GetUploadUrlRequest.
 * Use `create(GetUploadUrlRequestSchema)` to create a new message.
 */
export const GetUploadUrlRequestSchema: GenMessage<GetUploadUrlRequest> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 1);

/**
 * @generated from message media.v1.GetUploadUrlResponse
 */
export type GetUploadUrlResponse = Message<"media.v1.GetUploadUrlResponse"> & {
  /**
   * Presigned URL for upload
   *
   * @generated from field: string upload_url = 1;
   */
  uploadUrl: string;

  /**
   * S3 key (path) for the file
   *
   * @generated from field: string media_key = 2;
   */
  mediaKey: string;

  /**
   * Pre-generated ID for the media record
   *
   * @generated from field: string media_id = 3;
   */
  mediaId: string;
};

/**
 * Describes the message media.v1.GetUploadUrlResponse.
 * Use `create(GetUploadUrlResponseSchema)` to create a new message.
 */
export const GetUploadUrlResponseSchema: GenMessage<GetUploadUrlResponse> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 2);

/**
 * @generated from message media.v1.RegisterMediaRequest
 */
export type RegisterMediaRequest = Message<"media.v1.RegisterMediaRequest"> & {
  /**
   * ID from GetUploadUrlResponse
   *
   * @generated from field: string media_id = 1;
   */
  mediaId: string;

  /**
   * Key from GetUploadUrlResponse
   *
   * @generated from field: string media_key = 2;
   */
  mediaKey: string;

  /**
   * @generated from field: media.v1.MediaType media_type = 3;
   */
  mediaType: MediaType;

  /**
   * @generated from field: string filename = 4;
   */
  filename: string;

  /**
   * @generated from field: string content_type = 5;
   */
  contentType: string;

  /**
   * @generated from field: int64 size_bytes = 6;
   */
  sizeBytes: bigint;

  /**
   * Optional: key for thumbnail (for videos)
   *
   * @generated from field: string thumbnail_key = 7;
   */
  thumbnailKey: string;
};

/**
 * Describes the message media.v1.RegisterMediaRequest.
 * Use `create(RegisterMediaRequestSchema)` to create a new message.
 */
export const RegisterMediaRequestSchema: GenMessage<RegisterMediaRequest> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 3);

/**
 * @generated from message media.v1.RegisterMediaResponse
 */
export type RegisterMediaResponse = Message<"media.v1.RegisterMediaResponse"> & {
  /**
   * @generated from field: media.v1.Media media = 1;
   */
  media?: Media;
};

/**
 * Describes the message media.v1.RegisterMediaResponse.
 * Use `create(RegisterMediaResponseSchema)` to create a new message.
 */
export const RegisterMediaResponseSchema: GenMessage<RegisterMediaResponse> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 4);

/**
 * @generated from message media.v1.GetMediaRequest
 */
export type GetMediaRequest = Message<"media.v1.GetMediaRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message media.v1.GetMediaRequest.
 * Use `create(GetMediaRequestSchema)` to create a new message.
 */
export const GetMediaRequestSchema: GenMessage<GetMediaRequest> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 5);

/**
 * @generated from message media.v1.GetMediaResponse
 */
export type GetMediaResponse = Message<"media.v1.GetMediaResponse"> & {
  /**
   * @generated from field: media.v1.Media media = 1;
   */
  media?: Media;
};

/**
 * Describes the message media.v1.GetMediaResponse.
 * Use `create(GetMediaResponseSchema)` to create a new message.
 */
export const GetMediaResponseSchema: GenMessage<GetMediaResponse> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 6);

/**
 * @generated from message media.v1.GetMediaBatchRequest
 */
export type GetMediaBatchRequest = Message<"media.v1.GetMediaBatchRequest"> & {
  /**
   * @generated from field: repeated string ids = 1;
   */
  ids: string[];
};

/**
 * Describes the message media.v1.GetMediaBatchRequest.
 * Use `create(GetMediaBatchRequestSchema)` to create a new message.
 */
export const GetMediaBatchRequestSchema: GenMessage<GetMediaBatchRequest> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 7);

/**
 * @generated from message media.v1.GetMediaBatchResponse
 */
export type GetMediaBatchResponse = Message<"media.v1.GetMediaBatchResponse"> & {
  /**
   * @generated from field: repeated media.v1.Media media = 1;
   */
  media: Media[];
};

/**
 * Describes the message media.v1.GetMediaBatchResponse.
 * Use `create(GetMediaBatchResponseSchema)` to create a new message.
 */
export const GetMediaBatchResponseSchema: GenMessage<GetMediaBatchResponse> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 8);

/**
 * @generated from message media.v1.DeleteMediaRequest
 */
export type DeleteMediaRequest = Message<"media.v1.DeleteMediaRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message media.v1.DeleteMediaRequest.
 * Use `create(DeleteMediaRequestSchema)` to create a new message.
 */
export const DeleteMediaRequestSchema: GenMessage<DeleteMediaRequest> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 9);

/**
 * @generated from message media.v1.DeleteMediaResponse
 */
export type DeleteMediaResponse = Message<"media.v1.DeleteMediaResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message media.v1.DeleteMediaResponse.
 * Use `create(DeleteMediaResponseSchema)` to create a new message.
 */
export const DeleteMediaResponseSchema: GenMessage<DeleteMediaResponse> = /*@__PURE__*/
  messageDesc(file_media_v1_media_service, 10);

/**
 * @generated from enum media.v1.MediaType
 */
export enum MediaType {
  /**
   * @generated from enum value: MEDIA_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MEDIA_TYPE_IMAGE = 1;
   */
  IMAGE = 1,

  /**
   * @generated from enum value: MEDIA_TYPE_VIDEO = 2;
   */
  VIDEO = 2,
}

/**
 * Describes the enum media.v1.MediaType.
 */
export const MediaTypeSchema: GenEnum<MediaType> = /*@__PURE__*/
  enumDesc(file_media_v1_media_service, 0);

/**
 * @generated from service media.v1.MediaService
 */
export const MediaService: GenService<{
  /**
   * Get a presigned URL for uploading a file
   *
   * @generated from rpc media.v1.MediaService.GetUploadUrl
   */
  getUploadUrl: {
    methodKind: "unary";
    input: typeof GetUploadUrlRequestSchema;
    output: typeof GetUploadUrlResponseSchema;
  },
  /**
   * Register uploaded media after successful upload
   *
   * @generated from rpc media.v1.MediaService.RegisterMedia
   */
  registerMedia: {
    methodKind: "unary";
    input: typeof RegisterMediaRequestSchema;
    output: typeof RegisterMediaResponseSchema;
  },
  /**
   * Get media by ID
   *
   * @generated from rpc media.v1.MediaService.GetMedia
   */
  getMedia: {
    methodKind: "unary";
    input: typeof GetMediaRequestSchema;
    output: typeof GetMediaResponseSchema;
  },
  /**
   * Get multiple media by IDs
   *
   * @generated from rpc media.v1.MediaService.GetMediaBatch
   */
  getMediaBatch: {
    methodKind: "unary";
    input: typeof GetMediaBatchRequestSchema;
    output: typeof GetMediaBatchResponseSchema;
  },
  /**
   * Delete media by ID
   *
   * @generated from rpc media.v1.MediaService.DeleteMedia
   */
  deleteMedia: {
    methodKind: "unary";
    input: typeof DeleteMediaRequestSchema;
    output: typeof DeleteMediaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_media_v1_media_service, 0);

