**/.git
**/node_modules
**/.next
**/.env.local
**/*.log

infrastructure/
lambda/aws/
lambda/image/tests/

frontend/kubernetes/
frontend/CHANGELOG.md
frontend/README.md
frontend/README-ja.md

monolith/kubernetes/
monolith/log/
monolith/tmp/
monolith/spec/
monolith/coverage/
monolith/vendor/bundle/
monolith/.bundle/
monolith/public/uploads/
monolith/CHANGELOG.md
monolith/README.md
monolith/README-ja.md
