--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: cast; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "cast";


--
-- Name: identity; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA identity;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cast_plans; Type: TABLE; Schema: cast; Owner: -
--

CREATE TABLE "cast".cast_plans (
    id integer NOT NULL,
    cast_id integer NOT NULL,
    name text NOT NULL,
    price integer NOT NULL,
    duration_minutes integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: cast_plans_id_seq; Type: SEQUENCE; Schema: cast; Owner: -
--

ALTER TABLE "cast".cast_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "cast".cast_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: casts; Type: TABLE; Schema: cast; Owner: -
--

CREATE TABLE "cast".casts (
    id integer NOT NULL,
    user_id integer NOT NULL,
    name text NOT NULL,
    bio text,
    image_url text,
    status text DEFAULT 'offline'::text,
    promise_rate double precision DEFAULT 1.0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: casts_id_seq; Type: SEQUENCE; Schema: cast; Owner: -
--

ALTER TABLE "cast".casts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "cast".casts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: identity; Owner: -
--

CREATE TABLE identity.users (
    id integer NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    role text DEFAULT 'guest'::text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: identity; Owner: -
--

ALTER TABLE identity.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME identity.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: cast_plans cast_plans_pkey; Type: CONSTRAINT; Schema: cast; Owner: -
--

ALTER TABLE ONLY "cast".cast_plans
    ADD CONSTRAINT cast_plans_pkey PRIMARY KEY (id);


--
-- Name: casts casts_pkey; Type: CONSTRAINT; Schema: cast; Owner: -
--

ALTER TABLE ONLY "cast".casts
    ADD CONSTRAINT casts_pkey PRIMARY KEY (id);


--
-- Name: casts casts_user_id_key; Type: CONSTRAINT; Schema: cast; Owner: -
--

ALTER TABLE ONLY "cast".casts
    ADD CONSTRAINT casts_user_id_key UNIQUE (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: identity; Owner: -
--

ALTER TABLE ONLY identity.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: identity; Owner: -
--

ALTER TABLE ONLY identity.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: cast_plans cast_plans_cast_id_fkey; Type: FK CONSTRAINT; Schema: cast; Owner: -
--

ALTER TABLE ONLY "cast".cast_plans
    ADD CONSTRAINT cast_plans_cast_id_fkey FOREIGN KEY (cast_id) REFERENCES "cast".casts(id) ON DELETE CASCADE;


--
-- Name: casts casts_user_id_fkey; Type: FK CONSTRAINT; Schema: cast; Owner: -
--

ALTER TABLE ONLY "cast".casts
    ADD CONSTRAINT casts_user_id_fkey FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


SET search_path TO "$user", public;

INSERT INTO schema_migrations (filename) VALUES
('20260101163904_create_users.rb'),
('20260102155945_create_casts.rb');
