apiVersion: apps/v1
kind: Deployment
metadata:
  name: pennyworth-slack
spec:
  template:
    spec:
      containers:
        - name: pennyworth-slack
          image: ghcr.io/panicboat/monorepo/pennyworth:v0.0.1 # {"$imagepolicy": "flux-system:pennyworth"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pennyworth-alertmanager
spec:
  template:
    spec:
      containers:
        - name: pennyworth-alertmanager
          image: ghcr.io/panicboat/monorepo/pennyworth:v0.0.1 # {"$imagepolicy": "flux-system:pennyworth"}
