apiVersion: apps/v1
kind: Deployment
metadata:
  name: holmes-slack
spec:
  template:
    spec:
      containers:
        - name: holmes-slack
          image: ghcr.io/panicboat/monorepo/holmes:v0.6.0 # {"$imagepolicy": "flux-system:holmes"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holmes-alertmanager
spec:
  template:
    spec:
      containers:
        - name: holmes-alertmanager
          image: ghcr.io/panicboat/monorepo/holmes:v0.6.0 # {"$imagepolicy": "flux-system:holmes"}
