syntax = "proto3";

package identity.v1;

import "google/protobuf/timestamp.proto";

service IdentityService {
  rpc HealthCheck (HealthCheckRequest) returns (HealthCheckResponse);
  rpc CreateAccount (CreateAccountRequest) returns (CreateAccountResponse);
  rpc GetAccount (GetAccountRequest) returns (GetAccountResponse);
  rpc DeactivateAccount (DeactivateAccountRequest) returns (DeactivateAccountResponse);
  rpc ReactivateAccount (ReactivateAccountRequest) returns (ReactivateAccountResponse);
}

message HealthCheckRequest {}

message HealthCheckResponse {
  string status = 1;
}

message CreateAccountRequest {
  string sub = 1;
  Role role = 2;
}

message CreateAccountResponse {
  Account account = 1;
}

message GetAccountRequest {
  string sub = 1;
}

message GetAccountResponse {
  Account account = 1;
}

message DeactivateAccountRequest {}
message DeactivateAccountResponse {}

message ReactivateAccountRequest {
  string sub = 1;
}

message ReactivateAccountResponse {
  Account account = 1;
}

enum Role {
  ROLE_UNSPECIFIED = 0;
  ROLE_GUEST = 1;
  ROLE_CAST = 2;
}

message Account {
  string id = 1;
  Role role = 2;
  google.protobuf.Timestamp deactivated_at = 3;
}
