apiVersion: apps/v1
kind: Deployment
metadata:
  name: holmes-relay
spec:
  template:
    spec:
      containers:
        - name: holmes-relay
          image: ghcr.io/panicboat/monorepo/holmes-relay:v0.1.0 # {"$imagepolicy": "flux-system:holmes-relay"}
