apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: holmes-slack
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: holmes-slack
    creationPolicy: Owner
  data:
    - secretKey: SLACK_SIGNING_SECRET
      remoteRef:
        key: panicboat/holmes/slack
        property: signing_secret
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: panicboat/holmes/slack
        property: bot_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: holmes-alertmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: holmes-alertmanager
    creationPolicy: Owner
  data:
    - secretKey: ALERTMANAGER_SHARED_TOKEN
      remoteRef:
        key: panicboat/holmes/alertmanager
        property: shared_token
