// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file feed/v1/feed_service.proto (package feed.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file feed/v1/feed_service.proto.
 */
export const file_feed_v1_feed_service: GenFile = /*@__PURE__*/
  fileDesc("ChpmZWVkL3YxL2ZlZWRfc2VydmljZS5wcm90bxIHZmVlZC52MSI5CgpGZWVkQXV0aG9yEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEQoJaW1hZ2VfdXJsGAMgASgJIk8KCUZlZWRNZWRpYRIKCgJpZBgBIAEoCRISCgptZWRpYV90eXBlGAIgASgJEgsKA3VybBgDIAEoCRIVCg10aHVtYm5haWxfdXJsGAQgASgJIvYBCghGZWVkUG9zdBIKCgJpZBgBIAEoCRIPCgdjYXN0X2lkGAIgASgJEg8KB2NvbnRlbnQYAyABKAkSIQoFbWVkaWEYBCADKAsyEi5mZWVkLnYxLkZlZWRNZWRpYRISCgpjcmVhdGVkX2F0GAUgASgJEiMKBmF1dGhvchgGIAEoCzITLmZlZWQudjEuRmVlZEF1dGhvchITCgtsaWtlc19jb3VudBgHIAEoBRIWCg5jb21tZW50c19jb3VudBgIIAEoBRISCgp2aXNpYmlsaXR5GAkgASgJEhAKCGhhc2h0YWdzGAogAygJEg0KBWxpa2VkGAsgASgIIloKFExpc3RHdWVzdEZlZWRSZXF1ZXN0EiMKBmZpbHRlchgBIAEoDjITLmZlZWQudjEuRmVlZEZpbHRlchINCgVsaW1pdBgCIAEoBRIOCgZjdXJzb3IYAyABKAkiYAoVTGlzdEd1ZXN0RmVlZFJlc3BvbnNlEiAKBXBvc3RzGAEgAygLMhEuZmVlZC52MS5GZWVkUG9zdBITCgtuZXh0X2N1cnNvchgCIAEoCRIQCghoYXNfbW9yZRgDIAEoCCI0ChNMaXN0Q2FzdEZlZWRSZXF1ZXN0Eg0KBWxpbWl0GAEgASgFEg4KBmN1cnNvchgCIAEoCSJfChRMaXN0Q2FzdEZlZWRSZXNwb25zZRIgCgVwb3N0cxgBIAMoCzIRLmZlZWQudjEuRmVlZFBvc3QSEwoLbmV4dF9jdXJzb3IYAiABKAkSEAoIaGFzX21vcmUYAyABKAgqdAoKRmVlZEZpbHRlchIbChdGRUVEX0ZJTFRFUl9VTlNQRUNJRklFRBAAEhMKD0ZFRURfRklMVEVSX0FMTBABEhkKFUZFRURfRklMVEVSX0ZPTExPV0lORxACEhkKFUZFRURfRklMVEVSX0ZBVk9SSVRFUxADMqoBCgtGZWVkU2VydmljZRJOCg1MaXN0R3Vlc3RGZWVkEh0uZmVlZC52MS5MaXN0R3Vlc3RGZWVkUmVxdWVzdBoeLmZlZWQudjEuTGlzdEd1ZXN0RmVlZFJlc3BvbnNlEksKDExpc3RDYXN0RmVlZBIcLmZlZWQudjEuTGlzdENhc3RGZWVkUmVxdWVzdBodLmZlZWQudjEuTGlzdENhc3RGZWVkUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message feed.v1.FeedAuthor
 */
export type FeedAuthor = Message<"feed.v1.FeedAuthor"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string image_url = 3;
   */
  imageUrl: string;
};

/**
 * Describes the message feed.v1.FeedAuthor.
 * Use `create(FeedAuthorSchema)` to create a new message.
 */
export const FeedAuthorSchema: GenMessage<FeedAuthor> = /*@__PURE__*/
  messageDesc(file_feed_v1_feed_service, 0);

/**
 * @generated from message feed.v1.FeedMedia
 */
export type FeedMedia = Message<"feed.v1.FeedMedia"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "image" or "video"
   *
   * @generated from field: string media_type = 2;
   */
  mediaType: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: string thumbnail_url = 4;
   */
  thumbnailUrl: string;
};

/**
 * Describes the message feed.v1.FeedMedia.
 * Use `create(FeedMediaSchema)` to create a new message.
 */
export const FeedMediaSchema: GenMessage<FeedMedia> = /*@__PURE__*/
  messageDesc(file_feed_v1_feed_service, 1);

/**
 * @generated from message feed.v1.FeedPost
 */
export type FeedPost = Message<"feed.v1.FeedPost"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string cast_id = 2;
   */
  castId: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: repeated feed.v1.FeedMedia media = 4;
   */
  media: FeedMedia[];

  /**
   * ISO8601
   *
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * @generated from field: feed.v1.FeedAuthor author = 6;
   */
  author?: FeedAuthor;

  /**
   * @generated from field: int32 likes_count = 7;
   */
  likesCount: number;

  /**
   * @generated from field: int32 comments_count = 8;
   */
  commentsCount: number;

  /**
   * "public" or "private"
   *
   * @generated from field: string visibility = 9;
   */
  visibility: string;

  /**
   * @generated from field: repeated string hashtags = 10;
   */
  hashtags: string[];

  /**
   * whether current user liked this post
   *
   * @generated from field: bool liked = 11;
   */
  liked: boolean;
};

/**
 * Describes the message feed.v1.FeedPost.
 * Use `create(FeedPostSchema)` to create a new message.
 */
export const FeedPostSchema: GenMessage<FeedPost> = /*@__PURE__*/
  messageDesc(file_feed_v1_feed_service, 2);

/**
 * @generated from message feed.v1.ListGuestFeedRequest
 */
export type ListGuestFeedRequest = Message<"feed.v1.ListGuestFeedRequest"> & {
  /**
   * required: all/following/favorites
   *
   * @generated from field: feed.v1.FeedFilter filter = 1;
   */
  filter: FeedFilter;

  /**
   * default: 20, max: 50
   *
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * optional, for pagination
   *
   * @generated from field: string cursor = 3;
   */
  cursor: string;
};

/**
 * Describes the message feed.v1.ListGuestFeedRequest.
 * Use `create(ListGuestFeedRequestSchema)` to create a new message.
 */
export const ListGuestFeedRequestSchema: GenMessage<ListGuestFeedRequest> = /*@__PURE__*/
  messageDesc(file_feed_v1_feed_service, 3);

/**
 * @generated from message feed.v1.ListGuestFeedResponse
 */
export type ListGuestFeedResponse = Message<"feed.v1.ListGuestFeedResponse"> & {
  /**
   * @generated from field: repeated feed.v1.FeedPost posts = 1;
   */
  posts: FeedPost[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message feed.v1.ListGuestFeedResponse.
 * Use `create(ListGuestFeedResponseSchema)` to create a new message.
 */
export const ListGuestFeedResponseSchema: GenMessage<ListGuestFeedResponse> = /*@__PURE__*/
  messageDesc(file_feed_v1_feed_service, 4);

/**
 * @generated from message feed.v1.ListCastFeedRequest
 */
export type ListCastFeedRequest = Message<"feed.v1.ListCastFeedRequest"> & {
  /**
   * default: 20, max: 50
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * optional, for pagination
   *
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message feed.v1.ListCastFeedRequest.
 * Use `create(ListCastFeedRequestSchema)` to create a new message.
 */
export const ListCastFeedRequestSchema: GenMessage<ListCastFeedRequest> = /*@__PURE__*/
  messageDesc(file_feed_v1_feed_service, 5);

/**
 * @generated from message feed.v1.ListCastFeedResponse
 */
export type ListCastFeedResponse = Message<"feed.v1.ListCastFeedResponse"> & {
  /**
   * @generated from field: repeated feed.v1.FeedPost posts = 1;
   */
  posts: FeedPost[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message feed.v1.ListCastFeedResponse.
 * Use `create(ListCastFeedResponseSchema)` to create a new message.
 */
export const ListCastFeedResponseSchema: GenMessage<ListCastFeedResponse> = /*@__PURE__*/
  messageDesc(file_feed_v1_feed_service, 6);

/**
 * Feed filter options for guest timeline
 *
 * @generated from enum feed.v1.FeedFilter
 */
export enum FeedFilter {
  /**
   * @generated from enum value: FEED_FILTER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Public posts + posts from followed casts
   *
   * @generated from enum value: FEED_FILTER_ALL = 1;
   */
  ALL = 1,

  /**
   * Posts from followed casts only
   *
   * @generated from enum value: FEED_FILTER_FOLLOWING = 2;
   */
  FOLLOWING = 2,

  /**
   * Posts from favorited casts only
   *
   * @generated from enum value: FEED_FILTER_FAVORITES = 3;
   */
  FAVORITES = 3,
}

/**
 * Describes the enum feed.v1.FeedFilter.
 */
export const FeedFilterSchema: GenEnum<FeedFilter> = /*@__PURE__*/
  enumDesc(file_feed_v1_feed_service, 0);

/**
 * @generated from service feed.v1.FeedService
 */
export const FeedService: GenService<{
  /**
   * Guest feed: personalized feed based on filter
   *
   * @generated from rpc feed.v1.FeedService.ListGuestFeed
   */
  listGuestFeed: {
    methodKind: "unary";
    input: typeof ListGuestFeedRequestSchema;
    output: typeof ListGuestFeedResponseSchema;
  },
  /**
   * Cast feed: cast's own posts for management
   *
   * @generated from rpc feed.v1.FeedService.ListCastFeed
   */
  listCastFeed: {
    methodKind: "unary";
    input: typeof ListCastFeedRequestSchema;
    output: typeof ListCastFeedResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_feed_v1_feed_service, 0);

