apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: monolith
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: monorepo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: panicboat@gmail.com
        name: panicboat
      messageTemplate: |
        chore(monolith): bump image to {{range .Changed.Changes}}{{ println .NewValue }}{{end}}
    push:
      branch: main
  update:
    path: ./services/monolith/kubernetes
    strategy: Setters
