---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: scaffold-cron-workflow
  options:
    disableNameSuffixHash: true
patches:
- path: configmap/scaffold-cron-workflow.yaml
resources:
- cronworkflow/scaffold-cron-workflow.yaml
openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json
