# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: social/v1/block_service.proto

require 'google/protobuf'

require 'profile/v1/service_pb'


descriptor_data = "\n\x1dsocial/v1/block_service.proto\x12\tsocial.v1\x1a\x18profile/v1/service.proto\":\n\x0c\x42lockRequest\x12*\n\x11target_account_id\x18\x01 \x01(\tR\x0ftargetAccountId\"\x0f\n\rBlockResponse\"<\n\x0eUnblockRequest\x12*\n\x11target_account_id\x18\x01 \x01(\tR\x0ftargetAccountId\"\x11\n\x0fUnblockResponse\"B\n\x12ListBlockedRequest\x12\x14\n\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n\x06\x63ursor\x18\x02 \x01(\tR\x06\x63ursor\"\x82\x01\n\x13ListBlockedResponse\x12/\n\x08profiles\x18\x01 \x03(\x0b\x32\x13.profile.v1.ProfileR\x08profiles\x12\x1f\n\x0bnext_cursor\x18\x02 \x01(\tR\nnextCursor\x12\x19\n\x08has_more\x18\x03 \x01(\x08R\x07hasMore\"E\n\x15GetBlockStatusRequest\x12,\n\x12target_account_ids\x18\x01 \x03(\tR\x10targetAccountIds\"\x9e\x01\n\x16GetBlockStatusResponse\x12H\n\x07\x62locked\x18\x01 \x03(\x0b\x32..social.v1.GetBlockStatusResponse.BlockedEntryR\x07\x62locked\x1a:\n\x0c\x42lockedEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x08R\x05value:\x02\x38\x01\x32\xb1\x02\n\x0c\x42lockService\x12:\n\x05\x42lock\x12\x17.social.v1.BlockRequest\x1a\x18.social.v1.BlockResponse\x12@\n\x07Unblock\x12\x19.social.v1.UnblockRequest\x1a\x1a.social.v1.UnblockResponse\x12L\n\x0bListBlocked\x12\x1d.social.v1.ListBlockedRequest\x1a\x1e.social.v1.ListBlockedResponse\x12U\n\x0eGetBlockStatus\x12 .social.v1.GetBlockStatusRequest\x1a!.social.v1.GetBlockStatusResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Social
  module V1
    BlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.BlockRequest").msgclass
    BlockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.BlockResponse").msgclass
    UnblockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.UnblockRequest").msgclass
    UnblockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.UnblockResponse").msgclass
    ListBlockedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.ListBlockedRequest").msgclass
    ListBlockedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.ListBlockedResponse").msgclass
    GetBlockStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.GetBlockStatusRequest").msgclass
    GetBlockStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.GetBlockStatusResponse").msgclass
  end
end
