# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", "~> 3.0", ">= 3.0.2"
gem "hanami-action", "~> 3.0", ">= 3.0.1"
gem "hanami-assets", "~> 3.0"
gem "hanami-db", "~> 3.0"
gem "hanami-router", "~> 3.0"
gem "hanami-view", "~> 3.0", ">= 3.0.2"

gem "grpc"
gem "gruf"
gem "stripe"
gem "aws-sdk-s3", "~> 1.232", ">= 1.232.3"
gem "aws-sdk-cognitoidentityprovider", "~> 1.154"

gem "pg"

gem "dry-types", "~> 1.9", ">= 1.9.1"
# Keep dry-validation because hanami-validations was retired in Hanami 3.
gem "dry-validation"
gem "dry-operation", ">= 1.1.0"
gem "puma"
gem "opentelemetry-sdk", "~> 1.13", ">= 1.13.1"
gem "opentelemetry-instrumentation-all", "~> 0.97"
gem "opentelemetry-exporter-otlp", "~> 0.37"
gem "rake"
gem "sqlite3"
gem "dotenv"

group :development do
  gem "hanami-webconsole", "~> 3.0"
  # Pin grpc-tools because descriptor annotations vary by version and Ruby 4.0 needs a recent release.
  gem "grpc-tools", "1.84.0"
end

group :development, :test do
  gem "faker", "~> 3.8"
end

group :cli, :development do
  gem "hanami-reloader", "~> 3.0"
end

group :cli, :development, :test do
  gem "hanami-rspec", "~> 3.0"
end

group :test do
  gem "database_cleaner-sequel"

  gem "capybara"
  gem "rack-test"
end
