# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: profile/v1/service.proto for package 'profile.v1'

require 'grpc'
require 'profile/v1/service_pb'

module Profile
  module V1
    module ProfileService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'profile.v1.ProfileService'

        rpc :GetProfile, ::Profile::V1::GetProfileRequest, ::Profile::V1::GetProfileResponse
        rpc :GetProfileByUsername, ::Profile::V1::GetProfileByUsernameRequest, ::Profile::V1::GetProfileResponse
        rpc :ListMyProfiles, ::Profile::V1::ListMyProfilesRequest, ::Profile::V1::ListMyProfilesResponse
        rpc :CreateProfile, ::Profile::V1::CreateProfileRequest, ::Profile::V1::CreateProfileResponse
        rpc :SaveProfile, ::Profile::V1::SaveProfileRequest, ::Profile::V1::SaveProfileResponse
        rpc :CheckUsernameAvailability, ::Profile::V1::CheckUsernameAvailabilityRequest, ::Profile::V1::CheckUsernameAvailabilityResponse
        rpc :SaveProfileMedia, ::Profile::V1::SaveProfileMediaRequest, ::Profile::V1::SaveProfileMediaResponse
        rpc :DisableProfile, ::Profile::V1::DisableProfileRequest, ::Profile::V1::DisableProfileResponse
        rpc :EnableProfile, ::Profile::V1::EnableProfileRequest, ::Profile::V1::EnableProfileResponse
        rpc :DeleteProfile, ::Profile::V1::DeleteProfileRequest, ::Profile::V1::DeleteProfileResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
