// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file relationship/v1/favorite_service.proto (package relationship.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file relationship/v1/favorite_service.proto.
 */
export const file_relationship_v1_favorite_service: GenFile = /*@__PURE__*/
  fileDesc("CiZyZWxhdGlvbnNoaXAvdjEvZmF2b3JpdGVfc2VydmljZS5wcm90bxIPcmVsYXRpb25zaGlwLnYxIioKEkFkZEZhdm9yaXRlUmVxdWVzdBIUCgxjYXN0X3VzZXJfaWQYASABKAkiJgoTQWRkRmF2b3JpdGVSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIi0KFVJlbW92ZUZhdm9yaXRlUmVxdWVzdBIUCgxjYXN0X3VzZXJfaWQYASABKAkiKQoWUmVtb3ZlRmF2b3JpdGVSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIjUKFExpc3RGYXZvcml0ZXNSZXF1ZXN0Eg0KBWxpbWl0GAEgASgFEg4KBmN1cnNvchgCIAEoCSJVChVMaXN0RmF2b3JpdGVzUmVzcG9uc2USFQoNY2FzdF91c2VyX2lkcxgBIAMoCRITCgtuZXh0X2N1cnNvchgCIAEoCRIQCghoYXNfbW9yZRgDIAEoCCIxChhHZXRGYXZvcml0ZVN0YXR1c1JlcXVlc3QSFQoNY2FzdF91c2VyX2lkcxgBIAMoCSKbAQoZR2V0RmF2b3JpdGVTdGF0dXNSZXNwb25zZRJMCglmYXZvcml0ZWQYASADKAsyOS5yZWxhdGlvbnNoaXAudjEuR2V0RmF2b3JpdGVTdGF0dXNSZXNwb25zZS5GYXZvcml0ZWRFbnRyeRowCg5GYXZvcml0ZWRFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAg6AjgBMpoDCg9GYXZvcml0ZVNlcnZpY2USWAoLQWRkRmF2b3JpdGUSIy5yZWxhdGlvbnNoaXAudjEuQWRkRmF2b3JpdGVSZXF1ZXN0GiQucmVsYXRpb25zaGlwLnYxLkFkZEZhdm9yaXRlUmVzcG9uc2USYQoOUmVtb3ZlRmF2b3JpdGUSJi5yZWxhdGlvbnNoaXAudjEuUmVtb3ZlRmF2b3JpdGVSZXF1ZXN0GicucmVsYXRpb25zaGlwLnYxLlJlbW92ZUZhdm9yaXRlUmVzcG9uc2USXgoNTGlzdEZhdm9yaXRlcxIlLnJlbGF0aW9uc2hpcC52MS5MaXN0RmF2b3JpdGVzUmVxdWVzdBomLnJlbGF0aW9uc2hpcC52MS5MaXN0RmF2b3JpdGVzUmVzcG9uc2USagoRR2V0RmF2b3JpdGVTdGF0dXMSKS5yZWxhdGlvbnNoaXAudjEuR2V0RmF2b3JpdGVTdGF0dXNSZXF1ZXN0GioucmVsYXRpb25zaGlwLnYxLkdldEZhdm9yaXRlU3RhdHVzUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message relationship.v1.AddFavoriteRequest
 */
export type AddFavoriteRequest = Message<"relationship.v1.AddFavoriteRequest"> & {
  /**
   * @generated from field: string cast_user_id = 1;
   */
  castUserId: string;
};

/**
 * Describes the message relationship.v1.AddFavoriteRequest.
 * Use `create(AddFavoriteRequestSchema)` to create a new message.
 */
export const AddFavoriteRequestSchema: GenMessage<AddFavoriteRequest> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 0);

/**
 * @generated from message relationship.v1.AddFavoriteResponse
 */
export type AddFavoriteResponse = Message<"relationship.v1.AddFavoriteResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message relationship.v1.AddFavoriteResponse.
 * Use `create(AddFavoriteResponseSchema)` to create a new message.
 */
export const AddFavoriteResponseSchema: GenMessage<AddFavoriteResponse> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 1);

/**
 * @generated from message relationship.v1.RemoveFavoriteRequest
 */
export type RemoveFavoriteRequest = Message<"relationship.v1.RemoveFavoriteRequest"> & {
  /**
   * @generated from field: string cast_user_id = 1;
   */
  castUserId: string;
};

/**
 * Describes the message relationship.v1.RemoveFavoriteRequest.
 * Use `create(RemoveFavoriteRequestSchema)` to create a new message.
 */
export const RemoveFavoriteRequestSchema: GenMessage<RemoveFavoriteRequest> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 2);

/**
 * @generated from message relationship.v1.RemoveFavoriteResponse
 */
export type RemoveFavoriteResponse = Message<"relationship.v1.RemoveFavoriteResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message relationship.v1.RemoveFavoriteResponse.
 * Use `create(RemoveFavoriteResponseSchema)` to create a new message.
 */
export const RemoveFavoriteResponseSchema: GenMessage<RemoveFavoriteResponse> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 3);

/**
 * @generated from message relationship.v1.ListFavoritesRequest
 */
export type ListFavoritesRequest = Message<"relationship.v1.ListFavoritesRequest"> & {
  /**
   * default: 100, max: 200
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * optional, for pagination
   *
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message relationship.v1.ListFavoritesRequest.
 * Use `create(ListFavoritesRequestSchema)` to create a new message.
 */
export const ListFavoritesRequestSchema: GenMessage<ListFavoritesRequest> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 4);

/**
 * @generated from message relationship.v1.ListFavoritesResponse
 */
export type ListFavoritesResponse = Message<"relationship.v1.ListFavoritesResponse"> & {
  /**
   * @generated from field: repeated string cast_user_ids = 1;
   */
  castUserIds: string[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 3;
   */
  hasMore: boolean;
};

/**
 * Describes the message relationship.v1.ListFavoritesResponse.
 * Use `create(ListFavoritesResponseSchema)` to create a new message.
 */
export const ListFavoritesResponseSchema: GenMessage<ListFavoritesResponse> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 5);

/**
 * @generated from message relationship.v1.GetFavoriteStatusRequest
 */
export type GetFavoriteStatusRequest = Message<"relationship.v1.GetFavoriteStatusRequest"> & {
  /**
   * @generated from field: repeated string cast_user_ids = 1;
   */
  castUserIds: string[];
};

/**
 * Describes the message relationship.v1.GetFavoriteStatusRequest.
 * Use `create(GetFavoriteStatusRequestSchema)` to create a new message.
 */
export const GetFavoriteStatusRequestSchema: GenMessage<GetFavoriteStatusRequest> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 6);

/**
 * @generated from message relationship.v1.GetFavoriteStatusResponse
 */
export type GetFavoriteStatusResponse = Message<"relationship.v1.GetFavoriteStatusResponse"> & {
  /**
   * cast_user_id -> is_favorited
   *
   * @generated from field: map<string, bool> favorited = 1;
   */
  favorited: { [key: string]: boolean };
};

/**
 * Describes the message relationship.v1.GetFavoriteStatusResponse.
 * Use `create(GetFavoriteStatusResponseSchema)` to create a new message.
 */
export const GetFavoriteStatusResponseSchema: GenMessage<GetFavoriteStatusResponse> = /*@__PURE__*/
  messageDesc(file_relationship_v1_favorite_service, 7);

/**
 * @generated from service relationship.v1.FavoriteService
 */
export const FavoriteService: GenService<{
  /**
   * @generated from rpc relationship.v1.FavoriteService.AddFavorite
   */
  addFavorite: {
    methodKind: "unary";
    input: typeof AddFavoriteRequestSchema;
    output: typeof AddFavoriteResponseSchema;
  },
  /**
   * @generated from rpc relationship.v1.FavoriteService.RemoveFavorite
   */
  removeFavorite: {
    methodKind: "unary";
    input: typeof RemoveFavoriteRequestSchema;
    output: typeof RemoveFavoriteResponseSchema;
  },
  /**
   * @generated from rpc relationship.v1.FavoriteService.ListFavorites
   */
  listFavorites: {
    methodKind: "unary";
    input: typeof ListFavoritesRequestSchema;
    output: typeof ListFavoritesResponseSchema;
  },
  /**
   * @generated from rpc relationship.v1.FavoriteService.GetFavoriteStatus
   */
  getFavoriteStatus: {
    methodKind: "unary";
    input: typeof GetFavoriteStatusRequestSchema;
    output: typeof GetFavoriteStatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_relationship_v1_favorite_service, 0);

