---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nginx
  namespace: default
  labels:
    service: nginx
spec:
  imageRepositoryRef:
    name: nginx
  policy:
    semver:
      range: ">=1.0.0"
