---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  image: 559744160976.dkr.ecr.ap-northeast-1.amazonaws.com/sandbox/nginx
  interval: 1m0s
