# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: social/v1/favorite_service.proto for package 'social.v1'

require 'grpc'
require 'social/v1/favorite_service_pb'

module Social
  module V1
    module FavoriteService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'social.v1.FavoriteService'

        rpc :AddFavorite, ::Social::V1::AddFavoriteRequest, ::Social::V1::AddFavoriteResponse
        rpc :RemoveFavorite, ::Social::V1::RemoveFavoriteRequest, ::Social::V1::RemoveFavoriteResponse
        rpc :ListFavorites, ::Social::V1::ListFavoritesRequest, ::Social::V1::ListFavoritesResponse
        rpc :GetFavoriteStatus, ::Social::V1::GetFavoriteStatusRequest, ::Social::V1::GetFavoriteStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
