# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: social/v1/like_service.proto

require 'google/protobuf'


descriptor_data = "\n\x1csocial/v1/like_service.proto\x12\tsocial.v1\".\n\x13LikeCastPostRequest\x12\x17\n\x07post_id\x18\x01 \x01(\tR\x06postId\"7\n\x14LikeCastPostResponse\x12\x1f\n\x0blikes_count\x18\x01 \x01(\x05R\nlikesCount\"0\n\x15UnlikeCastPostRequest\x12\x17\n\x07post_id\x18\x01 \x01(\tR\x06postId\"9\n\x16UnlikeCastPostResponse\x12\x1f\n\x0blikes_count\x18\x01 \x01(\x05R\nlikesCount\"5\n\x18GetPostLikeStatusRequest\x12\x19\n\x08post_ids\x18\x01 \x03(\tR\x07postIds\"\x9c\x01\n\x19GetPostLikeStatusResponse\x12\x45\n\x05liked\x18\x01 \x03(\x0b\x32/.social.v1.GetPostLikeStatusResponse.LikedEntryR\x05liked\x1a\x38\n\nLikedEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x08R\x05value:\x02\x38\x01\x32\x95\x02\n\x0bLikeService\x12O\n\x0cLikeCastPost\x12\x1e.social.v1.LikeCastPostRequest\x1a\x1f.social.v1.LikeCastPostResponse\x12U\n\x0eUnlikeCastPost\x12 .social.v1.UnlikeCastPostRequest\x1a!.social.v1.UnlikeCastPostResponse\x12^\n\x11GetPostLikeStatus\x12#.social.v1.GetPostLikeStatusRequest\x1a$.social.v1.GetPostLikeStatusResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Social
  module V1
    LikeCastPostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.LikeCastPostRequest").msgclass
    LikeCastPostResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.LikeCastPostResponse").msgclass
    UnlikeCastPostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.UnlikeCastPostRequest").msgclass
    UnlikeCastPostResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.UnlikeCastPostResponse").msgclass
    GetPostLikeStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.GetPostLikeStatusRequest").msgclass
    GetPostLikeStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("social.v1.GetPostLikeStatusResponse").msgclass
  end
end
