# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: social/v1/service.proto for package 'social.v1'

require 'grpc'
require 'social/v1/service_pb'

module Social
  module V1
    module TimelineService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'social.v1.TimelineService'

        rpc :ListCastPosts, ::Social::V1::ListCastPostsRequest, ::Social::V1::ListCastPostsResponse
        rpc :SaveCastPost, ::Social::V1::SaveCastPostRequest, ::Social::V1::SaveCastPostResponse
        rpc :DeleteCastPost, ::Social::V1::DeleteCastPostRequest, ::Social::V1::DeleteCastPostResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
