# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: identity/v1/service.proto for package 'identity.v1'

require 'grpc'
require 'identity/v1/service_pb'

module Identity
  module V1
    module IdentityService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'identity.v1.IdentityService'

        rpc :HealthCheck, ::Identity::V1::HealthCheckRequest, ::Identity::V1::HealthCheckResponse
        # Use Phone Number to send SMS verification code
        rpc :SendSms, ::Identity::V1::SendSmsRequest, ::Identity::V1::SendSmsResponse
        # Verify SMS code to get a verification token
        rpc :VerifySms, ::Identity::V1::VerifySmsRequest, ::Identity::V1::VerifySmsResponse
        # Register with Phone (verified) and Password
        rpc :Register, ::Identity::V1::RegisterRequest, ::Identity::V1::RegisterResponse
        # Login with Phone and Password
        rpc :Login, ::Identity::V1::LoginRequest, ::Identity::V1::LoginResponse
        # Refresh access token using refresh token
        rpc :RefreshToken, ::Identity::V1::RefreshTokenRequest, ::Identity::V1::RefreshTokenResponse
        # Logout by revoking refresh token
        rpc :Logout, ::Identity::V1::LogoutRequest, ::Identity::V1::LogoutResponse
        # Get current user session
        rpc :GetCurrentUser, ::Google::Protobuf::Empty, ::Identity::V1::UserProfile
      end

      Stub = Service.rpc_stub_class
    end
  end
end
