---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./services/nginx/kubernetes/overlays/production"
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  targetNamespace: default
  postBuild:
    substitute:
      service_name: nginx
