name: 'Build Kubernetes Manifests'
description: 'Build Kubernetes manifests using Kustomize'

inputs:
  source-path:
    description: 'Source path for kustomize build'
    required: true
  service-name:
    description: 'Service name for kubernetes manifest generation'
    required: true

outputs:
  status:
    description: 'Build status (success or failure)'
    value: ${{ steps.build.outputs.status }}
  output-file:
    description: 'Path to generated manifest file'
    value: ${{ steps.build.outputs.output-file }}
  build-failed:
    description: 'Whether build failed (true/false)'
    value: ${{ steps.build.outputs.build-failed }}

runs:
  using: 'composite'
  steps:
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2
      with:
        kustomize-version: "5.0.0"

    - name: Validate Kubernetes directory structure
      shell: bash
      run: ${{ github.action_path }}/scripts/validate-structure.sh "${{ inputs.source-path }}" "${{ inputs.service-name }}"

    - name: Build Kubernetes manifests
      id: build
      shell: bash
      run: ${{ github.action_path }}/scripts/build-manifests.sh "${{ inputs.source-path }}" "${{ inputs.service-name }}"
