environments:
  - environment: develop
    aws_region: ap-northeast-1
    iam_role_plan: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
    iam_role_apply: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role

  - environment: staging
    aws_region: ap-northeast-1
    iam_role_plan: arn:aws:iam::123456789012:role/terragrunt-plan-staging-role
    iam_role_apply: arn:aws:iam::123456789012:role/terragrunt-apply-staging-role

  - environment: production
    aws_region: ap-northeast-1
    iam_role_plan: arn:aws:iam::123456789012:role/terragrunt-plan-production-role
    iam_role_apply: arn:aws:iam::123456789012:role/terragrunt-apply-production-role

directory_conventions:
  terragrunt: "{service}/terragrunt/envs/{environment}"
  kubernetes: "{service}/kubernetes/overlays/{environment}"

services:
  - name: claude-code-action
    directory_conventions:
      terragrunt: .github/actions/{service}/terragrunt/envs/{environment}
      kubernetes: .github/actions/{service}/kubernetes/overlays/{environment}

  - name: github-repository
    exclude_from_automation: true
    exclusion_config:
      reason: "When deployed in parallel, GitHub's exclusion control deadlocks the state."
      type: "permanent"

defaults:
  aws_region: ap-northeast-1
  iam_role_plan: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
  iam_role_apply: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role

modules:
  terraform_version: "1.12.1"
  terragrunt_version: "0.81.0"
  kubectl_version: "1.28.0"
  kustomize_version: "5.0.0"

# Branch-to-environment mapping configuration
branch_patterns:
  develop:
    target_environment: develop
  staging:
    pattern: "staging/*"
    target_environment: staging
  production:
    pattern: "production/*"
    target_environment: production

# Safety checks configuration
safety_checks:
  require_merged_pr: true      # Require PR information for all deployments
  fail_on_missing_pr: true     # Stop deployment if no PR found
  max_retry_attempts: 3        # Retry attempts for API failures
  allowed_direct_push_branches: []  # Emergency override branches (empty for strict mode)
