// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file identity/v1/service.proto (package identity.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file identity/v1/service.proto.
 */
export const file_identity_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChlpZGVudGl0eS92MS9zZXJ2aWNlLnByb3RvEgtpZGVudGl0eS52MSIUChJIZWFsdGhDaGVja1JlcXVlc3QiJQoTSGVhbHRoQ2hlY2tSZXNwb25zZRIOCgZzdGF0dXMYASABKAkyYwoPSWRlbnRpdHlTZXJ2aWNlElAKC0hlYWx0aENoZWNrEh8uaWRlbnRpdHkudjEuSGVhbHRoQ2hlY2tSZXF1ZXN0GiAuaWRlbnRpdHkudjEuSGVhbHRoQ2hlY2tSZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message identity.v1.HealthCheckRequest
 */
export type HealthCheckRequest = Message<"identity.v1.HealthCheckRequest"> & {
};

/**
 * Describes the message identity.v1.HealthCheckRequest.
 * Use `create(HealthCheckRequestSchema)` to create a new message.
 */
export const HealthCheckRequestSchema: GenMessage<HealthCheckRequest> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 0);

/**
 * @generated from message identity.v1.HealthCheckResponse
 */
export type HealthCheckResponse = Message<"identity.v1.HealthCheckResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;
};

/**
 * Describes the message identity.v1.HealthCheckResponse.
 * Use `create(HealthCheckResponseSchema)` to create a new message.
 */
export const HealthCheckResponseSchema: GenMessage<HealthCheckResponse> = /*@__PURE__*/
  messageDesc(file_identity_v1_service, 1);

/**
 * @generated from service identity.v1.IdentityService
 */
export const IdentityService: GenService<{
  /**
   * @generated from rpc identity.v1.IdentityService.HealthCheck
   */
  healthCheck: {
    methodKind: "unary";
    input: typeof HealthCheckRequestSchema;
    output: typeof HealthCheckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_identity_v1_service, 0);

