# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", "~> 2.3.2"
gem "hanami-assets", "~> 2.3.0"
gem "hanami-controller", "~> 2.3.1"
gem "hanami-db", "~> 2.3.0"
gem "hanami-router", "~> 2.3.1"
gem "hanami-validations", "~> 2.3.0"
gem "hanami-view", "~> 2.3.1"

gem "grpc"
gem "gruf"
gem "aws-sdk-s3", "~> 1.213"

gem "jwt"
gem "bcrypt"
gem "pg"

gem "dry-types", "~> 1.9", ">= 1.9.1"
gem "dry-operation", ">= 1.1.0"
gem "puma"
gem "rake"
gem "sqlite3"
gem "dotenv"

group :development do
  gem "hanami-webconsole", "~> 2.3.1"
  gem "grpc-tools"
end

group :development, :test do
  gem "faker", "~> 3.2"
end

group :cli, :development do
  gem "hanami-reloader", "~> 2.3.0"
end

group :cli, :development, :test do
  gem "hanami-rspec", "~> 2.3.1"
end

group :test do
  # Database
  gem "database_cleaner-sequel"

  # Web integration
  gem "capybara"
  gem "rack-test"
end
