name: Scaffold argo-workflows manifests
description: Create argo-workflows manifests
inputs:
  service:
    description: 'Service name'
    required: true
  owner:
    description: 'Owner name'
    required: true
  namespace:
    description: 'Workflow namespace'
    required: true
  kind:
    description: 'Workflow kind'
    required: true
  name:
    description: 'Workflow name'
    required: true
  overlays:
    default: 'develop,production,staging'
    description: 'Environment to be deployed. Please enter comma-separated entries.'
    required: true
  service_account_name:
    description: 'Service account name'
    required: false
  is_create_brank_patches:
    default: 'true'
    description: 'Add an empty patch file to each environment. This makes editing a little easier when there are environment differences.'
    required: false
  working_directory:
    default: '.github/actions/scaffold-argo-workflows'
    description: 'The working directory for the action.'
    required: false
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{inputs.working_directory}}

    - run: ruby src/main.rb
      shell: bash
      env:
        WORKSPACE: ${{ github.workspace }}
        SERVICE: ${{inputs.service}}
        OWNER: ${{inputs.owner}}
        NAMESPACE: ${{inputs.namespace}}
        KIND: ${{inputs.kind}}
        NAME: ${{inputs.name}}
        OVERLAYS: ${{inputs.overlays}}
        SERVICE_ACCOUNT_NAME: ${{inputs.service_account_name}}
        IS_CREATE_BLANK_PATCHES: ${{inputs.is_create_brank_patches}}
      working-directory: ${{inputs.working_directory}}
