apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment-slack.yaml
  - deployment-alertmanager.yaml
  - ingress.yaml
  - service-slack.yaml
  - service-alertmanager.yaml
