# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offer/v1/service.proto

require 'google/protobuf'


descriptor_data = "\n\x16offer/v1/service.proto\x12\x08offer.v1\"\x92\x01\n\x04Plan\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n\x05price\x18\x03 \x01(\x05R\x05price\x12)\n\x10\x64uration_minutes\x18\x04 \x01(\x05R\x0f\x64urationMinutes\x12%\n\x0eis_recommended\x18\x05 \x01(\x08R\risRecommended\"3\n\x0fGetPlansRequest\x12 \n\x0c\x63\x61st_user_id\x18\x01 \x01(\tR\ncastUserId\"8\n\x10GetPlansResponse\x12$\n\x05plans\x18\x01 \x03(\x0b\x32\x0e.offer.v1.PlanR\x05plans\"8\n\x10SavePlansRequest\x12$\n\x05plans\x18\x01 \x03(\x0b\x32\x0e.offer.v1.PlanR\x05plans\"9\n\x11SavePlansResponse\x12$\n\x05plans\x18\x01 \x03(\x0b\x32\x0e.offer.v1.PlanR\x05plans\"X\n\x08Schedule\x12\x12\n\x04\x64\x61te\x18\x01 \x01(\tR\x04\x64\x61te\x12\x1d\n\nstart_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n\x08\x65nd_time\x18\x03 \x01(\tR\x07\x65ndTime\"q\n\x13GetSchedulesRequest\x12 \n\x0c\x63\x61st_user_id\x18\x01 \x01(\tR\ncastUserId\x12\x1d\n\nstart_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n\x08\x65nd_date\x18\x03 \x01(\tR\x07\x65ndDate\"H\n\x14GetSchedulesResponse\x12\x30\n\tschedules\x18\x01 \x03(\x0b\x32\x12.offer.v1.ScheduleR\tschedules\"H\n\x14SaveSchedulesRequest\x12\x30\n\tschedules\x18\x01 \x03(\x0b\x32\x12.offer.v1.ScheduleR\tschedules\"I\n\x15SaveSchedulesResponse\x12\x30\n\tschedules\x18\x01 \x03(\x0b\x32\x12.offer.v1.ScheduleR\tschedules2\xb8\x02\n\x0cOfferService\x12\x41\n\x08GetPlans\x12\x19.offer.v1.GetPlansRequest\x1a\x1a.offer.v1.GetPlansResponse\x12\x44\n\tSavePlans\x12\x1a.offer.v1.SavePlansRequest\x1a\x1b.offer.v1.SavePlansResponse\x12M\n\x0cGetSchedules\x12\x1d.offer.v1.GetSchedulesRequest\x1a\x1e.offer.v1.GetSchedulesResponse\x12P\n\rSaveSchedules\x12\x1e.offer.v1.SaveSchedulesRequest\x1a\x1f.offer.v1.SaveSchedulesResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Offer
  module V1
    Plan = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.Plan").msgclass
    GetPlansRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.GetPlansRequest").msgclass
    GetPlansResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.GetPlansResponse").msgclass
    SavePlansRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.SavePlansRequest").msgclass
    SavePlansResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.SavePlansResponse").msgclass
    Schedule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.Schedule").msgclass
    GetSchedulesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.GetSchedulesRequest").msgclass
    GetSchedulesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.GetSchedulesResponse").msgclass
    SaveSchedulesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.SaveSchedulesRequest").msgclass
    SaveSchedulesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("offer.v1.SaveSchedulesResponse").msgclass
  end
end
