name: 'claude-code-action / terragrunt apply'

on:
  push:
    branches:
      - main
    paths:
      - 'github-actions/claude-code-action/terragrunt/modules/**'
      - 'github-actions/claude-code-action/terragrunt/envs/**'
      - 'github-actions/claude-code-action/terragrunt/root.hcl'

jobs:
  call-apply-workflow:
    uses: ./.github/workflows/terragrunt-apply-reusable.yml
    with:
      working_directory: './github-actions/claude-code-action/terragrunt'
      tf_version: '1.5.0'
      terragrunt_version: '0.58.0'
      aws_region: 'us-east-1'
      auto_approve: true
      max_parallel: 1
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
