name: 'Example Service - CI/CD'

on:
  pull_request:
    branches: [develop, staging/*, production/*]
    paths:
      - 'github-oidc-auth/**'
      - '.github/workflows/github-oidc-auth-*.yaml'
  push:
    branches: [develop, staging/*, production/*]
    paths:
      - 'github-oidc-auth/**'

jobs:
  terragrunt-orchestrator:
    uses: ./.github/workflows/reusable-terragrunt-orchestrator.yaml
    with:
      project_name: github-oidc-auth
      terraform_version: '1.5.7'
      terragrunt_version: '0.53.2'
      action_type: ${{ github.event_name == 'pull_request' && 'plan' || 'apply' }}
