name: 'GitHub OIDC Auth - CI/CD'

on:
  pull_request:
    paths:
      - 'github-oidc-auth/**'
      - '.github/workflows/github-oidc-auth-*.yaml'
  push:
    paths:
      - 'github-oidc-auth/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:
  terragrunt-plan:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reusable-terragrunt-plan.yaml
    with:
      project_name: github-oidc-auth

  terragrunt-apply:
    if: github.event_name == 'push'
    uses: ./.github/workflows/reusable-terragrunt-apply.yaml
    with:
      project_name: github-oidc-auth
