name: 'Optimized Terragrunt Orchestrator'

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      action_type:
        required: true
        type: string

jobs:
  detect-environments:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.detect.outputs.environments }}
      has_changes: ${{ steps.detect.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: detect
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          else
            FILES=$(git diff --name-only HEAD~1..HEAD)
          fi

          ENVIRONMENTS=$(echo "$FILES" | grep -E "^${{ inputs.project_name }}/terragrunt/envs/[^/]+/" | sed "s|^${{ inputs.project_name }}/terragrunt/envs/||" | cut -d'/' -f1 | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
          HAS_CHANGES=$([ "$ENVIRONMENTS" != "[]" ] && echo "true" || echo "false")

          echo "environments=$ENVIRONMENTS" >> $GITHUB_OUTPUT
          echo "has_changes=$HAS_CHANGES" >> $GITHUB_OUTPUT

  execute-environments:
    needs: detect-environments
    if: needs.detect-environments.outputs.has_changes == 'true'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-environments.outputs.environments) }}
      fail-fast: false
    uses: ./.github/workflows/optimized-terragrunt.yaml
    secrets: inherit
    with:
      project_name: ${{ inputs.project_name }}
      environment: ${{ matrix.environment }}
      action_type: ${{ inputs.action_type }}
