name: 'Reusable - Kubernetes Executor'

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
        description: 'Service name for kubernetes manifest generation'
      environment:
        required: true
        type: string
        description: 'Environment name (develop, staging, production, etc.)'
      action-type:
        required: false
        type: string
        default: diff
        description: 'Action type: diff (plan/preview) or apply (execute)'
      working-directory:
        required: true
        type: string
        description: 'Working directory for kustomize execution'
      target-repository:
        required: true
        type: string
        description: 'Target repository for generated manifests'
      target-branch:
        required: true
        type: string
        description: 'Target branch for generated manifests'
      target-directory:
        required: true
        type: string
        description: 'Target directory within the repository for generated manifests'
      app-id:
        required: true
        type: string
        description: 'GitHub App ID for authentication'
    secrets:
      private-key:
        required: true
        description: 'GitHub App private key for authentication'

jobs:
  diff-manifests:
    name: 'Diff Kubernetes Manifests'
    if: inputs.action-type == 'diff'
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private-key }}
          owner: ${{ github.repository_owner }}

      - name: Get PR information
        id: pr-info
        uses: jwalton/gh-find-current-pr@v1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          state: all
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Kustomize Diff
        id: kustomize-diff
        uses: swade1987/github-action-kustomize-diff@v0.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          root_dir: ${{ inputs.working-directory }}

      - name: Comment PR with Kustomize results
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## 🚀 Kustomize ${{ inputs.action-type }} Results

            **Service**: `${{ inputs.service-name }}`
            **Environment**: `${{ inputs.environment }}`

            <details>
            <summary>📋 Kustomize Output</summary>

            ```diff
            ${{ steps.kustomize-diff.outputs.diff }}
            ```
            </details>
          comment-tag: "kustomize-${{ inputs.service-name }}-${{ inputs.environment }}"
          mode: upsert
          pr-number: ${{ steps.pr-info.outputs.number }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        continue-on-error: true

  push-to-repo:
    name: 'Push Kubernetes Manifests to GitOps Repository'
    if: inputs.action-type == 'apply'
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private-key }}
          owner: ${{ github.repository_owner }}

      - name: Get PR information
        id: pr-info
        uses: jwalton/gh-find-current-pr@v1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          state: all
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Build Kubernetes manifests
        id: kustomize
        uses: int128/kustomize-action@v1
        with:
          kustomization: ${{ inputs.working-directory }}/kustomization.yaml

      - name: Push Generated Manifests
        id: git-pr
        uses: panicboat/deploy-actions/git-pr@main
        with:
          service-name: ${{ inputs.service-name }}
          environment: ${{ inputs.environment }}
          pr-number: ${{ steps.pr-info.outputs.number }}
          source-file: ${{ steps.kustomize.outputs.directory }}/${{ inputs.working-directory }}/generated.yaml
          target-repository: ${{ inputs.target-repository }}
          target-branch: ${{ inputs.target-branch }}
          target-path: ${{ inputs.target-directory }}/${{ inputs.service-name }}.yaml
          github-token: ${{ steps.app-token.outputs.token }}
