name: 'Reusable - Kubernetes Executor'

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
        description: 'Service name for kubernetes manifest generation'
      environment:
        required: true
        type: string
        description: 'Environment name (develop, staging, production, etc.)'
      source-path:
        required: true
        type: string
        description: 'Source path for kustomize build (e.g., demo-service/kubernetes/overlays/develop)'
      target-repository:
        required: false
        type: string
        default: panicboat/generated-manifests
        description: 'Target repository for generated manifests (e.g., panicboat/generated-manifests)'
      target-branch:
        required: false
        type: string
        default: main
        description: 'Target branch for generated manifests'
    secrets:
      APP_PRIVATE_KEY:
        required: true
        description: 'GitHub App private key for authentication'

jobs:
  kubernetes-execution:
    name: 'Kubernetes Manifest Generation - ${{ inputs.service-name }}:${{ inputs.environment }}'
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "5.0.0"

      - name: Validate Kubernetes directory structure
        run: |
          if [ ! -d "${{ inputs.source-path }}" ]; then
            echo "::error::Kustomize directory not found: ${{ inputs.source-path }}"
            echo "Expected kustomize directory structure with overlays for each environment"
            exit 1
          fi

          KUSTOMIZATION_FILE="${{ inputs.source-path }}/kustomization.yaml"
          if [ ! -f "$KUSTOMIZATION_FILE" ]; then
            echo "::error::kustomization.yaml not found: $KUSTOMIZATION_FILE"
            exit 1
          fi

          echo "✅ Kustomize structure validated for ${{ inputs.service-name }}:${{ inputs.environment }}"

      - name: Build Kubernetes manifests
        id: kustomize-build
        run: |
          OUTPUT_FILE="/tmp/${{ inputs.service-name }}-generated.yaml"

          echo "Building manifests from: ${{ inputs.source-path }}"
          kustomize build "${{ inputs.source-path }}" > "$OUTPUT_FILE"

          if [ ! -s "$OUTPUT_FILE" ]; then
            echo "::error::Generated manifest file is empty"
            exit 1
          fi

          echo "output-file=$OUTPUT_FILE" >> $GITHUB_OUTPUT
          echo "✅ Successfully built manifests for ${{ inputs.service-name }}"
        continue-on-error: true

      - name: Parse build results
        if: always()
        id: parse-results
        run: |
          STATUS=$([ "${{ steps.kustomize-build.outcome }}" == "success" ] && echo "✅ Success" || echo "❌ Failed")
          echo "status=$STATUS" >> $GITHUB_OUTPUT

          if [ "${{ steps.kustomize-build.outcome }}" == "failure" ]; then
            echo "build-failed=true" >> $GITHUB_OUTPUT
          else
            echo "build-failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout target repository
        if: steps.parse-results.outputs.build-failed == 'false'
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target-repository }}
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.target-branch }}
          path: generated-manifests

      - name: Configure Git for target repository
        if: steps.parse-results.outputs.build-failed == 'false'
        working-directory: generated-manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get source PR information
        id: pr-info
        uses: jwalton/gh-find-current-pr@v1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          state: all
        continue-on-error: true

      - name: Update manifests using gotk-helper
        if: steps.parse-results.outputs.build-failed == 'false' && steps.pr-info.outputs.number
        id: gotk-update
        working-directory: generated-manifests
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # Execute gotk-helper with PR-based approach
          cd ../.github/scripts/gotk-helper

          bundle exec bin/gotk-helper update_from_pr ${{ steps.pr-info.outputs.number }} \
            --manifest-file="${{ steps.kustomize-build.outputs.output-file }}" \
            --target-repo="${{ inputs.target-repository }}" \
            --target-branch="${{ inputs.target-branch }}" \
            --service-name="${{ inputs.service-name }}" \
            --environment="${{ inputs.environment }}"

          # Check exit code for success/failure
          if [ $? -eq 0 ]; then
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "✅ Successfully executed gotk-helper for PR #${{ steps.pr-info.outputs.number }}"
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "❌ gotk-helper execution failed for PR #${{ steps.pr-info.outputs.number }}"
            exit 1
          fi

      - name: Update source PR with generation results
        if: steps.pr-info.outputs.number
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## ☸️ Kubernetes Manifest Generation Results

            **Service**: ${{ inputs.service-name }}
            **Environment**: `${{ inputs.environment }}`
            **Status**: ${{ steps.parse-results.outputs.status }}
            **Target Repository**: [${{ inputs.target-repository }}](https://github.com/${{ inputs.target-repository }})
            **Generated File**: `${{ inputs.environment }}/${{ inputs.service-name }}.yaml`

            ### 📋 Generation Details
            - **Source Path**: `${{ inputs.source-path }}`
            - **Commit**: [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            - **Target Branch**: `${{ inputs.target-branch }}`
            ${{ steps.parse-results.outputs.build-failed == 'false' && steps.gotk-update.outputs.has-changes == 'false' && '- **Changes**: No manifest changes detected' || '' }}
            ${{ steps.parse-results.outputs.build-failed == 'false' && steps.gotk-update.outputs.has-changes == 'true' && '- **Status**: Manifest update completed via gotk-helper' || '' }}

            [View workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ---
            *Generated by Kubernetes manifest automation*
          comment-tag: 'kubernetes-manifest-${{ inputs.environment }}-${{ inputs.service-name }}'
          mode: upsert
          pr-number: ${{ steps.pr-info.outputs.number }}
        continue-on-error: true

      - name: Exit with appropriate code
        run: |
          if [ "${{ steps.kustomize-build.outcome }}" == "failure" ]; then
            echo "::error::Kubernetes manifest generation failed for ${{ inputs.service-name }}:${{ inputs.environment }}"
            exit 1
          fi

          if [ "${{ steps.parse-results.outputs.build-failed }}" == "false" ] && [ "${{ steps.gotk-update.outputs.has-changes }}" == "true" ]; then
            echo "✅ Successfully executed gotk-helper for ${{ inputs.service-name }}:${{ inputs.environment }}"
          elif [ "${{ steps.parse-results.outputs.build-failed }}" == "false" ]; then
            echo "ℹ️ No changes detected for ${{ inputs.service-name }}:${{ inputs.environment }}"
          fi
