name: 'reusable / nodejs ci'

on:
  workflow_call:
    inputs:
      service_path:
        description: 'Path to the service directory'
        required: true
        type: string
      node_version:
        description: 'Node.js version'
        required: false
        type: string
        default: '20'
      enable_lint:
        description: 'Enable linting'
        required: false
        type: boolean
        default: true
      enable_test:
        description: 'Enable testing'
        required: false
        type: boolean
        default: true
      enable_build:
        description: 'Enable building'
        required: false
        type: boolean
        default: true
      cache_dependency_path:
        description: 'Path to package-lock.json for caching'
        required: false
        type: string
        default: ''

jobs:
  nodejs-ci:
    name: 'Node.js CI'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache_dependency_path || format('{0}/package-lock.json', inputs.service_path) }}

    - name: Install dependencies
      run: |
        cd ${{ inputs.service_path }}
        if [ -f package.json ]; then
          npm ci
          echo "Dependencies installed successfully"
        else
          echo "No package.json found, skipping npm install"
          exit 0
        fi

    - name: Run linting
      if: inputs.enable_lint
      run: |
        cd ${{ inputs.service_path }}
        if [ -f package.json ]; then
          if npm run lint --if-present; then
            echo "Linting completed successfully"
          else
            echo "Linting failed or no lint script found"
            # Don't fail the job if linting script doesn't exist
            if npm run lint 2>&1 | grep -q "missing script"; then
              echo "No lint script found, skipping"
              exit 0
            else
              exit 1
            fi
          fi
        else
          echo "No package.json found, skipping linting"
        fi

    - name: Run tests
      if: inputs.enable_test
      run: |
        cd ${{ inputs.service_path }}
        if [ -f package.json ]; then
          if npm run test --if-present; then
            echo "Tests completed successfully"
          else
            echo "Tests failed or no test script found"
            # Don't fail the job if test script doesn't exist
            if npm run test 2>&1 | grep -q "missing script"; then
              echo "No test script found, skipping"
              exit 0
            else
              exit 1
            fi
          fi
        else
          echo "No package.json found, skipping tests"
        fi

    - name: Build application
      if: inputs.enable_build
      run: |
        cd ${{ inputs.service_path }}
        if [ -f package.json ]; then
          if npm run build --if-present; then
            echo "Build completed successfully"
          else
            echo "Build failed or no build script found"
            # Don't fail the job if build script doesn't exist
            if npm run build 2>&1 | grep -q "missing script"; then
              echo "No build script found, skipping"
              exit 0
            else
              exit 1
            fi
          fi
        else
          echo "No package.json found, skipping build"
        fi

    - name: Upload build artifacts
      if: inputs.enable_build
      uses: actions/upload-artifact@v4
      with:
        name: nodejs-build-${{ github.sha }}
        path: |
          ${{ inputs.service_path }}/dist/
          ${{ inputs.service_path }}/build/
          ${{ inputs.service_path }}/out/
        retention-days: 1
        if-no-files-found: ignore
