name: 'Reusable - Kubernetes Executor'

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
        description: 'Service name for kubernetes manifest generation'
      environment:
        required: true
        type: string
        description: 'Environment name (develop, staging, production, etc.)'
      action-type:
        required: false
        type: string
        default: diff
        description: 'Action type: diff (plan/preview) or apply (execute)'
      working-directory:
        required: true
        type: string
        description: 'Working directory for kustomize execution'
      target-repository:
        required: true
        type: string
        description: 'Target repository for generated manifests'
      target-branch:
        required: true
        type: string
        description: 'Target branch for generated manifests'
      app-id:
        required: true
        type: string
        description: 'GitHub App ID for authentication'
    secrets:
      private-key:
        required: true
        description: 'GitHub App private key for authentication'

jobs:
  execute-kubernetes:
    name: 'Push Kubernetes Manifests to GitOps Repository'
    if: inputs.action-type != ''
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private-key }}
          owner: ${{ github.repository_owner }}

      - name: Get PR information
        id: pr-info
        uses: jwalton/gh-find-current-pr@v1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          state: all
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Build Kubernetes manifests
        id: kustomize
        uses: int128/kustomize-action@v1
        with:
          kustomization: ${{ inputs.working-directory }}/kustomization.yaml

      - name: Push Generated Manifests
        id: git-push
        uses: panicboat/deploy-actions/git-push@main
        with:
          source-file: ${{ steps.kustomize.outputs.directory }}/${{ inputs.working-directory }}/generated.yaml
          service-name: ${{ inputs.service-name }}
          environment: ${{ inputs.environment }}
          target-repository: ${{ inputs.target-repository }}
          target-branch: ${{ inputs.target-branch }}
          github-token: ${{ steps.app-token.outputs.token }}
          pr-number: ${{ steps.pr-info.outputs.number }}
