---
name: '- Scaffold argo-workflows'
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name'
        required: true
      owner:
        description: 'Owner name'
        required: true
      namespace:
        description: 'Workflow namespace'
        required: true
        type: choice
        options:
          - workflow
          - workflow-secure
      kind:
        description: 'Workflow kind'
        required: true
        type: choice
        options:
          - CronWorkflow
          - WorkflowTemplate
      name:
        description: 'Workflow name'
        required: true
      overlays:
        default: 'develop,production,staging'
        description: 'Environment to be deployed. Please enter comma-separated entries.'
        required: true
      is_create_brank_patches:
        default: 'true'
        description: 'Add an empty patch file to each environment. This makes editing a little easier when there are environment differences.'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  scaffold:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SANDBOX_APP_ID }}
          private-key: ${{ secrets.SANDBOX_PRIVATE_KEY }}

      - uses: ./.github/actions/scaffold-argo-workflows
        id: scaffold
        with:
          service: ${{ github.event.inputs.service }}
          owner: ${{ github.event.inputs.owner }}
          namespace: ${{ github.event.inputs.namespace }}
          kind: ${{ github.event.inputs.kind }}
          name: ${{ github.event.inputs.name }}
          overlays: ${{ github.event.inputs.overlays }}
          is_create_brank_patches: ${{ github.event.inputs.is_create_brank_patches }}

      - uses: int128/update-generated-files-action@v2
        with:
          token: ${{ steps.token.outputs.token }}
          reviewers: panicboat
